/* migration: نقل مفاتيح التخزين من الاسم القديم الى mrzahi_ مرة واحدة لكل متصفح، فلا يفقد احد لغته ولا ثيمه ولا حسابه المختار */
try{["lang","theme","org","sidebar","dash_tab","bell_seen","chat_seen","cal_mode","cal_zoom","dp_cal","drive_folder","tr"].forEach(function(k){var o=localStorage.getItem("record_"+k);if(o!==null&&localStorage.getItem("mrzahi_"+k)===null){localStorage.setItem("mrzahi_"+k,o);localStorage.removeItem("record_"+k);}});}catch(e){}
    const translations = {
      ar: {
        exportXlsx: "تصدير Excel",
        exportBtn: "تصدير",
        caseFileTitle: "ملف القضية",
        caseFileEmpty: "لا عناصر تحت هذه القضية بعد.",
        secSessions: "الجلسات",
        secRulings: "الأحكام",
        secExecutions: "طلبات التنفيذ",
        secViolations: "المخالفات",
        secTasks: "المهام",
        secDocuments: "المستندات",
        fieldCourt: "المحكمة",
        fieldStage: "المرحلة",
        openCaseFile: "ملف القضية",
        appName: "MrZahi",
        exportCsv: "تصدير CSV",
        title: "لوحة التحكم",
        loading: "جاري التحميل...",
        serviceUnavailableTitle: "تعذر الاتصال بالخدمة",
        serviceUnavailableText: "انقطع الاتصال بالخدمة. تحقق من اتصالك ثم أعد المحاولة.",
        noOrg: "لا توجد شركة محددة، أنشئ شركتك أولا.",
        planLimitItems: "وصلت إلى الحد الأقصى لعدد العناصر في باقتك الحالية، رق باقتك لإضافة المزيد.",
        planLimitMembers: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية، رق باقتك لإضافة المزيد.",
        planLimitLink: "عرض الباقات والأسعار",
        genericError: "حدث خطأ، حاول مرة أخرى.",
        errorLoad: "تعذر تحميل البيانات، حاول مرة أخرى.",
        saved: "تم الحفظ.",
        deleted: "تم الحذف.",
        companyLabel: "الشركة:",
        switchOrg: "التبديل بين الشركات",
        newOrgBtn: "+ إضافة حساب",
        renameOrgBtn: "تعديل الاسم",
        deleteOrgBtn: "حذف الشركة",
        orgRenamed: "تم تعديل اسم الشركة.",
        deleteOrgConfirm: "ستحذف الشركة «{name}» وكل عناصرها وسجلاتها نهائيا. هل تتابع؟",
        newOrgPlaceholder: "اسم الجهة",
        selfNamePlaceholder: "اسمك الكامل",
        newOrgSubmit: "إنشاء",
        cancel: "إلغاء",
        createOrgTitle: "ابدأ حسابك",
        createOrgIntro: "اختر نوع الحساب: شركة أو مؤسسة أو وثيقة عمل حر، أو شخصي لمن يرتب أوراقه.",
        packPickLine: "اختر الواجهة التي تناسب تخصصك.",
        packChoose: "اختيار",
        orgCreated: "تم إنشاء الحساب بنجاح.",
        orgNameRequired: "أدخل الاسم.",
        joinTitle: "أو انضم إلى حساب قائم",
        joinIntro: "إن كان لك عمل في شركة مسجلة هنا، اكتب رقم حسابها وسيصل صاحبه طلبك.",
        joinCodePlaceholder: "رقم الحساب",
        joinSubmit: "إرسال الطلب",
        joinSent: "أرسل طلبك، وستدخل الحساب حين يقبله صاحبه.",
        joinPending: "طلبك إلى {org} بانتظار الموافقة.",
        joinNotFound: "لا حساب بهذا الرقم.",
        joinAlready: "أنت عضو في هذا الحساب.",
        joinCodeRequired: "اكتب رقم الحساب.",
        linkImport: "استيراد ملف",
        linkTeam: "الفريق",
        linkSettings: "الإعدادات",
        linkAdmin: "إدارة المنصة",
        signOut: "تسجيل الخروج",
        statOpen: "عناصر مفتوحة",
        statDue7: "مستحقة خلال 7 أيام",
        statOverdue: "متأخرة",
        statDone: "مكتملة",
        tabList: "القائمة",
        timelineTitle: "إنجازاتك",
        tlNow: "الآن",
        tlDayEvents: "{n} احداث في {d}",
        tlMonths: "تصفح الاشهر",
        tlPrev: "المعلم السابق",
        tlNext: "المعلم التالي",
        tlEventOf: "الحدث {i} من {n}",
        timelineEmpty: "لا نشاط بعد — ابدأ باستيراد ملف أو إضافة موعد.",
        tlCreated: "أضيف عنصر",
        tlDone: "أنجز",
        tlImport: "استيراد ملف",
        tlAttachment: "رفع ملف",
        tlMember: "انضم عضو",
        tlPlan: "اشتراك",
        tlToday: "اليوم",
        tlYesterday: "أمس",
        tlDaysAgo: "قبل {n} يوما",
        achDoneMonth: "أنجز هذا الشهر",
        achItems: "إجمالي العناصر",
        achFiles: "الملفات",
        achImports: "عمليات الاستيراد",
        colVNumber: "رقم المخالفة",
        colCaseNumber: "رقم الدعوى",
        caseBundleTitle: "ملف الدعوى {n}",
        caseBundleEmpty: "لا توجد عناصر مرتبطة بهذا الرقم.",
        colVDate: "تاريخ المخالفة",
        colClient: "الشركة",
        colIssuer: "جهة الإصدار",
        colAmount: "المبلغ",
        colVType: "نوع المخالفة",
        colObjection: "حالة التظلم",
        colPayDue: "موعد السداد",
        allClients: "كل الشركات",
        totalCount: "عدد المخالفات",
        totalAmount: "إجمالي المبالغ",
        totalUnpaid: "غير المسددة",
        totalOverdue: "تجاوزت موعد السداد",
        attachTitle: "المرفقات",
        attachDrive: "اختيار من Google Drive",
        attachUpload: "رفع ملف (PDF أو Word)",
        attachLinkPlaceholder: "أو الصق رابط Google Drive",
        attachLinkBtn: "إضافة الرابط",
        attachEmpty: "لا مرفقات لهذا العنصر.",
        attachUploading: "جاري الرفع...",
        attachDone: "تمت الإضافة.",
        attachFailed: "تعذر رفع الملف.",
        attachLimit: "تجاوزت مساحة التخزين المسموحة في باقتك.",
        attachDeleteConfirm: "حذف المرفق نهائيا؟",
        attachLinkLabel: "رابط خارجي",
        delete: "حذف",
        chartTitle: "المؤشر (جدول المخالفات)",
        indicatorsTitle: "المؤشرات الحالية للمخالفات والجلسات",
        courtsTitle: "إجمالي القضايا {n} (حسب المحكمة)",
        cancelledAmount: "مبلغ المخالفات التي تم إلغاؤها",
        noCourtData: "لا توجد بيانات محاكم بعد.",
        chartTotal: "إجمالي المخالفات",
        chartObjected: "تم التظلم فيها",
        chartCourt: "مرفوعة للمحكمة",
        chartRepeated: "المخالفات المتكررة",
        casesIndicatorsTitle: "المؤشرات الحالية للقضايا",
        indicatorsFor: "المؤشرات الحالية — {name}", indTableOf: "المؤشر (جدول {name})", byPartyTitle: "{name} {n}",
        indTotal: "الإجمالي", indOpen: "جارية", indOverdue: "متأخرة عن موعدها", indDone: "منتهية",
        indAmountTotal: "إجمالي المبالغ", indAmountDone: "مبالغ المنتهية",
        indMine: "مؤشراتي", indMyPapers: "أوراقي ومواعيدي", indPapers: "أوراق مسجلة", indPapersSoon: "تنتهي خلال 30 يوما", indMyAppts: "مواعيدي القادمة",
        indPapersExpired: "منتهية", indOpenItems: "عناصر مفتوحة", indRegular: "{n} عنصرا منتظما بتذكير",
        casesChartTitle: "المؤشر (جدول القضايا)",
        caseTotal: "إجمالي القضايا",
        caseOpen: "قضايا جارية",
        caseOverdue: "متأخرة عن موعدها",
        caseDone: "قضايا منتهية",
        clientsTitle: "العملاء {n} (حسب العميل)",
        noClientData: "لا توجد بيانات عملاء بعد.",
        caseAmount: "إجمالي مبالغ القضايا",
        caseDoneAmount: "مبالغ القضايا المنتهية",
        viewCases: "لوحة القضايا",
        viewExpenses: "مصاريف التشغيل",
        viewHealth: "صحتي",
        viewRulings: "لوحة الأحكام",
        viewContracts: "لوحة العقود", viewDeals: "لوحة الصفقات",
        fieldDealStage: "مرحلة الصفقة", fieldDealProbability: "احتمال الإغلاق %", fieldDealSource: "مصدر العميل",
        dealStageLead: "عميل محتمل", dealStageContact: "تواصل", dealStageProposal: "عرض سعر",
        dealStageNegotiation: "تفاوض", dealStageWon: "ربحت", dealStageLost: "خسرت",
        dealsPipeline: "قيمة خط الأنابيب", dealsWon: "المربوح هذا الشهر", dealsOpen: "صفقات مفتوحة", dealsRate: "معدل التحويل",
        /* المالية: الفاتورة ومستحقاتها وضريبتها، لا «مصروف» بحالة مفتوح/منجز */
        viewInvoices: "لوحة الفواتير",
        fieldFinNumber: "رقم الفاتورة", fieldFinDir: "اتجاه الفاتورة", fieldFinIssued: "تاريخ الاصدار",
        fieldFinVat: "الضريبة", fieldFinAmount: "مبلغ الفاتورة", fieldFinPaid: "المحصل حتى الان",
        fieldFinPaidAt: "تاريخ التحصيل", fieldFinMethod: "طريقة السداد",
        financeDirIn: "مدين (فاتورة على عميل)", financeDirOut: "دائن (فاتورة من مورد)",
        financeDirInShort: "مدين", financeDirOutShort: "دائن", financeDirAll: "كل الاتجاهات",
        financeVatExclusive: "تضاف 15%", financeVatInclusive: "شامل 15%", financeVatExempt: "معفاة بلا ضريبة",
        financeStateAll: "كل الحالات", financeStateDue: "مستحقة", financeStatePartial: "محصلة جزئيا",
        financeStateOverdue: "متاخرة", financeStateCollected: "محصلة", financeStateCancelled: "ملغاة",
        financePartyAll: "كل الجهات", finActionCollect: "تحصيل",
        finTotalCount: "عدد الفواتير", finTotalReceivable: "المستحق لنا",
        finTotalPayable: "المستحق علينا", finTotalOverdue: "المتاخر",
        finIndicatorsTitle: "مؤشرات المالية", finMonthlyTitle: "التحصيل شهرا بشهر {y}",
        finTopDebtorsTitle: "اكبر المدينين", noDebtorData: "لا جهة عليها مبلغ متبق",
        finDueToday: "المستحق اليوم", finCollectedMonth: "المحصل هذا الشهر",
        finAvgDays: "متوسط ايام التحصيل",
        colFinNumber: "رقم الفاتورة", colFinSubject: "البيان", colFinParty: "الجهة",
        colFinIssued: "تاريخ الاصدار", colFinDue: "تاريخ الاستحقاق", colFinBase: "قبل الضريبة",
        colFinVat: "الضريبة", colFinTotal: "الاجمالي", colFinPaid: "المحصل", colFinRemain: "المتبقي",
        /* الموارد البشرية: الموظف واجازاته ودوراته ومؤهلاته (حزمة hr وحدها) */
        viewStaff: "لوحة الموظفين", viewLeaves: "لوحة الاجازات", viewTraining: "لوحة الدورات والمؤهلات",
        fieldStaffName: "اسم الموظف", fieldStaffNameEn: "الاسم بالانجليزية", fieldStaffPhone: "الجوال",
        fieldStaffEmail: "البريد الالكتروني", fieldStaffDept: "القسم", fieldStaffJob: "المسمى الوظيفي",
        fieldStaffContract: "نوع التعاقد", fieldStaffStage: "الحالة الوظيفية", fieldStaffHired: "تاريخ التعيين",
        fieldStaffNationality: "الجنسية", fieldStaffId: "رقم الهوية او الاقامة", fieldStaffIdExpiry: "انتهاء الهوية او الاقامة",
        fieldStaffContractEnd: "انتهاء العقد", fieldStaffSalary: "الراتب الاساسي", fieldStaffHousing: "بدل السكن",
        fieldStaffTransport: "بدل النقل", fieldStaffOther: "بدلات اخرى", fieldStaffLeaveDays: "رصيد الاجازة السنوية (يوما)",
        fieldStaffIban: "الايبان",
        staffContractNone: "غير محدد", staffContractFixed: "محدد المدة", staffContractOpen: "غير محدد المدة",
        staffContractPart: "دوام جزئي", staffContractTemp: "مؤقت او موسمي", staffContractRemote: "عن بعد",
        staffStageCandidate: "مرشح", staffStageProbation: "تحت التجربة", staffStageActive: "على راس العمل",
        staffStageNotice: "فترة اشعار", staffStageEnded: "انتهت خدمته",
        staffDeptAll: "كل الاقسام", staffStageAll: "كل الحالات",
        staffTotalActive: "على راس العمل", staffTotalPayroll: "الرواتب الشهرية",
        staffTotalExpiring: "اقامات وعقود انتهت او تنتهي خلال 60 يوما", staffTotalOnLeave: "في اجازة اليوم",
        staffBasicShort: "اساسي {n}",
        colStaffNumber: "الرقم الوظيفي", colStaffName: "الموظف", colStaffDept: "القسم", colStaffJob: "المسمى الوظيفي",
        colStaffContract: "التعاقد", colStaffHired: "التعيين", colStaffSalary: "الراتب الاجمالي",
        colStaffIdExpiry: "انتهاء الاقامة", colStaffContractEnd: "انتهاء العقد", colStaffLeft: "المتبقي",
        colStaffLeaveBalance: "رصيد الاجازة",
        openStaffFile: "ملف الموظف", staffFileLeaves: "الاجازات", staffFileTraining: "الدورات والمؤهلات",
        staffFileBalance: "رصيد الاجازة السنوية", staffFileEmpty: "لا اجازات ولا دورات مسجلة لهذا الموظف بعد.",
        fieldLeaveTitle: "البيان (اختياري)", fieldLeaveEmployee: "الموظف", fieldLeaveKind: "نوع الاجازة",
        fieldLeaveApproval: "الاعتماد", fieldLeaveFrom: "من تاريخ", fieldLeaveTo: "الى تاريخ",
        fieldLeaveDays: "عدد الايام", fieldLeaveReturn: "تاريخ المباشرة", fieldLeaveNote: "السبب او الملاحظة",
        leavePickEmployee: "اختر الموظف", leaveEmployeeRequired: "اختر الموظف اولا.",
        leaveDatesRequired: "اكتب تاريخ بداية الاجازة.",
        leaveKindAnnual: "سنوية", leaveKindSick: "مرضية", leaveKindEmergency: "اضطرارية", leaveKindUnpaid: "بلا راتب",
        leaveKindMaternity: "امومة", leaveKindPaternity: "ابوة", leaveKindMarriage: "زواج", leaveKindBereavement: "وفاة",
        leaveKindHajj: "حج", leaveKindStudy: "دراسية", leaveKindOther: "اخرى",
        leaveApprovalPending: "بانتظار الاعتماد", leaveApprovalApproved: "معتمدة", leaveApprovalRejected: "مرفوضة",
        leaveApprovalCancelled: "ملغاة", leaveStateOngoing: "جارية الان", leaveStateFinished: "انتهت",
        leaveEmpAll: "كل الموظفين", leaveKindAll: "كل الانواع", leaveStateAll: "كل الحالات",
        leaveTotalPending: "بانتظار الاعتماد", leaveTotalToday: "في اجازة اليوم",
        leaveTotalSickYear: "ايام مرضية هذه السنة", leaveTotalAnnualYear: "ايام سنوية معتمدة هذه السنة",
        colLeaveEmployee: "الموظف", colLeaveKind: "نوع الاجازة", colLeaveFrom: "من", colLeaveTo: "الى",
        colLeaveDays: "الايام", colLeaveLeft: "تبدا بعد", colLeaveApproval: "الاعتماد", colLeaveNote: "البيان",
        actionApprove: "اعتماد", actionReject: "رفض", leaveApproved: "اعتمدت الاجازة.", leaveRejected: "رفضت الاجازة.",
        fieldTrainName: "اسم الدورة او المؤهل", fieldTrainEmployee: "الموظف", fieldTrainKind: "نوع السجل",
        fieldTrainProvider: "الجهة المانحة", fieldTrainDate: "تاريخ الدورة او التخرج", fieldTrainExpiry: "انتهاء الشهادة",
        fieldTrainHours: "عدد الساعات", fieldTrainDegree: "الدرجة العلمية", fieldTrainMajor: "التخصص",
        fieldTrainResult: "النتيجة او التقدير",
        trainKindCourse: "دورة تدريبية", trainKindDegree: "مؤهل علمي", trainKindCert: "شهادة مهنية",
        trainEmpAll: "كل الموظفين", trainKindAll: "كل الانواع",
        trainTotalCourses: "دورات", trainTotalDegrees: "مؤهلات", trainTotalExpiring: "شهادات انتهت او تنتهي خلال 90 يوما",
        trainTotalHours: "ساعات التدريب",
        colTrainEmployee: "الموظف", colTrainKind: "النوع", colTrainName: "الدورة او المؤهل", colTrainProvider: "الجهة",
        colTrainDate: "التاريخ", colTrainDegree: "الدرجة والتخصص", colTrainHours: "الساعات",
        colTrainExpiry: "انتهاء الشهادة", colTrainLeft: "المتبقي",
        storePickLine: "أين تحفظ ملفاتك؟ يمكنك تغيير الاختيار لاحقا من الإعدادات.",
        storePickPlatform: "خادم مستر زاهي داخل المملكة",
        storePickPlatformHint: "ملفاتك تحفظ على خادمنا المحلي في جدة، ضمن حصة باقتك.",
        storePickDrive: "Google Drive الخاص بك",
        storePickDriveHint: "في Drive الخاص بك، خارج حصة الباقة.",
        storePickDriveDenied: "لم يصل إذن Google، فبقي الحفظ على خادم مستر زاهي داخل المملكة.",
        colCNumber: "رقم العقد",
        colCSubject: "موضوع العقد",
        colCParty: "الطرف الآخر",
        colCType: "نوع العقد",
        colCStart: "تاريخ البدء",
        colCEnd: "تاريخ الانتهاء",
        colCLeft: "المتبقي",
        colCValue: "قيمة العقد",
        colCRenewal: "التجديد",
        fieldCNumber: "رقم العقد",
        fieldCType: "نوع العقد",
        fieldCStart: "تاريخ البدء",
        fieldCRenewal: "التجديد",
        fieldCNotice: "مهلة الإشعار قبل الانتهاء (أيام)",
        renewalAuto: "تلقائي",
        renewalManual: "يدوي",
        renewalNone: "لا يتجدد",
        contractActive: "ساري",
        contractSoon: "تقترب مهلته",
        contractEnded: "منته",
        allParties: "كل الأطراف",
        allContractTypes: "كل الأنواع",
        allContractStates: "كل الحالات",
        totalContracts: "عدد العقود",
        totalContractValue: "إجمالي القيم",
        totalContractSoon: "تقترب مهلتها",
        totalContractEnded: "منتهية",
        noticeShort: "إشعار قبل %s يوما",
        colExpDate: "التاريخ",
        colExpCat: "البند",
        colExpDesc: "البيان",
        colExpVendor: "الجهة",
        colExpMethod: "طريقة الدفع",
        allCats: "كل البنود",
        allYears: "كل السنوات",
        expCount: "عدد المصاريف",
        expTotal: "إجمالي المصروف",
        expPaid: "المدفوع",
        expDue: "المستحق",
        expOverdue: "متأخر السداد",
        expAvgMonth: "متوسط الشهر",
        expIndicatorsTitle: "مؤشرات المصاريف",
        expMonthlyTitle: "المصروف شهريا ({y})",
        expByCatTitle: "حسب البند ({n})",
        noExpenseData: "لا توجد مبالغ مسجلة بعد",
        expNoCat: "بلا بند",
        expStatusPaid: "مدفوع",
        expActionPay: "تعليم كمدفوع",
        fieldAmount: "المبلغ",
        fieldClient: "الجهة أو العميل",
        fieldClientEn: "الجهة أو العميل بالإنجليزية",
        appealDeadline: "مهلة الاستئناف",
        appealTitle: "مهلة استئناف — {case}",
        appealCategory: "مهلة استئناف",
        nextSession: "الجلسة القادمة",
        nextSessionTitle: "جلسة — {case}",
        sessionCategory: "جلسة",
        weekTitle: "ملخص الأسبوع",
        weekDone: "أنجز هذا الأسبوع",
        weekAdded: "أضيف هذا الأسبوع",
        weekLate: "تأخر هذا الأسبوع",
        weekSame: "مثل الأسبوع الماضي",
        weekVsLast: "عن الأسبوع الماضي",
        listUpcoming: "قادمة",
        listPast: "سابقة",
        actionReschedule: "اعادة جدولة",
        colNumber: "الرقم",
        fieldRemind: "ذكرني قبل",
        remindDefault: "حسب قاعدة السجل",
        remindDay: "بيوم",
        remind3Days: "بثلاثة أيام",
        remindWeek: "بأسبوع",
        remind2Weeks: "بأسبوعين",
        remindMonth: "بشهر",
        fieldCaseNumber: "رقم الملف",
        viewViolations: "لوحة المخالفات",
        servicesTitle: "الخدمات",
        calendarCardTitle: "التقويم والمواعيد",
        startService: "بدء الخدمة",
        svcImportTitle: "استيراد من Excel",
        svcImportText: "حول جدول مواعيدك وعقودك إلى عناصر متابعة في دقيقة.",
        svcAddTitle: "إضافة موعد",
        svcAddText: "سجل جلسة أو موعد استحقاق جديدا يدويا.",
        svcTeamTitle: "دعوة زميل",
        svcTeamText: "أضف زملاءك وأسند إليهم المواعيد والمهام.",
        svcTelegramTitle: "ربط Telegram",
        svcTelegramText: "استقبل تنبيه كل موعد على Telegram قبل حلوله.",
        svcCalendarTitle: "ربط التقويم",
        svcCalendarText: "اربط مواعيدك بتقويم Google أو آبل أو أوتلوك بنقرة.",
        tabCalendar: "التقويم",
        filterAllRecords: "كل السجلات",
        filterAllStatuses: "كل الحالات",
        searchPlaceholder: "بحث في العناوين",
        statusOpen: "مفتوح",
        statusDone: "مكتمل",
        statusCancelled: "ملغى",
        statusOverdue: "متأخر",
        colTitle: "العنوان",
        colRecord: "السجل",
        colDue: "موعد الاستحقاق",
        colAssignee: "المسؤول",
        colStatus: "الحالة",
        colActions: "الإجراءات",
        noItems: "لا توجد عناصر مطابقة.",
        noDue: "بدون موعد",
        noAssignee: "غير محدد",
        actionDone: "إنجاز",
        actionReopen: "إعادة فتح",
        actionEdit: "تعديل",
        actionDelete: "حذف",
        confirmDelete: "هل تريد حذف هذا العنصر؟ لا يمكن التراجع عن الحذف.",
        editTitle: "تعديل العنصر",
        addItemBtn: "+ عنصر",
        addItemTitle: "عنصر جديد",
        fieldTitle: "العنوان",
        fieldRecord: "السجل",
        fieldDue: "موعد الاستحقاق",
        fieldCategory: "التصنيف",
        fieldAssignee: "المسؤول",
        fieldStatus: "الحالة",
        titlePlaceholder: "عنوان العنصر",
        categoryPlaceholder: "التصنيف (اختياري)",
        chooseRecord: "اختر السجل",
        save: "حفظ",
        add: "إضافة",
        titleRequired: "أدخل عنوان العنصر.",
        recordRequired: "اختر سجلا أولا.",
        newRecordBtn: "+ سجل جديد",
        newRecordPlaceholder: "اسم السجل",
        recordCreated: "تم إنشاء السجل.",
        recordNameRequired: "أدخل اسم السجل.",
        noRecordsHint: "لا توجد سجلات بعد، أنشئ سجلا أولا لتتمكن من إضافة العناصر.",
        calPrev: "الشهر السابق",
        calNext: "الشهر التالي",
        calPrevWeek: "الأسبوع السابق",
        calNextWeek: "الأسبوع التالي",
        calPrevDay: "اليوم السابق",
        calNextDay: "اليوم التالي",
        calZoomMonth: "شهر",
        calZoomWeek: "أسبوع",
        calZoomDay: "يوم",
        calMoved: "نقل الموعد.",
        calAssignHint: "انقر الاسم لتصفية مواعيده، واسحب الموعد اليه لنقل المسؤولية",
        calWhoAll: "كامل الفريق",
        calAssigned: "تغير المسؤول.",
        calToday: "اليوم",
        tileOpenWord: "{k} مفتوحة", tileDue7Word: "{k} خلال 7 ايام", tileOverdueWord: "{k} متاخرة", tileDoneWord: "{k} اغلقت",
        calFilterAll: "الكل", calFilterCases: "قضايا", calFilterViolations: "مخالفات", calFilterTasks: "مهام", calFilterMeetings: "اجتماعات", calFilterDocuments: "مستندات",
        viewMeetings: "الاجتماعات",
        fieldHealthKind: "نوع العنصر الصحي", fieldHealthDose: "الجرعة أو التفصيل", fieldHealthRepeat: "التكرار", fieldHealthUntil: "حتى تاريخ (نهاية الوصفة)",
        fieldHealthProvider: "الطبيب أو الجهة", fieldHealthNote: "ملاحظة",
        healthKindMedicine: "دواء أو علاج", healthKindAppointment: "موعد طبي", healthKindLab: "فحص أو تحليل",
        healthKindVaccine: "تطعيم", healthKindFitness: "نادي أو تمرين", healthKindInsurance: "تأمين صحي",
        healthRepeatNone: "بلا تكرار", healthRepeatDaily: "يوميا", healthRepeatWeekly: "أسبوعيا", healthRepeatMonthly: "شهريا",
        healthRepeat4h: "كل 4 ساعات", healthRepeat6h: "كل 6 ساعات", healthRepeat8h: "كل 8 ساعات", healthRepeat12h: "كل 12 ساعة",
        healthKindAll: "كل الأنواع", healthRecordName: "صحتي",
        healthStateAll: "كل الحالات", healthStateToday: "اليوم", healthStateUpcoming: "قادم", healthStateOverdue: "متأخر", healthStateDone: "تم",
        healthTotalToday: "اليوم", healthTotalOverdue: "متأخر", healthTotalRegular: "منتظم بتذكير", healthTotalSubs: "اشتراكات",
        colHItem: "العنصر", colHKind: "النوع", colHDose: "الجرعة أو التفصيل", colHRepeat: "التكرار",
        colHWhen: "الموعد", colHLeft: "المتبقي", colHProvider: "الطبيب أو الجهة", colHAmount: "المبلغ",
        calGregorian: "ميلادي",
        calHijri: "هجري",
        daySun: "الأحد",
        dayMon: "الاثنين",
        dayTue: "الثلاثاء",
        dayWed: "الأربعاء",
        dayThu: "الخميس",
        dayFri: "الجمعة",
        daySat: "السبت",
        month1: "يناير",
        month2: "فبراير",
        month3: "مارس",
        month4: "أبريل",
        month5: "مايو",
        month6: "يونيو",
        month7: "يوليو",
        month8: "أغسطس",
        month9: "سبتمبر",
        month10: "أكتوبر",
        month11: "نوفمبر",
        month12: "ديسمبر",
        moreItems: "{n} عناصر أخرى",
        icsTitle: "رابط التقويم (ICS)",
        icsHint: "أضف هذا الرابط إلى تقويم Apple أو Google أو Outlook بوصفه اشتراكا في تقويم عبر الرابط، لتظهر مواعيد عناصرك تلقائيا وتتحدث دوريا.",
        copy: "نسخ الرابط",
        copied: "تم نسخ الرابط.",
        regenerate: "إعادة توليد الرابط",
        confirmRegenerate: "سيتوقف الرابط الحالي عن العمل وسيلزمك إضافة الرابط الجديد إلى تقويمك. هل تريد المتابعة؟",
        regenerated: "تم توليد رابط جديد.",
        icsSecret: "هذا الرابط خاص بك، لا تشاركه مع الآخرين.",
        itemDone: "تم إنجاز العنصر.",
        itemReopened: "أعيد فتح العنصر.",
        itemAdded: "تمت إضافة العنصر.",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        loginLink: "تسجيل الدخول",
        dashboardLink: "لوحة التحكم",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        exportXlsx: "Export Excel",
        exportBtn: "Export",
        caseFileTitle: "Case file",
        caseFileEmpty: "Nothing filed under this case yet.",
        secSessions: "Hearings",
        secRulings: "Rulings",
        secExecutions: "Execution requests",
        secViolations: "Violations",
        secTasks: "Tasks",
        secDocuments: "Documents",
        fieldCourt: "Court",
        fieldStage: "Stage",
        openCaseFile: "Case file",
        appName: "MrZahi",
        exportCsv: "Export CSV",
        title: "Dashboard",
        loading: "Loading...",
        serviceUnavailableTitle: "Could not reach the service",
        serviceUnavailableText: "The connection to the service was lost. Check your connection and try again.",
        noOrg: "No company selected. Create your company first.",
        planLimitItems: "You have reached the item limit of your current plan. Upgrade to add more.",
        planLimitMembers: "You have reached the member limit of your current plan. Upgrade to add more.",
        planLimitLink: "View plans & pricing",
        genericError: "Something went wrong. Please try again.",
        errorLoad: "Could not load data. Please try again.",
        saved: "Saved.",
        deleted: "Deleted.",
        companyLabel: "Company:",
        switchOrg: "Switch company",
        newOrgBtn: "+ Add account",
        renameOrgBtn: "Rename",
        deleteOrgBtn: "Delete company",
        orgRenamed: "Company name updated.",
        deleteOrgConfirm: "«{name}» and all of its items and records will be permanently deleted. Continue?",
        newOrgPlaceholder: "Entity name",
        selfNamePlaceholder: "Your full name",
        newOrgSubmit: "Create",
        cancel: "Cancel",
        createOrgTitle: "Start your account",
        createOrgIntro: "Choose the account type: a company, an establishment, a freelance permit, or an individual organising their own papers.",
        packPickLine: "Choose the interface that fits your work.",
        packChoose: "Choose",
        orgCreated: "Account created successfully.",
        orgNameRequired: "Enter the name.",
        joinTitle: "Or join an existing account",
        joinIntro: "If you work at a company already registered here, enter its account number and the owner will get your request.",
        joinCodePlaceholder: "Account number",
        joinSubmit: "Send request",
        joinSent: "Your request was sent; you will join once the owner accepts it.",
        joinPending: "Your request to {org} is waiting for approval.",
        joinNotFound: "No account with that number.",
        joinAlready: "You are already a member of that account.",
        joinCodeRequired: "Enter the account number.",
        linkImport: "Import file",
        linkTeam: "Team",
        linkSettings: "Settings",
        linkAdmin: "Platform admin",
        signOut: "Sign out",
        statOpen: "Open items",
        statDue7: "Due within 7 days",
        statOverdue: "Overdue",
        statDone: "Done",
        tabList: "List",
        timelineTitle: "Your progress",
        tlNow: "NOW",
        tlDayEvents: "{n} events on {d}",
        tlMonths: "Browse months",
        tlPrev: "Previous milestone",
        tlNext: "Next milestone",
        tlEventOf: "Event {i} of {n}",
        timelineEmpty: "No activity yet — import a file or add an appointment.",
        tlCreated: "Item added",
        tlDone: "Completed",
        tlImport: "File imported",
        tlAttachment: "File uploaded",
        tlMember: "Member joined",
        tlPlan: "Subscription",
        tlToday: "Today",
        tlYesterday: "Yesterday",
        tlDaysAgo: "{n} days ago",
        achDoneMonth: "Completed this month",
        achItems: "Total items",
        achFiles: "Files",
        achImports: "Imports",
        colVNumber: "Violation no.",
        colCaseNumber: "Case no.",
        caseBundleTitle: "Case file {n}",
        caseBundleEmpty: "Nothing linked to this number.",
        colVDate: "Violation date",
        colClient: "Client",
        colIssuer: "Issuer",
        colAmount: "Amount",
        colVType: "Violation type",
        colObjection: "Appeal status",
        colPayDue: "Payment due",
        allClients: "All clients",
        totalCount: "Violations",
        totalAmount: "Total amount",
        totalUnpaid: "Unpaid",
        totalOverdue: "Past due",
        attachTitle: "Attachments",
        attachDrive: "Pick from Google Drive",
        attachUpload: "Upload a file (PDF or Word)",
        attachLinkPlaceholder: "Or paste a Google Drive link",
        attachLinkBtn: "Add link",
        attachEmpty: "No attachments for this item.",
        attachUploading: "Uploading...",
        attachDone: "Added.",
        attachFailed: "Could not upload the file.",
        attachLimit: "Your plan storage limit is exhausted.",
        attachDeleteConfirm: "Delete this attachment permanently?",
        attachLinkLabel: "external link",
        delete: "Delete",
        chartTitle: "Violations indicator",
        indicatorsTitle: "Current violation and hearing indicators",
        courtsTitle: "Cases {n} (by court)",
        cancelledAmount: "Cancelled fines amount",
        noCourtData: "No court data yet.",
        chartTotal: "Total violations",
        chartObjected: "Appealed",
        chartCourt: "Referred to court",
        chartRepeated: "Repeated violations",
        casesIndicatorsTitle: "Current case indicators",
        indicatorsFor: "Current indicators — {name}", indTableOf: "{name} indicator", byPartyTitle: "{name} {n}",
        indTotal: "Total", indOpen: "In progress", indOverdue: "Overdue", indDone: "Completed",
        indAmountTotal: "Total amount", indAmountDone: "Completed amount",
        indMine: "My indicators", indMyPapers: "My papers and dates", indPapers: "Papers on file", indPapersSoon: "Expiring within 30 days", indMyAppts: "My upcoming appointments",
        indPapersExpired: "Expired", indOpenItems: "Open items", indRegular: "{n} recurring with reminders",
        casesChartTitle: "Cases indicator",
        caseTotal: "Total cases",
        caseOpen: "Open cases",
        caseOverdue: "Overdue",
        caseDone: "Closed cases",
        clientsTitle: "Clients {n} (by client)",
        noClientData: "No client data yet.",
        caseAmount: "Total case amounts",
        caseDoneAmount: "Closed case amounts",
        viewCases: "Cases dashboard",
        viewExpenses: "Operating expenses",
        viewHealth: "My health",
        viewRulings: "Rulings dashboard",
        viewContracts: "Contracts dashboard", viewDeals: "Deals dashboard",
        fieldDealStage: "Deal stage", fieldDealProbability: "Close probability %", fieldDealSource: "Lead source",
        dealStageLead: "Lead", dealStageContact: "Contacted", dealStageProposal: "Proposal",
        dealStageNegotiation: "Negotiation", dealStageWon: "Won", dealStageLost: "Lost",
        dealsPipeline: "Pipeline value", dealsWon: "Won this month", dealsOpen: "Open deals", dealsRate: "Conversion rate",
        viewInvoices: "Invoices dashboard",
        fieldFinNumber: "Invoice number", fieldFinDir: "Invoice direction", fieldFinIssued: "Issue date",
        fieldFinVat: "VAT", fieldFinAmount: "Invoice amount", fieldFinPaid: "Collected so far",
        fieldFinPaidAt: "Collection date", fieldFinMethod: "Payment method",
        financeDirIn: "Receivable (customer invoice)", financeDirOut: "Payable (supplier invoice)",
        financeDirInShort: "Receivable", financeDirOutShort: "Payable", financeDirAll: "All directions",
        financeVatExclusive: "15% added", financeVatInclusive: "15% included", financeVatExempt: "Exempt, no VAT",
        financeStateAll: "All states", financeStateDue: "Due", financeStatePartial: "Partly collected",
        financeStateOverdue: "Overdue", financeStateCollected: "Collected", financeStateCancelled: "Cancelled",
        financePartyAll: "All parties", finActionCollect: "Collect",
        finTotalCount: "Invoices", finTotalReceivable: "Receivable",
        finTotalPayable: "Payable", finTotalOverdue: "Overdue",
        finIndicatorsTitle: "Finance indicators", finMonthlyTitle: "Collection by month {y}",
        finTopDebtorsTitle: "Top debtors", noDebtorData: "No party with an outstanding balance",
        finDueToday: "Due today", finCollectedMonth: "Collected this month",
        finAvgDays: "Average days to collect",
        colFinNumber: "Invoice no.", colFinSubject: "Description", colFinParty: "Party",
        colFinIssued: "Issued", colFinDue: "Due date", colFinBase: "Before VAT",
        colFinVat: "VAT", colFinTotal: "Total", colFinPaid: "Collected", colFinRemain: "Outstanding",
        viewStaff: "Employees dashboard", viewLeaves: "Leaves dashboard", viewTraining: "Training and qualifications",
        fieldStaffName: "Employee name", fieldStaffNameEn: "Name in English", fieldStaffPhone: "Mobile",
        fieldStaffEmail: "Email", fieldStaffDept: "Department", fieldStaffJob: "Job title",
        fieldStaffContract: "Contract type", fieldStaffStage: "Employment status", fieldStaffHired: "Hire date",
        fieldStaffNationality: "Nationality", fieldStaffId: "ID or iqama number", fieldStaffIdExpiry: "ID or iqama expiry",
        fieldStaffContractEnd: "Contract end", fieldStaffSalary: "Basic salary", fieldStaffHousing: "Housing allowance",
        fieldStaffTransport: "Transport allowance", fieldStaffOther: "Other allowances", fieldStaffLeaveDays: "Annual leave entitlement (days)",
        fieldStaffIban: "IBAN",
        staffContractNone: "Not set", staffContractFixed: "Fixed term", staffContractOpen: "Open ended",
        staffContractPart: "Part time", staffContractTemp: "Temporary or seasonal", staffContractRemote: "Remote",
        staffStageCandidate: "Candidate", staffStageProbation: "On probation", staffStageActive: "Active",
        staffStageNotice: "Notice period", staffStageEnded: "Left the company",
        staffDeptAll: "All departments", staffStageAll: "All statuses",
        staffTotalActive: "Active employees", staffTotalPayroll: "Monthly payroll",
        staffTotalExpiring: "IDs and contracts expired or expiring within 60 days", staffTotalOnLeave: "On leave today",
        staffBasicShort: "basic {n}",
        colStaffNumber: "Employee no.", colStaffName: "Employee", colStaffDept: "Department", colStaffJob: "Job title",
        colStaffContract: "Contract", colStaffHired: "Hired", colStaffSalary: "Total salary",
        colStaffIdExpiry: "ID expiry", colStaffContractEnd: "Contract end", colStaffLeft: "Remaining",
        colStaffLeaveBalance: "Leave balance",
        openStaffFile: "Employee file", staffFileLeaves: "Leaves", staffFileTraining: "Training and qualifications",
        staffFileBalance: "Annual leave balance", staffFileEmpty: "No leaves or training recorded for this employee yet.",
        fieldLeaveTitle: "Description (optional)", fieldLeaveEmployee: "Employee", fieldLeaveKind: "Leave type",
        fieldLeaveApproval: "Approval", fieldLeaveFrom: "From", fieldLeaveTo: "To",
        fieldLeaveDays: "Days", fieldLeaveReturn: "Return date", fieldLeaveNote: "Reason or note",
        leavePickEmployee: "Choose the employee", leaveEmployeeRequired: "Choose the employee first.",
        leaveDatesRequired: "Enter the leave start date.",
        leaveKindAnnual: "Annual", leaveKindSick: "Sick", leaveKindEmergency: "Emergency", leaveKindUnpaid: "Unpaid",
        leaveKindMaternity: "Maternity", leaveKindPaternity: "Paternity", leaveKindMarriage: "Marriage", leaveKindBereavement: "Bereavement",
        leaveKindHajj: "Hajj", leaveKindStudy: "Study", leaveKindOther: "Other",
        leaveApprovalPending: "Awaiting approval", leaveApprovalApproved: "Approved", leaveApprovalRejected: "Rejected",
        leaveApprovalCancelled: "Cancelled", leaveStateOngoing: "Ongoing", leaveStateFinished: "Finished",
        leaveEmpAll: "All employees", leaveKindAll: "All types", leaveStateAll: "All states",
        leaveTotalPending: "Awaiting approval", leaveTotalToday: "On leave today",
        leaveTotalSickYear: "Sick days this year", leaveTotalAnnualYear: "Approved annual days this year",
        colLeaveEmployee: "Employee", colLeaveKind: "Leave type", colLeaveFrom: "From", colLeaveTo: "To",
        colLeaveDays: "Days", colLeaveLeft: "Starts in", colLeaveApproval: "Approval", colLeaveNote: "Description",
        actionApprove: "Approve", actionReject: "Reject", leaveApproved: "Leave approved.", leaveRejected: "Leave rejected.",
        fieldTrainName: "Course or qualification name", fieldTrainEmployee: "Employee", fieldTrainKind: "Record type",
        fieldTrainProvider: "Provider", fieldTrainDate: "Course or graduation date", fieldTrainExpiry: "Certificate expiry",
        fieldTrainHours: "Hours", fieldTrainDegree: "Degree", fieldTrainMajor: "Major",
        fieldTrainResult: "Result or grade",
        trainKindCourse: "Training course", trainKindDegree: "Academic qualification", trainKindCert: "Professional certificate",
        trainEmpAll: "All employees", trainKindAll: "All types",
        trainTotalCourses: "Courses", trainTotalDegrees: "Qualifications", trainTotalExpiring: "Certificates expired or expiring within 90 days",
        trainTotalHours: "Training hours",
        colTrainEmployee: "Employee", colTrainKind: "Type", colTrainName: "Course or qualification", colTrainProvider: "Provider",
        colTrainDate: "Date", colTrainDegree: "Degree and major", colTrainHours: "Hours",
        colTrainExpiry: "Certificate expiry", colTrainLeft: "Remaining",
        storePickLine: "Where should your files be kept? You can change this later in settings.",
        storePickPlatform: "Mr.Zahi server in Saudi Arabia",
        storePickPlatformHint: "Your files are kept on our local server in Jeddah, within your plan quota.",
        storePickDrive: "Your own Google Drive",
        storePickDriveHint: "In your Drive, outside the plan quota.",
        storePickDriveDenied: "Google permission was not granted, so files stay on the Mr.Zahi server in Saudi Arabia.",
        colCNumber: "Contract No.",
        colCSubject: "Subject",
        colCParty: "Counterparty",
        colCType: "Type",
        colCStart: "Start",
        colCEnd: "End",
        colCLeft: "Remaining",
        colCValue: "Value",
        colCRenewal: "Renewal",
        fieldCNumber: "Contract number",
        fieldCType: "Contract type",
        fieldCStart: "Start date",
        fieldCRenewal: "Renewal",
        fieldCNotice: "Notice period before end (days)",
        renewalAuto: "Automatic",
        renewalManual: "Manual",
        renewalNone: "No renewal",
        contractActive: "Active",
        contractSoon: "Notice due",
        contractEnded: "Ended",
        allParties: "All counterparties",
        allContractTypes: "All types",
        allContractStates: "All states",
        totalContracts: "Contracts",
        totalContractValue: "Total value",
        totalContractSoon: "Notice due",
        totalContractEnded: "Ended",
        noticeShort: "notice %s days",
        colExpDate: "Date",
        colExpCat: "Category",
        colExpDesc: "Description",
        colExpVendor: "Payee",
        colExpMethod: "Payment method",
        allCats: "All categories",
        allYears: "All years",
        expCount: "Expenses",
        expTotal: "Total spent",
        expPaid: "Paid",
        expDue: "Outstanding",
        expOverdue: "Overdue",
        expAvgMonth: "Monthly average",
        expIndicatorsTitle: "Expense indicators",
        expMonthlyTitle: "Monthly spend ({y})",
        expByCatTitle: "By category ({n})",
        noExpenseData: "No amounts recorded yet",
        expNoCat: "Uncategorised",
        expStatusPaid: "Paid",
        expActionPay: "Mark as paid",
        fieldAmount: "Amount",
        fieldClient: "Party or client",
        fieldClientEn: "Party or client in English",
        appealDeadline: "Appeal deadline",
        appealTitle: "Appeal deadline — {case}",
        appealCategory: "Appeal deadline",
        nextSession: "Next hearing",
        nextSessionTitle: "Hearing — {case}",
        sessionCategory: "Hearing",
        weekTitle: "This week",
        weekDone: "Finished this week",
        weekAdded: "Added this week",
        weekLate: "Late this week",
        weekSame: "Same as last week",
        weekVsLast: "vs last week",
        listUpcoming: "Upcoming",
        listPast: "Past",
        actionReschedule: "Reschedule",
        colNumber: "Number",
        fieldRemind: "Remind me before",
        remindDefault: "As the record's rule says",
        remindDay: "One day",
        remind3Days: "Three days",
        remindWeek: "One week",
        remind2Weeks: "Two weeks",
        remindMonth: "One month",
        fieldCaseNumber: "File number",
        viewViolations: "Violations dashboard",
        servicesTitle: "Services",
        calendarCardTitle: "Calendar & hearings",
        startService: "Start service",
        svcImportTitle: "Import from Excel",
        svcImportText: "Turn your schedule or contracts into tracked items in a minute.",
        svcAddTitle: "Add an appointment",
        svcAddText: "Log a hearing or a due date by hand.",
        svcTeamTitle: "Invite a colleague",
        svcTeamText: "Add colleagues and assign dates and tasks to them.",
        svcTelegramTitle: "Connect Telegram",
        svcTelegramText: "Get every reminder on Telegram before it is due.",
        svcCalendarTitle: "Connect your calendar",
        svcCalendarText: "Link your dates to Google, Apple or Outlook in one click.",
        tabCalendar: "Calendar",
        filterAllRecords: "All records",
        filterAllStatuses: "All statuses",
        searchPlaceholder: "Search titles",
        statusOpen: "Open",
        statusDone: "Done",
        statusCancelled: "Cancelled",
        statusOverdue: "Overdue",
        colTitle: "Title",
        colRecord: "Record",
        colDue: "Due date",
        colAssignee: "Assignee",
        colStatus: "Status",
        colActions: "Actions",
        noItems: "No matching items.",
        noDue: "No due date",
        noAssignee: "Unassigned",
        actionDone: "Mark done",
        actionReopen: "Reopen",
        actionEdit: "Edit",
        actionDelete: "Delete",
        confirmDelete: "Delete this item? This cannot be undone.",
        editTitle: "Edit item",
        addItemBtn: "+ Item",
        addItemTitle: "New item",
        fieldTitle: "Title",
        fieldRecord: "Record",
        fieldDue: "Due date & time",
        fieldCategory: "Category",
        fieldAssignee: "Assignee",
        fieldStatus: "Status",
        titlePlaceholder: "Item title",
        categoryPlaceholder: "Category (optional)",
        chooseRecord: "Choose a record",
        save: "Save",
        add: "Add",
        titleRequired: "Enter the item title.",
        recordRequired: "Choose a record first.",
        newRecordBtn: "+ New record",
        newRecordPlaceholder: "Record name",
        recordCreated: "Record created.",
        recordNameRequired: "Enter the record name.",
        noRecordsHint: "No records yet. Create a record first to add items.",
        calPrev: "Previous month",
        calNext: "Next month",
        calPrevWeek: "Previous week",
        calNextWeek: "Next week",
        calPrevDay: "Previous day",
        calNextDay: "Next day",
        calZoomMonth: "Month",
        calZoomWeek: "Week",
        calZoomDay: "Day",
        calMoved: "Date moved.",
        calAssignHint: "Click a name to filter, drag an event onto it to reassign",
        calWhoAll: "Whole team",
        calAssigned: "Owner changed.",
        calToday: "Today",
        tileOpenWord: "Open {k}", tileDue7Word: "{k} within 7 days", tileOverdueWord: "Overdue {k}", tileDoneWord: "Closed {k}",
        calFilterAll: "All", calFilterCases: "Cases", calFilterViolations: "Violations", calFilterTasks: "Tasks", calFilterMeetings: "Meetings", calFilterDocuments: "Documents",
        viewMeetings: "Meetings",
        fieldHealthKind: "Health item type", fieldHealthDose: "Dose or detail", fieldHealthRepeat: "Repeat", fieldHealthUntil: "Until (end of prescription)",
        fieldHealthProvider: "Doctor or provider", fieldHealthNote: "Note",
        healthKindMedicine: "Medicine or treatment", healthKindAppointment: "Doctor appointment", healthKindLab: "Test or lab",
        healthKindVaccine: "Vaccine", healthKindFitness: "Gym or workout", healthKindInsurance: "Health insurance",
        healthRepeatNone: "No repeat", healthRepeatDaily: "Daily", healthRepeatWeekly: "Weekly", healthRepeatMonthly: "Monthly",
        healthRepeat4h: "Every 4 hours", healthRepeat6h: "Every 6 hours", healthRepeat8h: "Every 8 hours", healthRepeat12h: "Every 12 hours",
        healthKindAll: "All types", healthRecordName: "My health",
        healthStateAll: "All states", healthStateToday: "Today", healthStateUpcoming: "Upcoming", healthStateOverdue: "Overdue", healthStateDone: "Done",
        healthTotalToday: "Today", healthTotalOverdue: "Overdue", healthTotalRegular: "Recurring", healthTotalSubs: "Subscriptions",
        colHItem: "Item", colHKind: "Type", colHDose: "Dose or detail", colHRepeat: "Repeat",
        colHWhen: "When", colHLeft: "Left", colHProvider: "Doctor or provider", colHAmount: "Amount",
        calGregorian: "Gregorian",
        calHijri: "Hijri",
        daySun: "Sun",
        dayMon: "Mon",
        dayTue: "Tue",
        dayWed: "Wed",
        dayThu: "Thu",
        dayFri: "Fri",
        daySat: "Sat",
        month1: "January",
        month2: "February",
        month3: "March",
        month4: "April",
        month5: "May",
        month6: "June",
        month7: "July",
        month8: "August",
        month9: "September",
        month10: "October",
        month11: "November",
        month12: "December",
        moreItems: "{n} more items",
        icsTitle: "Calendar link (ICS)",
        icsHint: "Add this link to Apple Calendar, Google Calendar or Outlook as a calendar subscription (by URL) so your item due dates appear automatically and stay up to date.",
        copy: "Copy link",
        copied: "Link copied.",
        regenerate: "Regenerate link",
        confirmRegenerate: "The current link will stop working and you will need to add the new link to your calendar. Continue?",
        regenerated: "A new link was generated.",
        icsSecret: "This link is personal. Do not share it with others.",
        itemDone: "Item marked as done.",
        itemReopened: "Item reopened.",
        itemAdded: "Item added.",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        loginLink: "Sign in",
        dashboardLink: "Dashboard",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        exportXlsx: "Exporter Excel",
        exportBtn: "Exporter",
        caseFileTitle: "Dossier",
        caseFileEmpty: "Rien encore rattaché à cette affaire.",
        secSessions: "Audiences",
        secRulings: "Jugements",
        secExecutions: "Demandes d'exécution",
        secViolations: "Infractions",
        secTasks: "Tâches",
        secDocuments: "Documents",
        fieldCourt: "Tribunal",
        fieldStage: "Étape",
        openCaseFile: "Dossier",
        appName: "MrZahi",
        exportCsv: "Exporter CSV",
        title: "Tableau de bord",
        loading: "Chargement...",
        serviceUnavailableTitle: "Service injoignable",
        serviceUnavailableText: "La connexion au service a ete perdue. Verifiez votre connexion et reessayez.",
        noOrg: "Aucune entreprise sélectionnée. Créez d'abord votre entreprise.",
        planLimitItems: "Vous avez atteint la limite d'éléments de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        planLimitMembers: "Vous avez atteint la limite de membres de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        planLimitLink: "Voir les forfaits et tarifs",
        genericError: "Une erreur est survenue. Veuillez réessayer.",
        errorLoad: "Impossible de charger les données. Veuillez réessayer.",
        saved: "Enregistré.",
        deleted: "Supprimé.",
        companyLabel: "Entreprise :",
        switchOrg: "Changer d'entreprise",
        newOrgBtn: "+ Ajouter un compte",
        renameOrgBtn: "Renommer",
        deleteOrgBtn: "Supprimer l'entreprise",
        orgRenamed: "Nom de l'entreprise mis à jour.",
        deleteOrgConfirm: "«{name}» et tous ses éléments seront supprimés définitivement. Continuer ?",
        newOrgPlaceholder: "Nom de l'entité",
        selfNamePlaceholder: "Votre nom complet",
        newOrgSubmit: "Créer",
        cancel: "Annuler",
        createOrgTitle: "Ouvrez votre compte",
        createOrgIntro: "Choisissez le type de compte : société, établissement, travail indépendant ou particulier qui organise ses papiers.",
        packPickLine: "Choisissez l'interface qui correspond a votre activite.",
        packChoose: "Choisir",
        orgCreated: "Compte créé avec succès.",
        orgNameRequired: "Saisissez le nom.",
        joinTitle: "Ou rejoignez un compte existant",
        joinIntro: "Si vous travaillez dans une entreprise deja inscrite ici, saisissez son numero de compte et son proprietaire recevra votre demande.",
        joinCodePlaceholder: "Numero de compte",
        joinSubmit: "Envoyer la demande",
        joinSent: "Votre demande est envoyee ; vous rejoindrez le compte des que le proprietaire l'accepte.",
        joinPending: "Votre demande a {org} attend une approbation.",
        joinNotFound: "Aucun compte avec ce numero.",
        joinAlready: "Vous etes deja membre de ce compte.",
        joinCodeRequired: "Saisissez le numero de compte.",
        linkImport: "Importer un fichier",
        linkTeam: "Équipe",
        linkSettings: "Paramètres",
        linkAdmin: "Administration",
        signOut: "Se déconnecter",
        statOpen: "Éléments ouverts",
        statDue7: "À échéance sous 7 jours",
        statOverdue: "En retard",
        statDone: "Terminés",
        tabList: "Liste",
        timelineTitle: "Vos réalisations",
        tlNow: "MAINTENANT",
        tlDayEvents: "{n} evenements le {d}",
        tlMonths: "Parcourir les mois",
        tlPrev: "Jalon précédent",
        tlNext: "Jalon suivant",
        tlEventOf: "Événement {i} sur {n}",
        timelineEmpty: "Aucune activité — importez un fichier ou ajoutez un rendez-vous.",
        tlCreated: "Élément ajouté",
        tlDone: "Terminé",
        tlImport: "Fichier importé",
        tlAttachment: "Fichier téléversé",
        tlMember: "Membre ajouté",
        tlPlan: "Abonnement",
        tlToday: "Aujourd'hui",
        tlYesterday: "Hier",
        tlDaysAgo: "il y a {n} jours",
        achDoneMonth: "Terminés ce mois",
        achItems: "Éléments",
        achFiles: "Fichiers",
        achImports: "Imports",
        colVNumber: "N° d'infraction",
        colCaseNumber: "N° de dossier",
        caseBundleTitle: "Dossier {n}",
        caseBundleEmpty: "Rien de lié à ce numéro.",
        colVDate: "Date de l'infraction",
        colClient: "Client",
        colIssuer: "Émetteur",
        colAmount: "Montant",
        colVType: "Type d'infraction",
        colObjection: "Statut du recours",
        colPayDue: "Échéance de paiement",
        allClients: "Tous les clients",
        totalCount: "Infractions",
        totalAmount: "Montant total",
        totalUnpaid: "Impayées",
        totalOverdue: "En retard",
        attachTitle: "Pièces jointes",
        attachDrive: "Choisir dans Google Drive",
        attachUpload: "Téléverser un fichier (PDF ou Word)",
        attachLinkPlaceholder: "Ou collez un lien Google Drive",
        attachLinkBtn: "Ajouter le lien",
        attachEmpty: "Aucune pièce jointe.",
        attachUploading: "Téléversement...",
        attachDone: "Ajouté.",
        attachFailed: "Échec du téléversement.",
        attachLimit: "Stockage de votre forfait épuisé.",
        attachDeleteConfirm: "Supprimer définitivement ?",
        attachLinkLabel: "lien externe",
        delete: "Supprimer",
        chartTitle: "Indicateur des infractions",
        indicatorsTitle: "Indicateurs des infractions et audiences",
        courtsTitle: "Affaires {n} (par tribunal)",
        cancelledAmount: "Montant des amendes annulées",
        noCourtData: "Aucune donnée de tribunal.",
        chartTotal: "Total des infractions",
        chartObjected: "Contestées",
        chartCourt: "Portées en justice",
        chartRepeated: "Infractions répétées",
        casesIndicatorsTitle: "Indicateurs des affaires",
        indicatorsFor: "Indicateurs actuels — {name}", indTableOf: "Indicateur {name}", byPartyTitle: "{name} {n}",
        indTotal: "Total", indOpen: "En cours", indOverdue: "En retard", indDone: "Termines",
        indAmountTotal: "Montant total", indAmountDone: "Montant termine",
        indMine: "Mes indicateurs", indMyPapers: "Mes papiers et echeances", indPapers: "Papiers enregistres", indPapersSoon: "Expirent sous 30 jours", indMyAppts: "Mes rendez-vous a venir",
        indPapersExpired: "Expires", indOpenItems: "Elements ouverts", indRegular: "{n} recurrents avec rappel",
        casesChartTitle: "Indicateur des affaires",
        caseTotal: "Total des affaires",
        caseOpen: "Affaires en cours",
        caseOverdue: "En retard",
        caseDone: "Affaires clôturées",
        clientsTitle: "Clients {n} (par client)",
        noClientData: "Aucune donnée client.",
        caseAmount: "Montant total des affaires",
        caseDoneAmount: "Montant des affaires clôturées",
        viewCases: "Tableau des affaires",
        viewExpenses: "Charges d'exploitation",
        viewHealth: "Ma sante",
        viewRulings: "Tableau des jugements",
        viewContracts: "Tableau des contrats", viewDeals: "Tableau des affaires",
        fieldDealStage: "Etape de l'affaire", fieldDealProbability: "Probabilite de conclusion %", fieldDealSource: "Source du prospect",
        dealStageLead: "Prospect", dealStageContact: "Contacte", dealStageProposal: "Devis",
        dealStageNegotiation: "Negociation", dealStageWon: "Gagnee", dealStageLost: "Perdue",
        dealsPipeline: "Valeur du pipeline", dealsWon: "Gagnees ce mois", dealsOpen: "Affaires ouvertes", dealsRate: "Taux de conversion",
        viewInvoices: "Tableau des factures",
        fieldFinNumber: "Numero de facture", fieldFinDir: "Sens de la facture", fieldFinIssued: "Date d'emission",
        fieldFinVat: "TVA", fieldFinAmount: "Montant de la facture", fieldFinPaid: "Encaisse a ce jour",
        fieldFinPaidAt: "Date d'encaissement", fieldFinMethod: "Mode de reglement",
        financeDirIn: "Creance (facture client)", financeDirOut: "Dette (facture fournisseur)",
        financeDirInShort: "Creance", financeDirOutShort: "Dette", financeDirAll: "Tous les sens",
        financeVatExclusive: "15% en sus", financeVatInclusive: "15% inclus", financeVatExempt: "Exonere, sans TVA",
        financeStateAll: "Tous les etats", financeStateDue: "A encaisser", financeStatePartial: "Partiellement encaissee",
        financeStateOverdue: "En retard", financeStateCollected: "Encaissee", financeStateCancelled: "Annulee",
        financePartyAll: "Tous les tiers", finActionCollect: "Encaisser",
        finTotalCount: "Factures", finTotalReceivable: "A encaisser",
        finTotalPayable: "A payer", finTotalOverdue: "En retard",
        finIndicatorsTitle: "Indicateurs financiers", finMonthlyTitle: "Encaissement par mois {y}",
        finTopDebtorsTitle: "Principaux debiteurs", noDebtorData: "Aucun tiers avec un solde du",
        finDueToday: "Du aujourd'hui", finCollectedMonth: "Encaisse ce mois",
        finAvgDays: "Delai moyen d'encaissement",
        colFinNumber: "No de facture", colFinSubject: "Libelle", colFinParty: "Tiers",
        colFinIssued: "Emission", colFinDue: "Echeance", colFinBase: "Hors TVA",
        colFinVat: "TVA", colFinTotal: "Total", colFinPaid: "Encaisse", colFinRemain: "Solde",
        viewStaff: "Tableau des employes", viewLeaves: "Tableau des conges", viewTraining: "Formations et diplomes",
        fieldStaffName: "Nom de l'employe", fieldStaffNameEn: "Nom en anglais", fieldStaffPhone: "Mobile",
        fieldStaffEmail: "Courriel", fieldStaffDept: "Service", fieldStaffJob: "Poste",
        fieldStaffContract: "Type de contrat", fieldStaffStage: "Situation", fieldStaffHired: "Date d'embauche",
        fieldStaffNationality: "Nationalite", fieldStaffId: "Numero d'identite ou d'iqama", fieldStaffIdExpiry: "Expiration de l'identite ou de l'iqama",
        fieldStaffContractEnd: "Fin du contrat", fieldStaffSalary: "Salaire de base", fieldStaffHousing: "Indemnite de logement",
        fieldStaffTransport: "Indemnite de transport", fieldStaffOther: "Autres indemnites", fieldStaffLeaveDays: "Droit a conge annuel (jours)",
        fieldStaffIban: "IBAN",
        staffContractNone: "Non precise", staffContractFixed: "Duree determinee", staffContractOpen: "Duree indeterminee",
        staffContractPart: "Temps partiel", staffContractTemp: "Temporaire ou saisonnier", staffContractRemote: "A distance",
        staffStageCandidate: "Candidat", staffStageProbation: "Periode d'essai", staffStageActive: "En poste",
        staffStageNotice: "Preavis", staffStageEnded: "A quitte l'entreprise",
        staffDeptAll: "Tous les services", staffStageAll: "Toutes les situations",
        staffTotalActive: "Employes en poste", staffTotalPayroll: "Masse salariale mensuelle",
        staffTotalExpiring: "Identites et contrats expires ou expirant sous 60 jours", staffTotalOnLeave: "En conge aujourd'hui",
        staffBasicShort: "base {n}",
        colStaffNumber: "Matricule", colStaffName: "Employe", colStaffDept: "Service", colStaffJob: "Poste",
        colStaffContract: "Contrat", colStaffHired: "Embauche", colStaffSalary: "Salaire total",
        colStaffIdExpiry: "Expiration identite", colStaffContractEnd: "Fin du contrat", colStaffLeft: "Restant",
        colStaffLeaveBalance: "Solde de conges",
        openStaffFile: "Dossier de l'employe", staffFileLeaves: "Conges", staffFileTraining: "Formations et diplomes",
        staffFileBalance: "Solde de conge annuel", staffFileEmpty: "Aucun conge ni formation pour cet employe pour l'instant.",
        fieldLeaveTitle: "Libelle (facultatif)", fieldLeaveEmployee: "Employe", fieldLeaveKind: "Type de conge",
        fieldLeaveApproval: "Approbation", fieldLeaveFrom: "Du", fieldLeaveTo: "Au",
        fieldLeaveDays: "Jours", fieldLeaveReturn: "Date de reprise", fieldLeaveNote: "Motif ou remarque",
        leavePickEmployee: "Choisir l'employe", leaveEmployeeRequired: "Choisissez d'abord l'employe.",
        leaveDatesRequired: "Indiquez la date de debut du conge.",
        leaveKindAnnual: "Annuel", leaveKindSick: "Maladie", leaveKindEmergency: "Urgence", leaveKindUnpaid: "Sans solde",
        leaveKindMaternity: "Maternite", leaveKindPaternity: "Paternite", leaveKindMarriage: "Mariage", leaveKindBereavement: "Deces",
        leaveKindHajj: "Hajj", leaveKindStudy: "Etudes", leaveKindOther: "Autre",
        leaveApprovalPending: "En attente d'approbation", leaveApprovalApproved: "Approuve", leaveApprovalRejected: "Refuse",
        leaveApprovalCancelled: "Annule", leaveStateOngoing: "En cours", leaveStateFinished: "Termine",
        leaveEmpAll: "Tous les employes", leaveKindAll: "Tous les types", leaveStateAll: "Tous les etats",
        leaveTotalPending: "En attente d'approbation", leaveTotalToday: "En conge aujourd'hui",
        leaveTotalSickYear: "Jours de maladie cette annee", leaveTotalAnnualYear: "Jours annuels approuves cette annee",
        colLeaveEmployee: "Employe", colLeaveKind: "Type de conge", colLeaveFrom: "Du", colLeaveTo: "Au",
        colLeaveDays: "Jours", colLeaveLeft: "Debute dans", colLeaveApproval: "Approbation", colLeaveNote: "Libelle",
        actionApprove: "Approuver", actionReject: "Refuser", leaveApproved: "Conge approuve.", leaveRejected: "Conge refuse.",
        fieldTrainName: "Nom de la formation ou du diplome", fieldTrainEmployee: "Employe", fieldTrainKind: "Type de fiche",
        fieldTrainProvider: "Organisme", fieldTrainDate: "Date de formation ou d'obtention", fieldTrainExpiry: "Expiration du certificat",
        fieldTrainHours: "Heures", fieldTrainDegree: "Niveau", fieldTrainMajor: "Specialite",
        fieldTrainResult: "Resultat ou mention",
        trainKindCourse: "Formation", trainKindDegree: "Diplome academique", trainKindCert: "Certificat professionnel",
        trainEmpAll: "Tous les employes", trainKindAll: "Tous les types",
        trainTotalCourses: "Formations", trainTotalDegrees: "Diplomes", trainTotalExpiring: "Certificats expires ou expirant sous 90 jours",
        trainTotalHours: "Heures de formation",
        colTrainEmployee: "Employe", colTrainKind: "Type", colTrainName: "Formation ou diplome", colTrainProvider: "Organisme",
        colTrainDate: "Date", colTrainDegree: "Niveau et specialite", colTrainHours: "Heures",
        colTrainExpiry: "Expiration du certificat", colTrainLeft: "Restant",
        storePickLine: "Où conserver vos fichiers ? Modifiable ensuite dans les paramètres.",
        storePickPlatform: "Serveur Mr.Zahi en Arabie saoudite",
        storePickPlatformHint: "Vos fichiers sont conservés sur notre serveur local à Djeddah, dans le quota du forfait.",
        storePickDrive: "Votre Google Drive",
        storePickDriveHint: "Dans votre Drive, hors quota.",
        storePickDriveDenied: "Permission Google refusée : les fichiers restent sur le serveur Mr.Zahi en Arabie saoudite.",
        colCNumber: "N° du contrat",
        colCSubject: "Objet",
        colCParty: "Contrepartie",
        colCType: "Type",
        colCStart: "Début",
        colCEnd: "Fin",
        colCLeft: "Restant",
        colCValue: "Valeur",
        colCRenewal: "Renouvellement",
        fieldCNumber: "Numéro du contrat",
        fieldCType: "Type de contrat",
        fieldCStart: "Date de début",
        fieldCRenewal: "Renouvellement",
        fieldCNotice: "Préavis avant la fin (jours)",
        renewalAuto: "Automatique",
        renewalManual: "Manuel",
        renewalNone: "Sans renouvellement",
        contractActive: "En cours",
        contractSoon: "Préavis proche",
        contractEnded: "Terminé",
        allParties: "Toutes les contreparties",
        allContractTypes: "Tous les types",
        allContractStates: "Tous les états",
        totalContracts: "Contrats",
        totalContractValue: "Valeur totale",
        totalContractSoon: "Préavis proche",
        totalContractEnded: "Terminés",
        noticeShort: "préavis %s jours",
        colExpDate: "Date",
        colExpCat: "Poste",
        colExpDesc: "Libellé",
        colExpVendor: "Bénéficiaire",
        colExpMethod: "Mode de paiement",
        allCats: "Tous les postes",
        allYears: "Toutes les années",
        expCount: "Dépenses",
        expTotal: "Total dépensé",
        expPaid: "Payé",
        expDue: "Restant dû",
        expOverdue: "En retard",
        expAvgMonth: "Moyenne mensuelle",
        expIndicatorsTitle: "Indicateurs des charges",
        expMonthlyTitle: "Dépenses mensuelles ({y})",
        expByCatTitle: "Par poste ({n})",
        noExpenseData: "Aucun montant enregistré",
        expNoCat: "Sans poste",
        expStatusPaid: "Payé",
        expActionPay: "Marquer payé",
        fieldAmount: "Montant",
        fieldClient: "Partie ou client",
        fieldClientEn: "Partie ou client en anglais",
        appealDeadline: "Délai d'appel",
        appealTitle: "Délai d'appel — {case}",
        appealCategory: "Délai d'appel",
        nextSession: "Prochaine audience",
        nextSessionTitle: "Audience — {case}",
        sessionCategory: "Audience",
        weekTitle: "Cette semaine",
        weekDone: "Terminé cette semaine",
        weekAdded: "Ajouté cette semaine",
        weekLate: "En retard cette semaine",
        weekSame: "Comme la semaine dernière",
        weekVsLast: "vs semaine dernière",
        listUpcoming: "À venir",
        listPast: "Passé",
        actionReschedule: "Replanifier",
        colNumber: "Numéro",
        fieldRemind: "Me rappeler avant",
        remindDefault: "Selon la règle du registre",
        remindDay: "Un jour",
        remind3Days: "Trois jours",
        remindWeek: "Une semaine",
        remind2Weeks: "Deux semaines",
        remindMonth: "Un mois",
        fieldCaseNumber: "Numéro de dossier",
        viewViolations: "Tableau des infractions",
        servicesTitle: "Services",
        calendarCardTitle: "Agenda et audiences",
        startService: "Démarrer le service",
        svcImportTitle: "Importer depuis Excel",
        svcImportText: "Transformez votre agenda ou vos contrats en éléments suivis en une minute.",
        svcAddTitle: "Ajouter un rendez-vous",
        svcAddText: "Enregistrez une audience ou une échéance manuellement.",
        svcTeamTitle: "Inviter un collègue",
        svcTeamText: "Ajoutez vos collègues et attribuez-leur dates et tâches.",
        svcTelegramTitle: "Connecter Telegram",
        svcTelegramText: "Recevez chaque rappel sur Telegram avant l'échéance.",
        svcCalendarTitle: "Connecter l'agenda",
        svcCalendarText: "Reliez vos dates à Google, Apple ou Outlook en un clic.",
        tabCalendar: "Calendrier",
        filterAllRecords: "Tous les suivis",
        filterAllStatuses: "Tous les statuts",
        searchPlaceholder: "Rechercher dans les titres",
        statusOpen: "Ouvert",
        statusDone: "Terminé",
        statusCancelled: "Annulé",
        statusOverdue: "En retard",
        colTitle: "Titre",
        colRecord: "Suivi",
        colDue: "Échéance",
        colAssignee: "Responsable",
        colStatus: "Statut",
        colActions: "Actions",
        noItems: "Aucun élément correspondant.",
        noDue: "Sans échéance",
        noAssignee: "Non attribué",
        actionDone: "Terminer",
        actionReopen: "Rouvrir",
        actionEdit: "Modifier",
        actionDelete: "Supprimer",
        confirmDelete: "Supprimer cet élément ? Cette action est irréversible.",
        editTitle: "Modifier l'élément",
        addItemBtn: "+ Élément",
        addItemTitle: "Nouvel élément",
        fieldTitle: "Titre",
        fieldRecord: "Suivi",
        fieldDue: "Date et heure d'échéance",
        fieldCategory: "Catégorie",
        fieldAssignee: "Responsable",
        fieldStatus: "Statut",
        titlePlaceholder: "Titre de l'élément",
        categoryPlaceholder: "Catégorie (facultatif)",
        chooseRecord: "Choisir un suivi",
        save: "Enregistrer",
        add: "Ajouter",
        titleRequired: "Saisissez le titre de l'élément.",
        recordRequired: "Choisissez d'abord un suivi.",
        newRecordBtn: "+ Nouveau suivi",
        newRecordPlaceholder: "Nom du suivi",
        recordCreated: "Suivi créé.",
        recordNameRequired: "Saisissez le nom du suivi.",
        noRecordsHint: "Aucun suivi pour le moment. Créez d'abord un suivi pour ajouter des éléments.",
        calPrev: "Mois précédent",
        calNext: "Mois suivant",
        calPrevWeek: "Semaine precedente",
        calNextWeek: "Semaine suivante",
        calPrevDay: "Jour precedent",
        calNextDay: "Jour suivant",
        calZoomMonth: "Mois",
        calZoomWeek: "Semaine",
        calZoomDay: "Jour",
        calMoved: "Date deplacee.",
        calAssignHint: "Cliquez un nom pour filtrer, glissez un événement dessus pour réattribuer",
        calWhoAll: "Toute l'équipe",
        calAssigned: "Responsable modifié.",
        calToday: "Aujourd'hui",
        tileOpenWord: "{k} ouverts", tileDue7Word: "{k} sous 7 jours", tileOverdueWord: "{k} en retard", tileDoneWord: "{k} clôturés",
        calFilterAll: "Tout", calFilterCases: "Affaires", calFilterViolations: "Infractions", calFilterTasks: "Taches", calFilterMeetings: "Reunions", calFilterDocuments: "Documents",
        viewMeetings: "Reunions",
        fieldHealthKind: "Type de sante", fieldHealthDose: "Dose ou detail", fieldHealthRepeat: "Repetition", fieldHealthUntil: "Jusqu'au (fin de l'ordonnance)",
        fieldHealthProvider: "Medecin ou etablissement", fieldHealthNote: "Note",
        healthKindMedicine: "Medicament ou traitement", healthKindAppointment: "Rendez-vous medical", healthKindLab: "Analyse ou examen",
        healthKindVaccine: "Vaccin", healthKindFitness: "Salle ou entrainement", healthKindInsurance: "Assurance sante",
        healthRepeatNone: "Sans repetition", healthRepeatDaily: "Chaque jour", healthRepeatWeekly: "Chaque semaine", healthRepeatMonthly: "Chaque mois",
        healthRepeat4h: "Toutes les 4 heures", healthRepeat6h: "Toutes les 6 heures", healthRepeat8h: "Toutes les 8 heures", healthRepeat12h: "Toutes les 12 heures",
        healthKindAll: "Tous les types", healthRecordName: "Ma sante",
        healthStateAll: "Tous les etats", healthStateToday: "Aujourd'hui", healthStateUpcoming: "A venir", healthStateOverdue: "En retard", healthStateDone: "Fait",
        healthTotalToday: "Aujourd'hui", healthTotalOverdue: "En retard", healthTotalRegular: "Recurrents", healthTotalSubs: "Abonnements",
        colHItem: "Element", colHKind: "Type", colHDose: "Dose ou detail", colHRepeat: "Repetition",
        colHWhen: "Echeance", colHLeft: "Restant", colHProvider: "Medecin ou etablissement", colHAmount: "Montant",
        calGregorian: "Grégorien",
        calHijri: "Hégirien",
        daySun: "Dim",
        dayMon: "Lun",
        dayTue: "Mar",
        dayWed: "Mer",
        dayThu: "Jeu",
        dayFri: "Ven",
        daySat: "Sam",
        month1: "Janvier",
        month2: "Février",
        month3: "Mars",
        month4: "Avril",
        month5: "Mai",
        month6: "Juin",
        month7: "Juillet",
        month8: "Août",
        month9: "Septembre",
        month10: "Octobre",
        month11: "Novembre",
        month12: "Décembre",
        moreItems: "{n} autres éléments",
        icsTitle: "Lien du calendrier (ICS)",
        icsHint: "Ajoutez ce lien à Apple Calendar, Google Agenda ou Outlook comme abonnement à un calendrier (par URL) pour que les échéances de vos éléments apparaissent automatiquement et restent à jour.",
        copy: "Copier le lien",
        copied: "Lien copié.",
        regenerate: "Régénérer le lien",
        confirmRegenerate: "Le lien actuel cessera de fonctionner et vous devrez ajouter le nouveau lien à votre calendrier. Continuer ?",
        regenerated: "Un nouveau lien a été généré.",
        icsSecret: "Ce lien est personnel. Ne le partagez pas.",
        itemDone: "Élément marqué comme terminé.",
        itemReopened: "Élément rouvert.",
        itemAdded: "Élément ajouté.",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        loginLink: "Connexion",
        dashboardLink: "Tableau de bord",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        exportXlsx: "ایکسل ایکسپورٹ",
        exportBtn: "ایکسپورٹ",
        caseFileTitle: "مقدمے کی فائل",
        caseFileEmpty: "اس مقدمے کے تحت ابھی کچھ نہیں۔",
        secSessions: "سماعتیں",
        secRulings: "فیصلے",
        secExecutions: "نفاذ کی درخواستیں",
        secViolations: "خلاف ورزیاں",
        secTasks: "کام",
        secDocuments: "دستاویزات",
        fieldCourt: "عدالت",
        fieldStage: "مرحلہ",
        openCaseFile: "مقدمے کی فائل",
        appName: "MrZahi",
        exportCsv: "CSV برآمد",
        title: "ڈیش بورڈ",
        loading: "لوڈ ہو رہا ہے...",
        serviceUnavailableTitle: "سروس تک رسائی نہیں ہو سکی",
        serviceUnavailableText: "سروس سے رابطہ منقطع ہو گیا۔ اپنا رابطہ چیک کر کے دوبارہ کوشش کریں۔",
        noOrg: "کوئی کمپنی منتخب نہیں، پہلے اپنی کمپنی بنائیں۔",
        planLimitItems: "آپ اپنے موجودہ پلان میں آئٹمز کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        planLimitMembers: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        planLimitLink: "پلانز اور قیمتیں دیکھیں",
        genericError: "کچھ غلط ہو گیا، براہ کرم دوبارہ کوشش کریں۔",
        errorLoad: "ڈیٹا لوڈ نہیں ہو سکا، براہ کرم دوبارہ کوشش کریں۔",
        saved: "محفوظ ہو گیا۔",
        deleted: "حذف ہو گیا۔",
        companyLabel: "کمپنی:",
        switchOrg: "کمپنی تبدیل کریں",
        newOrgBtn: "+ اکاؤنٹ شامل کریں",
        renameOrgBtn: "نام بدلیں",
        deleteOrgBtn: "کمپنی حذف کریں",
        orgRenamed: "کمپنی کا نام تبدیل ہو گیا۔",
        deleteOrgConfirm: "«{name}» اور اس کے تمام آئٹمز مستقل طور پر حذف ہو جائیں گے۔ جاری رکھیں؟",
        newOrgPlaceholder: "ادارے کا نام",
        selfNamePlaceholder: "آپ کا پورا نام",
        newOrgSubmit: "بنائیں",
        cancel: "منسوخ کریں",
        createOrgTitle: "اپنا اکاؤنٹ شروع کریں",
        createOrgIntro: "اکاؤنٹ کی قسم منتخب کریں: کمپنی، ادارہ، فری لانس اجازت، یا ذاتی کاغذات ترتیب دینے والا فرد۔",
        packPickLine: "اپنے کام کے مطابق انٹرفیس منتخب کریں۔",
        packChoose: "منتخب کریں",
        orgCreated: "اکاؤنٹ کامیابی سے بن گیا۔",
        orgNameRequired: "نام درج کریں۔",
        joinTitle: "یا موجودہ اکاؤنٹ میں شامل ہوں",
        joinIntro: "اگر آپ یہاں رجسٹرڈ کسی کمپنی میں کام کرتے ہیں تو اس کا اکاؤنٹ نمبر لکھیں، مالک کو آپ کی درخواست پہنچ جائے گی۔",
        joinCodePlaceholder: "اکاؤنٹ نمبر",
        joinSubmit: "درخواست بھیجیں",
        joinSent: "درخواست بھیج دی گئی؛ مالک کے قبول کرتے ہی آپ شامل ہو جائیں گے۔",
        joinPending: "{org} کو آپ کی درخواست منظوری کی منتظر ہے۔",
        joinNotFound: "اس نمبر کا کوئی اکاؤنٹ نہیں۔",
        joinAlready: "آپ پہلے ہی اس اکاؤنٹ کے رکن ہیں۔",
        joinCodeRequired: "اکاؤنٹ نمبر لکھیں۔",
        linkImport: "فائل امپورٹ کریں",
        linkTeam: "ٹیم",
        linkSettings: "ترتیبات",
        linkAdmin: "پلیٹ فارم انتظامیہ",
        signOut: "سائن آؤٹ",
        statOpen: "کھلے آئٹمز",
        statDue7: "7 دنوں میں واجب",
        statOverdue: "تاخیر شدہ",
        statDone: "مکمل",
        tabList: "فہرست",
        timelineTitle: "آپ کی کارکردگی",
        tlNow: "اب",
        tlDayEvents: "{d} کو {n} واقعات",
        tlMonths: "مہینے دیکھیں",
        tlPrev: "پچھلا سنگ میل",
        tlNext: "اگلا سنگ میل",
        tlEventOf: "واقعہ {i} از {n}",
        timelineEmpty: "ابھی کوئی سرگرمی نہیں — فائل درآمد کریں یا وقت شامل کریں۔",
        tlCreated: "آئٹم شامل",
        tlDone: "مکمل",
        tlImport: "فائل درآمد",
        tlAttachment: "فائل اپ لوڈ",
        tlMember: "رکن شامل",
        tlPlan: "سبسکرپشن",
        tlToday: "آج",
        tlYesterday: "کل",
        tlDaysAgo: "{n} دن پہلے",
        achDoneMonth: "اس مہینے مکمل",
        achItems: "کل آئٹمز",
        achFiles: "فائلیں",
        achImports: "درآمدات",
        colVNumber: "خلاف ورزی نمبر",
        colCaseNumber: "مقدمہ نمبر",
        caseBundleTitle: "مقدمہ فائل {n}",
        caseBundleEmpty: "اس نمبر سے کچھ منسلک نہیں۔",
        colVDate: "خلاف ورزی کی تاریخ",
        colClient: "کمپنی",
        colIssuer: "جاری کنندہ",
        colAmount: "رقم",
        colVType: "قسم",
        colObjection: "اعتراض کی حالت",
        colPayDue: "ادائیگی کی تاریخ",
        allClients: "تمام کمپنیاں",
        totalCount: "خلاف ورزیاں",
        totalAmount: "کل رقم",
        totalUnpaid: "غیر ادا شدہ",
        totalOverdue: "مدت گزر گئی",
        attachTitle: "منسلکات",
        attachDrive: "گوگل ڈرائیو سے چنیں",
        attachUpload: "فائل اپ لوڈ کریں (PDF یا Word)",
        attachLinkPlaceholder: "یا گوگل ڈرائیو لنک چسپاں کریں",
        attachLinkBtn: "لنک شامل کریں",
        attachEmpty: "اس آئٹم کے لیے کوئی منسلک نہیں۔",
        attachUploading: "اپ لوڈ ہو رہا ہے...",
        attachDone: "شامل ہو گیا۔",
        attachFailed: "فائل اپ لوڈ نہیں ہو سکی۔",
        attachLimit: "آپ کے پیکج کی اسٹوریج ختم ہو گئی۔",
        attachDeleteConfirm: "منسلک مستقل حذف کریں؟",
        attachLinkLabel: "بیرونی لنک",
        delete: "حذف",
        chartTitle: "خلاف ورزیوں کا اشاریہ",
        indicatorsTitle: "خلاف ورزیوں اور سماعتوں کے اشاریے",
        courtsTitle: "مقدمات {n} (عدالت کے مطابق)",
        cancelledAmount: "منسوخ جرمانوں کی رقم",
        noCourtData: "عدالت کا ڈیٹا موجود نہیں۔",
        chartTotal: "کل خلاف ورزیاں",
        chartObjected: "اعتراض شدہ",
        chartCourt: "عدالت میں",
        chartRepeated: "بار بار کی خلاف ورزیاں",
        casesIndicatorsTitle: "مقدمات کے موجودہ اشاریے",
        indicatorsFor: "موجودہ اشاریے — {name}", indTableOf: "{name} اشاریہ", byPartyTitle: "{name} {n}",
        indTotal: "کل", indOpen: "جاری", indOverdue: "تاخیر", indDone: "مکمل",
        indAmountTotal: "کل رقم", indAmountDone: "مکمل کی رقم",
        indMine: "میرے اشاریے", indMyPapers: "میرے کاغذات اور تاریخیں", indPapers: "درج کاغذات", indPapersSoon: "30 دن میں ختم", indMyAppts: "میری آنے والی ملاقاتیں",
        indPapersExpired: "ختم شدہ", indOpenItems: "کھلے آئٹمز", indRegular: "{n} باقاعدہ یاد دہانی کے ساتھ",
        casesChartTitle: "مقدمات کا اشاریہ",
        caseTotal: "کل مقدمات",
        caseOpen: "جاری مقدمات",
        caseOverdue: "تاخیر شدہ",
        caseDone: "مکمل مقدمات",
        clientsTitle: "کلائنٹس {n} (کلائنٹ کے مطابق)",
        noClientData: "کلائنٹ کا ڈیٹا موجود نہیں۔",
        caseAmount: "مقدمات کی کل رقم",
        caseDoneAmount: "مکمل مقدمات کی رقم",
        viewCases: "مقدمات ڈیش بورڈ",
        viewExpenses: "آپریٹنگ اخراجات",
        viewHealth: "میری صحت",
        viewRulings: "فیصلے ڈیش بورڈ",
        viewContracts: "معاہدے ڈیش بورڈ", viewDeals: "سودے ڈیش بورڈ",
        fieldDealStage: "سودے کا مرحلہ", fieldDealProbability: "بند ہونے کا امکان %", fieldDealSource: "گاہک کا ذریعہ",
        dealStageLead: "ممکنہ گاہک", dealStageContact: "رابطہ", dealStageProposal: "قیمت کی پیشکش",
        dealStageNegotiation: "بات چیت", dealStageWon: "جیتا", dealStageLost: "ہارا",
        dealsPipeline: "پائپ لائن کی قیمت", dealsWon: "اس ماہ جیتے", dealsOpen: "کھلے سودے", dealsRate: "تبدیلی کی شرح",
        viewInvoices: "رسیدیں ڈیش بورڈ",
        fieldFinNumber: "رسید نمبر", fieldFinDir: "رسید کی سمت", fieldFinIssued: "اجرا کی تاریخ",
        fieldFinVat: "ٹیکس", fieldFinAmount: "رسید کی رقم", fieldFinPaid: "اب تک وصول",
        fieldFinPaidAt: "وصولی کی تاریخ", fieldFinMethod: "ادائیگی کا طریقہ",
        financeDirIn: "واجب الوصول (گاہک کی رسید)", financeDirOut: "واجب ادائیگی (سپلائر کی رسید)",
        financeDirInShort: "واجب الوصول", financeDirOutShort: "واجب ادائیگی", financeDirAll: "تمام سمتیں",
        financeVatExclusive: "15% اضافی", financeVatInclusive: "15% شامل", financeVatExempt: "مستثنی، بغیر ٹیکس",
        financeStateAll: "تمام حالتیں", financeStateDue: "واجب", financeStatePartial: "جزوی وصول",
        financeStateOverdue: "تاخیر شدہ", financeStateCollected: "وصول شدہ", financeStateCancelled: "منسوخ",
        financePartyAll: "تمام ادارے", finActionCollect: "وصولی",
        finTotalCount: "رسیدیں", finTotalReceivable: "ہمارے واجبات",
        finTotalPayable: "ہم پر واجب", finTotalOverdue: "تاخیر شدہ",
        finIndicatorsTitle: "مالیاتی اشارے", finMonthlyTitle: "ماہ بہ ماہ وصولی {y}",
        finTopDebtorsTitle: "بڑے مقروض", noDebtorData: "کسی ادارے پر بقایا نہیں",
        finDueToday: "آج واجب", finCollectedMonth: "اس ماہ وصول",
        finAvgDays: "وصولی کے اوسط دن",
        colFinNumber: "رسید نمبر", colFinSubject: "تفصیل", colFinParty: "ادارہ",
        colFinIssued: "اجرا", colFinDue: "آخری تاریخ", colFinBase: "ٹیکس سے پہلے",
        colFinVat: "ٹیکس", colFinTotal: "کل", colFinPaid: "وصول", colFinRemain: "بقایا",
        viewStaff: "ملازمین ڈیش بورڈ", viewLeaves: "چھٹیاں ڈیش بورڈ", viewTraining: "کورسز اور قابلیت",
        fieldStaffName: "ملازم کا نام", fieldStaffNameEn: "انگریزی میں نام", fieldStaffPhone: "موبائل",
        fieldStaffEmail: "ای میل", fieldStaffDept: "شعبہ", fieldStaffJob: "عہدہ",
        fieldStaffContract: "معاہدے کی قسم", fieldStaffStage: "ملازمت کی حالت", fieldStaffHired: "تقرری کی تاریخ",
        fieldStaffNationality: "قومیت", fieldStaffId: "شناختی یا اقامہ نمبر", fieldStaffIdExpiry: "شناخت یا اقامہ کی میعاد",
        fieldStaffContractEnd: "معاہدے کا اختتام", fieldStaffSalary: "بنیادی تنخواہ", fieldStaffHousing: "رہائشی الاؤنس",
        fieldStaffTransport: "ٹرانسپورٹ الاؤنس", fieldStaffOther: "دیگر الاؤنس", fieldStaffLeaveDays: "سالانہ چھٹی کا حق (دن)",
        fieldStaffIban: "آئی بان",
        staffContractNone: "غیر متعین", staffContractFixed: "مقررہ مدت", staffContractOpen: "غیر مقررہ مدت",
        staffContractPart: "جز وقتی", staffContractTemp: "عارضی یا موسمی", staffContractRemote: "دور سے",
        staffStageCandidate: "امیدوار", staffStageProbation: "زیر آزمائش", staffStageActive: "برسر ملازمت",
        staffStageNotice: "نوٹس کی مدت", staffStageEnded: "ملازمت ختم",
        staffDeptAll: "تمام شعبے", staffStageAll: "تمام حالتیں",
        staffTotalActive: "برسر ملازمت", staffTotalPayroll: "ماہانہ تنخواہیں",
        staffTotalExpiring: "اقامے اور معاہدے جو ختم ہو گئے یا 60 دن میں ختم ہوں گے", staffTotalOnLeave: "آج چھٹی پر",
        staffBasicShort: "بنیادی {n}",
        colStaffNumber: "ملازم نمبر", colStaffName: "ملازم", colStaffDept: "شعبہ", colStaffJob: "عہدہ",
        colStaffContract: "معاہدہ", colStaffHired: "تقرری", colStaffSalary: "کل تنخواہ",
        colStaffIdExpiry: "اقامہ کی میعاد", colStaffContractEnd: "معاہدے کا اختتام", colStaffLeft: "باقی",
        colStaffLeaveBalance: "چھٹی کا بقایا",
        openStaffFile: "ملازم کی فائل", staffFileLeaves: "چھٹیاں", staffFileTraining: "کورسز اور قابلیت",
        staffFileBalance: "سالانہ چھٹی کا بقایا", staffFileEmpty: "اس ملازم کی ابھی کوئی چھٹی یا کورس درج نہیں۔",
        fieldLeaveTitle: "تفصیل (اختیاری)", fieldLeaveEmployee: "ملازم", fieldLeaveKind: "چھٹی کی قسم",
        fieldLeaveApproval: "منظوری", fieldLeaveFrom: "تاریخ سے", fieldLeaveTo: "تاریخ تک",
        fieldLeaveDays: "دنوں کی تعداد", fieldLeaveReturn: "واپسی کی تاریخ", fieldLeaveNote: "وجہ یا نوٹ",
        leavePickEmployee: "ملازم منتخب کریں", leaveEmployeeRequired: "پہلے ملازم منتخب کریں۔",
        leaveDatesRequired: "چھٹی کے آغاز کی تاریخ لکھیں۔",
        leaveKindAnnual: "سالانہ", leaveKindSick: "بیماری", leaveKindEmergency: "ہنگامی", leaveKindUnpaid: "بلا تنخواہ",
        leaveKindMaternity: "زچگی", leaveKindPaternity: "پدری", leaveKindMarriage: "شادی", leaveKindBereavement: "وفات",
        leaveKindHajj: "حج", leaveKindStudy: "تعلیمی", leaveKindOther: "دیگر",
        leaveApprovalPending: "منظوری کا انتظار", leaveApprovalApproved: "منظور شدہ", leaveApprovalRejected: "مسترد",
        leaveApprovalCancelled: "منسوخ", leaveStateOngoing: "جاری", leaveStateFinished: "ختم",
        leaveEmpAll: "تمام ملازمین", leaveKindAll: "تمام اقسام", leaveStateAll: "تمام حالتیں",
        leaveTotalPending: "منظوری کا انتظار", leaveTotalToday: "آج چھٹی پر",
        leaveTotalSickYear: "اس سال بیماری کے دن", leaveTotalAnnualYear: "اس سال منظور شدہ سالانہ دن",
        colLeaveEmployee: "ملازم", colLeaveKind: "چھٹی کی قسم", colLeaveFrom: "سے", colLeaveTo: "تک",
        colLeaveDays: "دن", colLeaveLeft: "شروع ہونے میں", colLeaveApproval: "منظوری", colLeaveNote: "تفصیل",
        actionApprove: "منظور", actionReject: "مسترد", leaveApproved: "چھٹی منظور ہو گئی۔", leaveRejected: "چھٹی مسترد ہو گئی۔",
        fieldTrainName: "کورس یا قابلیت کا نام", fieldTrainEmployee: "ملازم", fieldTrainKind: "ریکارڈ کی قسم",
        fieldTrainProvider: "جاری کرنے والا ادارہ", fieldTrainDate: "کورس یا فراغت کی تاریخ", fieldTrainExpiry: "سند کی میعاد",
        fieldTrainHours: "گھنٹے", fieldTrainDegree: "ڈگری", fieldTrainMajor: "مضمون",
        fieldTrainResult: "نتیجہ یا گریڈ",
        trainKindCourse: "تربیتی کورس", trainKindDegree: "تعلیمی قابلیت", trainKindCert: "پیشہ ورانہ سند",
        trainEmpAll: "تمام ملازمین", trainKindAll: "تمام اقسام",
        trainTotalCourses: "کورسز", trainTotalDegrees: "قابلیتیں", trainTotalExpiring: "اسناد جو ختم ہو گئیں یا 90 دن میں ختم ہوں گی",
        trainTotalHours: "تربیت کے گھنٹے",
        colTrainEmployee: "ملازم", colTrainKind: "قسم", colTrainName: "کورس یا قابلیت", colTrainProvider: "ادارہ",
        colTrainDate: "تاریخ", colTrainDegree: "ڈگری اور مضمون", colTrainHours: "گھنٹے",
        colTrainExpiry: "سند کی میعاد", colTrainLeft: "باقی",
        storePickLine: "آپ کی فائلیں کہاں محفوظ ہوں؟ بعد میں ترتیبات سے بدل سکتے ہیں۔",
        storePickPlatform: "سعودی عرب میں Mr.Zahi سرور",
        storePickPlatformHint: "آپ کی فائلیں جدہ میں ہمارے مقامی سرور پر، آپ کے پلان کی حد کے اندر محفوظ ہوتی ہیں۔",
        storePickDrive: "آپ کا اپنا Google Drive",
        storePickDriveHint: "آپ کے Drive میں، کوٹے سے باہر۔",
        storePickDriveDenied: "گوگل کی اجازت نہیں ملی، فائلیں سعودی عرب میں Mr.Zahi سرور پر رہیں گی۔",
        colCNumber: "معاہدہ نمبر",
        colCSubject: "موضوع",
        colCParty: "فریق ثانی",
        colCType: "قسم",
        colCStart: "آغاز",
        colCEnd: "اختتام",
        colCLeft: "باقی",
        colCValue: "مالیت",
        colCRenewal: "تجدید",
        fieldCNumber: "معاہدہ نمبر",
        fieldCType: "معاہدے کی قسم",
        fieldCStart: "تاریخ آغاز",
        fieldCRenewal: "تجدید",
        fieldCNotice: "اختتام سے پہلے اطلاع کی مدت (دن)",
        renewalAuto: "خودکار",
        renewalManual: "دستی",
        renewalNone: "تجدید نہیں",
        contractActive: "جاری",
        contractSoon: "اطلاع کا وقت",
        contractEnded: "ختم",
        allParties: "تمام فریق",
        allContractTypes: "تمام اقسام",
        allContractStates: "تمام حالتیں",
        totalContracts: "معاہدے",
        totalContractValue: "کل مالیت",
        totalContractSoon: "اطلاع کا وقت",
        totalContractEnded: "ختم شدہ",
        noticeShort: "اطلاع %s دن",
        colExpDate: "تاریخ",
        colExpCat: "مد",
        colExpDesc: "تفصیل",
        colExpVendor: "وصول کنندہ",
        colExpMethod: "ادائیگی کا طریقہ",
        allCats: "تمام مدات",
        allYears: "تمام سال",
        expCount: "اخراجات",
        expTotal: "کل خرچ",
        expPaid: "ادا شدہ",
        expDue: "واجب الادا",
        expOverdue: "تاخیر شدہ",
        expAvgMonth: "ماہانہ اوسط",
        expIndicatorsTitle: "اخراجات کے اشاریے",
        expMonthlyTitle: "ماہانہ خرچ ({y})",
        expByCatTitle: "مد کے حساب سے ({n})",
        noExpenseData: "ابھی کوئی رقم درج نہیں",
        expNoCat: "بغیر مد",
        expStatusPaid: "ادا شدہ",
        expActionPay: "ادا شدہ نشان زد کریں",
        fieldAmount: "رقم",
        fieldClient: "فریق یا کلائنٹ",
        fieldClientEn: "فریق یا کلائنٹ انگریزی میں",
        appealDeadline: "اپیل کی مہلت",
        appealTitle: "اپیل کی مہلت — {case}",
        appealCategory: "اپیل کی مہلت",
        nextSession: "اگلی سماعت",
        nextSessionTitle: "سماعت — {case}",
        sessionCategory: "سماعت",
        weekTitle: "اس ہفتے کا خلاصہ",
        weekDone: "اس ہفتے مکمل",
        weekAdded: "اس ہفتے شامل",
        weekLate: "اس ہفتے تاخیر",
        weekSame: "پچھلے ہفتے جیسا",
        weekVsLast: "پچھلے ہفتے کے مقابلے",
        listUpcoming: "آنے والے",
        listPast: "گزشتہ",
        actionReschedule: "دوبارہ شیڈول",
        colNumber: "نمبر",
        fieldRemind: "پہلے یاد دلائیں",
        remindDefault: "رجسٹر کے قاعدے کے مطابق",
        remindDay: "ایک دن",
        remind3Days: "تین دن",
        remindWeek: "ایک ہفتہ",
        remind2Weeks: "دو ہفتے",
        remindMonth: "ایک مہینہ",
        fieldCaseNumber: "فائل نمبر",
        viewViolations: "خلاف ورزیاں ڈیش بورڈ",
        servicesTitle: "خدمات",
        calendarCardTitle: "کیلنڈر اور سماعتیں",
        startService: "خدمت شروع کریں",
        svcImportTitle: "ایکسل سے درآمد",
        svcImportText: "اپنے شیڈول یا معاہدوں کو منٹ میں ٹریک شدہ آئٹمز میں بدلیں۔",
        svcAddTitle: "نیا وقت شامل کریں",
        svcAddText: "سماعت یا مقررہ تاریخ خود درج کریں۔",
        svcTeamTitle: "ساتھی کو مدعو کریں",
        svcTeamText: "ساتھیوں کو شامل کریں اور تاریخیں و کام تفویض کریں۔",
        svcTelegramTitle: "ٹیلیگرام جوڑیں",
        svcTelegramText: "ہر یاد دہانی وقت سے پہلے ٹیلیگرام پر پائیں۔",
        svcCalendarTitle: "کیلنڈر جوڑیں",
        svcCalendarText: "اپنی تاریخیں ایک کلک میں گوگل، ایپل یا آؤٹ لک سے جوڑیں۔",
        tabCalendar: "کیلنڈر",
        filterAllRecords: "تمام رجسٹرز",
        filterAllStatuses: "تمام حالتیں",
        searchPlaceholder: "عنوانات میں تلاش کریں",
        statusOpen: "کھلا",
        statusDone: "مکمل",
        statusCancelled: "منسوخ",
        statusOverdue: "تاخیر شدہ",
        colTitle: "عنوان",
        colRecord: "رجسٹر",
        colDue: "آخری تاریخ",
        colAssignee: "ذمہ دار",
        colStatus: "حالت",
        colActions: "کارروائیاں",
        noItems: "کوئی مطابقت رکھنے والا آئٹم نہیں۔",
        noDue: "بغیر تاریخ",
        noAssignee: "غیر متعین",
        actionDone: "مکمل کریں",
        actionReopen: "دوبارہ کھولیں",
        actionEdit: "ترمیم",
        actionDelete: "حذف کریں",
        confirmDelete: "کیا آپ یہ آئٹم حذف کرنا چاہتے ہیں؟ اسے واپس نہیں کیا جا سکتا۔",
        editTitle: "آئٹم میں ترمیم",
        addItemBtn: "+ آئٹم",
        addItemTitle: "نیا آئٹم",
        fieldTitle: "عنوان",
        fieldRecord: "رجسٹر",
        fieldDue: "آخری تاریخ اور وقت",
        fieldCategory: "زمرہ",
        fieldAssignee: "ذمہ دار",
        fieldStatus: "حالت",
        titlePlaceholder: "آئٹم کا عنوان",
        categoryPlaceholder: "زمرہ (اختیاری)",
        chooseRecord: "رجسٹر منتخب کریں",
        save: "محفوظ کریں",
        add: "شامل کریں",
        titleRequired: "آئٹم کا عنوان درج کریں۔",
        recordRequired: "پہلے رجسٹر منتخب کریں۔",
        newRecordBtn: "+ نیا رجسٹر",
        newRecordPlaceholder: "رجسٹر کا نام",
        recordCreated: "رجسٹر بن گیا۔",
        recordNameRequired: "رجسٹر کا نام درج کریں۔",
        noRecordsHint: "ابھی کوئی رجسٹر نہیں، آئٹمز شامل کرنے کے لیے پہلے رجسٹر بنائیں۔",
        calPrev: "پچھلا مہینہ",
        calNext: "اگلا مہینہ",
        calPrevWeek: "پچھلا ہفتہ",
        calNextWeek: "اگلا ہفتہ",
        calPrevDay: "پچھلا دن",
        calNextDay: "اگلا دن",
        calZoomMonth: "مہینہ",
        calZoomWeek: "ہفتہ",
        calZoomDay: "دن",
        calMoved: "تاریخ منتقل ہو گئی۔",
        calAssignHint: "نام پر کلک کر کے فلٹر کریں، معاملہ اس پر گھسیٹ کر ذمہ داری منتقل کریں",
        calWhoAll: "پوری ٹیم",
        calAssigned: "ذمہ دار تبدیل ہو گیا۔",
        calToday: "آج",
        tileOpenWord: "کھلے {k}", tileDue7Word: "{k} سات دن میں", tileOverdueWord: "تاخیر شدہ {k}", tileDoneWord: "بند {k}",
        calFilterAll: "سب", calFilterCases: "مقدمات", calFilterViolations: "خلاف ورزیاں", calFilterTasks: "کام", calFilterMeetings: "میٹنگز", calFilterDocuments: "دستاویزات",
        viewMeetings: "میٹنگز",
        fieldHealthKind: "صحت آئٹم کی قسم", fieldHealthDose: "خوراک یا تفصیل", fieldHealthRepeat: "تکرار", fieldHealthUntil: "تاریخ تک (نسخے کا اختتام)",
        fieldHealthProvider: "ڈاکٹر یا ادارہ", fieldHealthNote: "نوٹ",
        healthKindMedicine: "دوا یا علاج", healthKindAppointment: "ڈاکٹر کا وقت", healthKindLab: "ٹیسٹ یا لیب",
        healthKindVaccine: "ویکسین", healthKindFitness: "جم یا ورزش", healthKindInsurance: "ہیلتھ انشورنس",
        healthRepeatNone: "بغیر تکرار", healthRepeatDaily: "روزانہ", healthRepeatWeekly: "ہفتہ وار", healthRepeatMonthly: "ماہانہ",
        healthRepeat4h: "ہر 4 گھنٹے", healthRepeat6h: "ہر 6 گھنٹے", healthRepeat8h: "ہر 8 گھنٹے", healthRepeat12h: "ہر 12 گھنٹے",
        healthKindAll: "تمام اقسام", healthRecordName: "میری صحت",
        healthStateAll: "تمام حالتیں", healthStateToday: "آج", healthStateUpcoming: "آنے والا", healthStateOverdue: "تاخیر", healthStateDone: "مکمل",
        healthTotalToday: "آج", healthTotalOverdue: "تاخیر", healthTotalRegular: "باقاعدہ", healthTotalSubs: "سبسکرپشنز",
        colHItem: "آئٹم", colHKind: "قسم", colHDose: "خوراک یا تفصیل", colHRepeat: "تکرار",
        colHWhen: "وقت", colHLeft: "باقی", colHProvider: "ڈاکٹر یا ادارہ", colHAmount: "رقم",
        calGregorian: "عیسوی",
        calHijri: "ہجری",
        daySun: "اتوار",
        dayMon: "پیر",
        dayTue: "منگل",
        dayWed: "بدھ",
        dayThu: "جمعرات",
        dayFri: "جمعہ",
        daySat: "ہفتہ",
        month1: "جنوری",
        month2: "فروری",
        month3: "مارچ",
        month4: "اپریل",
        month5: "مئی",
        month6: "جون",
        month7: "جولائی",
        month8: "اگست",
        month9: "ستمبر",
        month10: "اکتوبر",
        month11: "نومبر",
        month12: "دسمبر",
        moreItems: "{n} مزید آئٹمز",
        icsTitle: "کیلنڈر لنک (ICS)",
        icsHint: "اس لنک کو Apple، Google یا Outlook کیلنڈر میں سبسکرپشن (URL کے ذریعے) کے طور پر شامل کریں تاکہ آپ کے آئٹمز کی تاریخیں خود بخود ظاہر ہوں اور اپ ڈیٹ رہیں۔",
        copy: "لنک کاپی کریں",
        copied: "لنک کاپی ہو گیا۔",
        regenerate: "نیا لنک بنائیں",
        confirmRegenerate: "موجودہ لنک کام کرنا بند کر دے گا اور آپ کو نیا لنک اپنے کیلنڈر میں شامل کرنا ہوگا۔ جاری رکھیں؟",
        regenerated: "نیا لنک بن گیا۔",
        icsSecret: "یہ لنک ذاتی ہے، اسے دوسروں کے ساتھ شیئر نہ کریں۔",
        itemDone: "آئٹم مکمل کر دیا گیا۔",
        itemReopened: "آئٹم دوبارہ کھول دیا گیا۔",
        itemAdded: "آئٹم شامل کر دیا گیا۔",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        loginLink: "سائن ان",
        dashboardLink: "ڈیش بورڈ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };

