/* migration: نقل مفاتيح التخزين من الاسم القديم الى mrzahi_ مرة واحدة لكل متصفح، فلا يفقد احد لغته ولا ثيمه ولا حسابه المختار */
try{["lang","theme","org","sidebar","dash_tab","bell_seen","chat_seen","cal_mode","cal_zoom","dp_cal","drive_folder","tr"].forEach(function(k){var o=localStorage.getItem("record_"+k);if(o!==null&&localStorage.getItem("mrzahi_"+k)===null){localStorage.setItem("mrzahi_"+k,o);localStorage.removeItem("record_"+k);}});}catch(e){}
    const t = {
      ar: {
        title: "حذف الحساب",
        intro: "يمكنك طلب حذف حسابك في MrZahi في أي وقت، إما من داخل المنصة مباشرة، أو عبر إرسال طلب بالبريد الإلكتروني. نوضح أدناه الخطوات وما يحدث لبياناتك بعد الحذف.",
        h1: "1. الحذف من داخل المنصة",
        s1li1: "افتح mrzahi.com وسجل الدخول إلى حسابك",
        s1li2: "انتقل إلى الإعدادات",
        s1li3: "اختر «حذف الحساب» أسفل الملف الشخصي",
        s1li4: "أكد الطلب لإتمام عملية الحذف",
        h2: "2. الحذف عبر البريد الإلكتروني",
        s2p1: "إذا تعذر عليك الوصول إلى حسابك، أرسل طلب الحذف من البريد الإلكتروني المسجل في حسابك إلى:",
        s2p2: "يرجى تضمين الاسم الكامل ورقم الجوال المسجلين في حسابك لتسريع عملية التحقق. سنرد على طلبك خلال أيام عمل قليلة.",
        h3: "3. ما يحذف",
        s3li1: "بياناتك الشخصية: الاسم، البريد الإلكتروني، رقم الجوال، وإعدادات حسابك",
        s3li2: "قنوات التنبيه المرتبطة بحسابك (تيليغرام وغيرها) وإشعاراتك",
        s3li3: "عضويتك في أي شركة تعمل فيها كعضو (تبقى بيانات الشركة نفسها كما هي لبقية أعضائها)",
        s3li4: "إن كنت المالك الوحيد لشركة لا يوجد فيها عضو نشط آخر: تحذف الشركة وكل عناصرها وسجلاتها معك",
        s3p2: "إن كنت مالك شركة فيها أعضاء نشطون آخرون، فلا يمكن إتمام حذف حسابك قبل نقل ملكية الشركة إلى عضو آخر أو إزالة أعضائها، لأن بياناتهم ليست ملكك وحدك.",
        h4: "4. ما يحتفظ به",
        s4p1: "قد نحتفظ بسجلات محدودة تخص الفوترة أو الوفاء بالتزام نظامي، وذلك فقط للمدة التي يقتضيها النظام.",
        h5: "5. فترة السماح: 30 يوما",
        s5p1: "بعد تأكيد طلب الحذف من داخل المنصة، يدخل حسابك في فترة سماح مدتها 30 يوما يمكنك خلالها استرجاعه بالكامل بمجرد تسجيل الدخول مرة أخرى. بعد انتهاء هذه المدة تحذف بياناتك نهائيا ولا يمكن استرجاعها.",
        h6: "6. الاستفسارات",
        s6p1: "لأي استفسار يخص حذف الحساب أو معالجة بياناتك، تواصل معنا عبر:",
        s6li1: "البريد الإلكتروني:",
        seePrivacy: "اطلع أيضا على سياسة الخصوصية",
        backBtn: "العودة للرئيسية",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        deleteAccountLink: "حذف الحساب",
        loginLink: "تسجيل الدخول",
        accountLabel: "الحساب",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        title: "Delete account",
        intro: "You can request to delete your MrZahi account at any time, either directly from within the platform or by sending an email request. The steps below explain what happens to your data after deletion.",
        h1: "1. Deleting from within the platform",
        s1li1: "Open mrzahi.com and sign in to your account",
        s1li2: "Go to Settings",
        s1li3: "Choose \"Delete account\" below your profile",
        s1li4: "Confirm the request to complete the deletion",
        h2: "2. Deleting by email",
        s2p1: "If you cannot access your account, send a deletion request from the email address registered on your account to:",
        s2p2: "Please include the full name and phone number registered on your account to speed up verification. We will respond within a few business days.",
        h3: "3. What is deleted",
        s3li1: "Your personal data: name, email, phone number, and account settings",
        s3li2: "Notification channels linked to your account (Telegram and others) and your notifications",
        s3li3: "Your membership in any company where you are a member (the company's own data remains for its other members)",
        s3li4: "If you are the sole owner of a company with no other active member: the company and all of its items and records are deleted with you",
        s3p2: "If you own a company that still has other active members, your account deletion cannot be completed before you transfer ownership to another member or remove those members, because their data is not yours alone.",
        h4: "4. What is retained",
        s4p1: "We may retain limited records for billing or to meet a legal obligation, only for the period the law requires.",
        h5: "5. Grace period: 30 days",
        s5p1: "After confirming the deletion request from within the platform, your account enters a 30-day grace period during which you can fully restore it simply by signing in again. After this period, your data is permanently deleted and cannot be recovered.",
        h6: "6. Inquiries",
        s6p1: "For any inquiry about account deletion or how your data is processed, contact us at:",
        s6li1: "Email:",
        seePrivacy: "See also our Privacy Policy",
        backBtn: "Back to home",
        copyrightLine2: "All rights reserved",
        aboutLink: "About us",
        termsLink: "Terms of use",
        pricingLink: "Plans and pricing",
        privacyLink: "Privacy policy",
        deleteAccountLink: "Delete account",
        loginLink: "Sign in",
        accountLabel: "Account",
        contactLink: "Contact us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        title: "Supprimer le compte",
        intro: "Vous pouvez demander la suppression de votre compte MrZahi à tout moment, directement depuis la plateforme ou en envoyant une demande par e-mail. Les étapes ci-dessous expliquent ce qu'il advient de vos données après la suppression.",
        h1: "1. Suppression depuis la plateforme",
        s1li1: "Ouvrez mrzahi.com et connectez-vous à votre compte",
        s1li2: "Allez dans Paramètres",
        s1li3: "Choisissez « Supprimer le compte » sous votre profil",
        s1li4: "Confirmez la demande pour terminer la suppression",
        h2: "2. Suppression par e-mail",
        s2p1: "Si vous ne pouvez pas accéder à votre compte, envoyez une demande de suppression depuis l'adresse e-mail enregistrée sur votre compte à :",
        s2p2: "Veuillez inclure le nom complet et le numéro de téléphone enregistrés sur votre compte pour accélérer la vérification. Nous répondrons sous quelques jours ouvrés.",
        h3: "3. Ce qui est supprimé",
        s3li1: "Vos données personnelles : nom, e-mail, numéro de téléphone et paramètres de compte",
        s3li2: "Les canaux de notification liés à votre compte (Telegram et autres) et vos notifications",
        s3li3: "Votre appartenance à toute entreprise où vous êtes membre (les données de l'entreprise restent pour ses autres membres)",
        s3li4: "Si vous êtes l'unique propriétaire d'une entreprise sans autre membre actif : l'entreprise et tous ses éléments et registres sont supprimés avec vous",
        s3p2: "Si vous possédez une entreprise ayant encore d'autres membres actifs, la suppression de votre compte ne peut pas être finalisée avant que vous transfériez la propriété à un autre membre ou retiriez ces membres, car leurs données ne vous appartiennent pas exclusivement.",
        h4: "4. Ce qui est conservé",
        s4p1: "Nous pouvons conserver des registres limités liés à la facturation ou pour respecter une obligation légale, uniquement pour la durée requise par la loi.",
        h5: "5. Délai de grâce : 30 jours",
        s5p1: "Après confirmation de la demande de suppression depuis la plateforme, votre compte entre dans un délai de grâce de 30 jours durant lequel vous pouvez le restaurer intégralement simplement en vous reconnectant. Passé ce délai, vos données sont définitivement supprimées et ne peuvent être récupérées.",
        h6: "6. Questions",
        s6p1: "Pour toute question concernant la suppression du compte ou le traitement de vos données, contactez-nous à :",
        s6li1: "E-mail :",
        seePrivacy: "Consultez aussi notre politique de confidentialité",
        backBtn: "Retour à l'accueil",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Offres et tarifs",
        privacyLink: "Politique de confidentialité",
        deleteAccountLink: "Supprimer le compte",
        loginLink: "Connexion",
        accountLabel: "Compte",
        contactLink: "Nous contacter",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        title: "اکاؤنٹ حذف کریں",
        intro: "آپ کسی بھی وقت اپنا MrZahi اکاؤنٹ حذف کرنے کی درخواست دے سکتے ہیں، یا تو براہ راست پلیٹ فارم کے اندر سے، یا ای میل کے ذریعے درخواست بھیج کر۔ نیچے حذف کرنے کے بعد آپ کے ڈیٹا کے ساتھ کیا ہوتا ہے وہ مراحل بیان کیے گئے ہیں۔",
        h1: "1. پلیٹ فارم کے اندر سے حذف کرنا",
        s1li1: "mrzahi.com کھولیں اور اپنے اکاؤنٹ میں سائن ان کریں",
        s1li2: "سیٹنگز میں جائیں",
        s1li3: "اپنے پروفائل کے نیچے «اکاؤنٹ حذف کریں» منتخب کریں",
        s1li4: "حذف مکمل کرنے کے لیے درخواست کی تصدیق کریں",
        h2: "2. ای میل کے ذریعے حذف کرنا",
        s2p1: "اگر آپ اپنے اکاؤنٹ تک رسائی حاصل نہیں کر سکتے تو اپنے اکاؤنٹ پر رجسٹرڈ ای میل ایڈریس سے حذف کرنے کی درخواست بھیجیں:",
        s2p2: "توثیق کے عمل کو تیز کرنے کے لیے براہ کرم اپنے اکاؤنٹ پر رجسٹرڈ مکمل نام اور فون نمبر شامل کریں۔ ہم چند کاروباری دنوں میں جواب دیں گے۔",
        h3: "3. کیا حذف ہوتا ہے",
        s3li1: "آپ کا ذاتی ڈیٹا: نام، ای میل، فون نمبر، اور اکاؤنٹ کی ترتیبات",
        s3li2: "آپ کے اکاؤنٹ سے منسلک نوٹیفکیشن چینلز (ٹیلیگرام اور دیگر) اور آپ کے نوٹیفکیشنز",
        s3li3: "کسی بھی کمپنی میں آپ کی رکنیت جہاں آپ رکن ہیں (کمپنی کا اپنا ڈیٹا اس کے دیگر اراکین کے لیے باقی رہتا ہے)",
        s3li4: "اگر آپ کسی ایسی کمپنی کے واحد مالک ہیں جس میں کوئی دوسرا فعال رکن نہیں: کمپنی اور اس کے تمام آئٹمز اور ریکارڈز آپ کے ساتھ حذف ہو جاتے ہیں",
        s3p2: "اگر آپ ایسی کمپنی کے مالک ہیں جس میں دیگر فعال اراکین موجود ہیں، تو ملکیت کسی اور رکن کو منتقل کیے یا ان اراکین کو ہٹائے بغیر آپ کے اکاؤنٹ کا حذف مکمل نہیں کیا جا سکتا، کیونکہ ان کا ڈیٹا صرف آپ کا نہیں ہے۔",
        h4: "4. کیا برقرار رکھا جاتا ہے",
        s4p1: "ہم بلنگ سے متعلق یا قانونی ذمہ داری پوری کرنے کے لیے محدود ریکارڈ برقرار رکھ سکتے ہیں، صرف اس مدت کے لیے جو قانون کا تقاضا ہو۔",
        h5: "5. مہلت کی مدت: 30 دن",
        s5p1: "پلیٹ فارم کے اندر سے حذف کرنے کی درخواست کی تصدیق کے بعد، آپ کا اکاؤنٹ 30 دن کی مہلت میں داخل ہوتا ہے جس دوران آپ محض دوبارہ سائن ان کر کے اسے مکمل طور پر بحال کر سکتے ہیں۔ اس مدت کے بعد آپ کا ڈیٹا مستقل طور پر حذف ہو جاتا ہے اور اسے واپس نہیں لایا جا سکتا۔",
        h6: "6. سوالات",
        s6p1: "اکاؤنٹ حذف کرنے یا آپ کے ڈیٹا پر کارروائی کے بارے میں کسی بھی سوال کے لیے ہم سے رابطہ کریں:",
        s6li1: "ای میل:",
        seePrivacy: "ہماری رازداری کی پالیسی بھی دیکھیں",
        backBtn: "واپس ہوم",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        deleteAccountLink: "اکاؤنٹ حذف کریں",
        loginLink: "سائن ان",
        accountLabel: "اکاؤنٹ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };
    const lang = () => localStorage.getItem("mrzahi_lang") || "ar";
    const theme = () => localStorage.getItem("mrzahi_theme") || "dark";
    const langNames = { ar: "العربية", en: "English", fr: "Français", ur: "اردو" };
    let l = lang();
    document.documentElement.lang = l;
    document.documentElement.dir = (l === "ar" || l === "ur") ? "rtl" : "ltr";
    function setLang(c) { localStorage.setItem("mrzahi_lang", c); l = c; document.documentElement.lang = c; document.documentElement.dir = (c === "ar" || c === "ur") ? "rtl" : "ltr"; document.getElementById("currentLangDisplay").textContent = langNames[c] || c; ["ar","en","fr","ur"].forEach(x => { const e = document.getElementById("check-" + x); if (e) e.style.display = c === x ? "inline" : "none"; }); document.querySelectorAll("[data-i18n]").forEach(el => { const k = el.dataset.i18n; if (t[c] && t[c][k]) el.innerHTML = t[c][k]; }); document.getElementById("currentThemeDisplay").textContent = t[c][theme() === "dark" ? "dark" : "light"]; document.title = (t[c]?.title || "Delete account") + " | MrZahi"; }
    function setTheme(th) { localStorage.setItem("mrzahi_theme", th); document.documentElement.dataset.theme = th; document.getElementById("themeColorMeta").content = th === "dark" ? "#1a2933" : "#0068b8"; document.getElementById("footerLogo").src = th === "dark" ? "mrzahi-logo-full-dark.png?v=2" : "mrzahi-logo-full-light.png?v=2"; document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️"; document.getElementById("currentThemeDisplay").textContent = t[l][th === "dark" ? "dark" : "light"]; document.getElementById("check-light").style.display = th === "light" ? "inline" : "none"; document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none"; }
    document.getElementById("langMenuBtn").onclick = e => { e.stopPropagation(); document.getElementById("langDropdown").classList.toggle("show"); document.getElementById("themeDropdown").classList.remove("show"); };
    document.getElementById("themeMenuBtn").onclick = e => { e.stopPropagation(); setTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark"); document.getElementById("langDropdown").classList.remove("show"); };
    document.addEventListener("click", () => { document.getElementById("langDropdown").classList.remove("show"); document.getElementById("themeDropdown").classList.remove("show"); });
    document.querySelectorAll("#langDropdown .menu-dropdown-item").forEach(item => item.onclick = () => setLang(item.dataset.lang));
    document.querySelectorAll("#themeDropdown .menu-dropdown-item").forEach(item => item.onclick = () => { setTheme(item.dataset.theme); document.getElementById("themeDropdown").classList.remove("show"); });
    document.querySelectorAll("[data-i18n]").forEach(el => { const k = el.dataset.i18n; if (t[l] && t[l][k]) el.innerHTML = t[l][k]; });
    document.getElementById("currentLangDisplay").textContent = langNames[l] || l;
    ["ar","en","fr","ur"].forEach(x => { const e = document.getElementById("check-" + x); if (e) e.style.display = l === x ? "inline" : "none"; });
    document.title = (t[l]?.title || "Delete account") + " | MrZahi";
    (function(){ const th = theme(); document.documentElement.dataset.theme = th; document.getElementById("themeColorMeta").content = th === "dark" ? "#1a2933" : "#0068b8"; document.getElementById("footerLogo").src = th === "dark" ? "mrzahi-logo-full-dark.png?v=2" : "mrzahi-logo-full-light.png?v=2"; document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️"; document.getElementById("currentThemeDisplay").textContent = t[l][th === "dark" ? "dark" : "light"]; document.getElementById("check-light").style.display = th === "light" ? "inline" : "none"; document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none"; })();
