/* migration: نقل مفاتيح التخزين من الاسم القديم الى mrzahi_ مرة واحدة لكل متصفح، فلا يفقد احد لغته ولا ثيمه ولا حسابه المختار */
try{["lang","theme","org","sidebar","dash_tab","bell_seen","chat_seen","cal_mode","cal_zoom","dp_cal","drive_folder","tr"].forEach(function(k){var o=localStorage.getItem("record_"+k);if(o!==null&&localStorage.getItem("mrzahi_"+k)===null){localStorage.setItem("mrzahi_"+k,o);localStorage.removeItem("record_"+k);}});}catch(e){}
const t = {
      ar: {
        planTrialStorage: "‏200 ميغابايت للملفات",
        planFreelanceYearly: "أو 3,000 سنويا — شهران بلا مقابل.",
        planPersonalYearly: "أو 1,500 سنويا — شهران بلا مقابل.",
        planEnterpriseYearly: "أو 7,000 سنويا — شهران بلا مقابل.",
        planStartupYearly: "أو 5,000 سنويا — شهران بلا مقابل.",
        planStartupVat: "السعر لا يشمل ضريبة القيمة المضافة.",
        planEnterpriseVat: "السعر لا يشمل ضريبة القيمة المضافة.",
        planPersonalName: "شخصي",
        planPersonalPrice: "150",
        planPersonalPeriod: "/ شهريا",
        planPersonalNote: "أو 190 سنويا، أي شهران بلا مقابل.",
        planPersonalFor: "لمن يريد ترتيب أوراقه ومواعيده وحده.",
        planPersonalMembers: "مستخدم واحد",
        planPersonalItems: "حتى 300 عنصر",
        planPersonalStorage: "‏1 غيغابايت للملفات",
        planPersonalCalendar: "تقويم ICS وتقويم Google",
        planPersonalImports: "استيراد ملفين شهريا",
        planPersonalScope: "المستندات والمواعيد فقط",
        planFreelanceName: "عمل حر",
        planFreelancePrice: "300",
        planFreelancePeriod: "/ شهريا",
        planFreelanceNote: "أو 390 سنويا، أي شهران بلا مقابل.",
        planFreelanceFor: "لصاحب وثيقة العمل الحر.",
        planFreelanceMembers: "مستخدم واحد",
        planFreelanceItems: "حتى 1,500 عنصر",
        planFreelanceStorage: "‏2 غيغابايت للملفات",
        planFreelanceDocs: "الوثيقة والـ IBAN والعقود والفواتير",
        planFreelanceChannels: "تنبيهات على Telegram",
        planFreelanceCalendar: "تقويم ICS وتقويم Google",
        planStartupName: "منشأة متناهية الصغر وصغيرة",
        planStartupPrice: "500",
        planStartupPeriod: "/ شهريا",
        planStartupNote: "المقعد الإضافي 25 شهريا فوق عدد الباقة.",
        planStartupFor: "للمؤسسات والشركات الناشئة ذات السجل التجاري.",
        planStartupMembers: "حتى 3 أعضاء",
        planStartupItems: "حتى 10,000 عنصر",
        planStartupStorage: "‏5 غيغابايت للملفات",
        planStartupScope: "كل المزايا: القضايا والعقود والمخالفات والمخاطر والفريق",
        planStartupChannels: "تنبيهات على Telegram",
        planStartupImports: "استيراد بلا حد",
        planEnterpriseName: "منشأة متوسطة وكبيرة",
        planEnterprisePrice: "700",
        planEnterprisePeriod: "/ شهريا",
        planEnterpriseNote: "المقعد الإضافي 25 شهريا فوق عدد الباقة.",
        planEnterpriseFor: "للشركات الكبيرة ذات الفرق والإدارات.",
        planEnterpriseMembers: "حتى 5 أعضاء",
        planEnterpriseItems: "حتى 100,000 عنصر",
        planEnterpriseStorage: "‏10 غيغابايت للملفات",
        planEnterpriseScope: "كل المزايا بحدود أوسع",
        planEnterpriseChannels: "تنبيهات على Telegram",
        planEnterpriseSupport: "دعم ذو أولوية",
        title: "الباقات والأسعار",
        intro: "تبدأ منصة MrZahi بفترة تجريبية مدتها 14 يوما بكل المزايا وبلا بطاقة بنكية، ثم تختار الشريحة التي تناسب حسابك: شخصي لمن يرتب أوراقه وحده، وعمل حر لصاحب الوثيقة، ومؤسسة وشركة ناشئة، وشركة كبيرة. وكل الشرائح فيها التقويم والتنبيهات قبل مواعيد الاستحقاق ورفع ملفات Excel.",
        planTrialName: "التجريبية",
        planTrialPrice: "0",
        planTrialPeriod: "/ لمدة 14 يوما",
        planTrialNote: "جرب المنصة أربعة عشر يوما بلا بطاقة بنكية، ثم اختر الشريحة التي تناسب حسابك.",
        planTrialMembers: "مستخدم واحد",
        planTrialItems: "حتى 300 عنصر",
        planTrialChannels: "تنبيهات على Telegram",
        planTrialImports: "استيراد ملفين",
        planTrialCalendar: "تقويم ICS وتقويم Google",
        planTrialSupport: "الدعم عبر البريد الإلكتروني",
        planTrialCta: "ابدأ التجربة المجانية",
        planMonthlyName: "الشهرية",
        planMonthlyPrice: "49",
        planMonthlyPeriod: "/ شهريا",
        planMonthlyMembers: "حتى 5 أعضاء",
        planMonthlyItems: "حتى 2,000 عنصر سجل",
        planMonthlyChannels: "تنبيهات على Telegram",
        planMonthlyImports: "استيراد غير محدود لملفات Excel",
        planMonthlyCalendar: "تقويم ICS وتقويم Google",
        planMonthlySupport: "الدعم عبر البريد الإلكتروني",
        planYearlyName: "السنوية",
        planYearlyPrice: "490",
        planYearlyFor: "للشركات الناشئة ووثائق العمل الحر والأفراد.",
        planBusinessName: "باقة الشركات",
        planBusinessPrice: "7,000",
        planBusinessPeriod: "/ سنويا",
        planBusinessVat: "السعر لا يشمل ضريبة القيمة المضافة.",
        planBusinessFor: "للشركات والمؤسسات ذات السجل التجاري.",
        planBusinessMembers: "أعضاء بلا حد",
        planBusinessItems: "عناصر بلا حد",
        planBusinessChannels: "تنبيهات على Telegram",
        planBusinessImports: "استيراد غير محدود لملفات Excel",
        planBusinessCalendar: "تقويم ICS وتقويم Google",
        planBusinessSupport: "دعم ذو أولوية",
        planYearlyPeriod: "/ سنويا",
        planYearlyNote: "أي ما يعادل شهرين مجانا مقارنة بالاشتراك الشهري.",
        planYearlyMembers: "حتى 15 عضوا",
        planYearlyItems: "حتى 20,000 عنصر سجل",
        planYearlyChannels: "تنبيهات على Telegram",
        planYearlyImports: "استيراد غير محدود لملفات Excel",
        planYearlyCalendar: "تقويم ICS وتقويم Google",
        planYearlySupport: "دعم ذو أولوية",
        planPaidCta: "اختر الباقة",
        activationLabel: "1. كيفية تفعيل الباقات حاليا",
        activationText1: "تفعل الباقة المدفوعة تلقائيا وفورا بعد إتمام الدفع الإلكتروني من صفحة الإعدادات في حسابك. لأي استفسار راسلنا على",
        activationText2: "أو عبر مساعد المحادثة داخل المنصة.",
        vatLabel: "2. ضريبة القيمة المضافة",
        vatText: "تطبق ضريبة القيمة المضافة على الباقات المدفوعة وفقا لأنظمة هيئة الزكاة والضريبة والجمارك في المملكة العربية السعودية حيثما ينطبق ذلك، وتبين قيمتها بوضوح قبل إتمام التفعيل.",
        renewalLabel: "3. التجديد والتغييرات",
        renewalText: "يمكنك الاشتراك في باقة مدفوعة أثناء الفترة التجريبية أو بعد انتهائها، والترقية من الباقة الشهرية إلى السنوية في أي وقت. تطبق حدود كل باقة (عدد الأعضاء، وعدد العناصر المسجلة، وقنوات التنبيه، وعمليات الاستيراد) تقنيا داخل المنصة. مدة الفترة التجريبية 14 يوما من تاريخ إنشاء الشركة، ومدة الباقة الشهرية شهر واحد، ومدة الباقة السنوية 12 شهرا كاملة من تاريخ التفعيل، ويتم التجديد تلقائيا بالدفع الإلكتروني نفسه المبين في البند 1. بعد انتهاء الفترة التجريبية دون اشتراك يبقى حسابك وبياناتك كما هي للاطلاع والتصدير، وتتوقف إضافة عناصر أو أعضاء جدد حتى التفعيل.",
        refundLabel: "4. الاسترجاع",
        refundText: "لا تسترد المبالغ المدفوعة عن الفترات الجزئية غير المستخدمة من الاشتراك الشهري أو السنوي، إلا فيما تقتضيه الأنظمة المعمول بها في المملكة العربية السعودية.",
        contactLabel: "5. التواصل",
        contactText1: "للاستفسار عن الباقات أو طلب تفعيل باقة مدفوعة، راسلنا على",
        contactText2: "يمكنك أيضا استخدام",
        contactFormLink: "نموذج التواصل في الصفحة الرئيسية",
        contactText3: ".",
        lastUpdated: "آخر تحديث: سبتمبر 2026",
        backBtn: "العودة للرئيسية",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        deleteAccountLink: "حذف الحساب",
        loginLink: "تسجيل الدخول",
        accountLabel: "الحساب",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        planTrialStorage: "200 MB for files",
        planFreelanceYearly: "Or 3,000 a year — two months free.",
        planPersonalYearly: "Or 1,500 a year — two months free.",
        planEnterpriseYearly: "Or 7,000 a year — two months free.",
        planStartupYearly: "Or 5,000 a year — two months free.",
        planStartupVat: "Price excludes VAT.",
        planEnterpriseVat: "Price excludes VAT.",
        planPersonalName: "Personal",
        planPersonalPrice: "150",
        planPersonalPeriod: "/ month",
        planPersonalNote: "Or 190 a year — two months free.",
        planPersonalFor: "For organising your own papers and dates.",
        planPersonalMembers: "One user",
        planPersonalItems: "Up to 300 items",
        planPersonalStorage: "1 GB for files",
        planPersonalCalendar: "ICS and Google Calendar",
        planPersonalImports: "Two imports a month",
        planPersonalScope: "Documents and dates only",
        planFreelanceName: "Freelance",
        planFreelancePrice: "300",
        planFreelancePeriod: "/ month",
        planFreelanceNote: "Or 390 a year — two months free.",
        planFreelanceFor: "For freelance permit holders.",
        planFreelanceMembers: "One user",
        planFreelanceItems: "Up to 1,500 items",
        planFreelanceStorage: "2 GB for files",
        planFreelanceDocs: "Permit, IBAN, contracts and invoices",
        planFreelanceChannels: "Telegram reminders",
        planFreelanceCalendar: "ICS and Google Calendar",
        planStartupName: "Micro & Small Enterprise",
        planStartupPrice: "500",
        planStartupPeriod: "/ month",
        planStartupNote: "Extra seat 25 a month above the plan count.",
        planStartupFor: "For establishments and startups with a commercial register.",
        planStartupMembers: "Up to 3 members",
        planStartupItems: "Up to 10,000 items",
        planStartupStorage: "5 GB for files",
        planStartupScope: "Every feature: cases, contracts, violations, risks and team",
        planStartupChannels: "Telegram reminders",
        planStartupImports: "Unlimited imports",
        planEnterpriseName: "Medium & Large Enterprise",
        planEnterprisePrice: "700",
        planEnterprisePeriod: "/ month",
        planEnterpriseNote: "Extra seat 25 a month above the plan count.",
        planEnterpriseFor: "For larger companies with teams and departments.",
        planEnterpriseMembers: "Up to 5 members",
        planEnterpriseItems: "Up to 100,000 items",
        planEnterpriseStorage: "10 GB for files",
        planEnterpriseScope: "Every feature with wider limits",
        planEnterpriseChannels: "Telegram reminders",
        planEnterpriseSupport: "Priority support",
        title: "Plans & Pricing",
        intro: "MrZahi starts with a 14-day trial with every feature and no bank card, then you pick the tier that fits your account: Personal for organising your own papers, Freelance for permit holders, Business for establishments and startups, and Enterprise for larger companies. Every tier includes the calendar, reminders before due dates, and Excel imports.",
        planTrialName: "Trial",
        planTrialPrice: "0",
        planTrialPeriod: "/ for 14 days",
        planTrialNote: "Try the platform for fourteen days with no bank card, then pick the tier that fits your account.",
        planTrialMembers: "One user",
        planTrialItems: "Up to 300 items",
        planTrialChannels: "Telegram reminders",
        planTrialImports: "Two imports",
        planTrialCalendar: "ICS and Google Calendar",
        planTrialSupport: "Email support",
        planTrialCta: "Start the free trial",
        planMonthlyName: "Monthly",
        planMonthlyPrice: "49",
        planMonthlyPeriod: "/ month",
        planMonthlyMembers: "Up to 5 members",
        planMonthlyItems: "Up to 2,000 tracked items",
        planMonthlyChannels: "Telegram reminders",
        planMonthlyImports: "Unlimited Excel imports",
        planMonthlyCalendar: "ICS calendar and Google Calendar",
        planMonthlySupport: "Email support",
        planYearlyName: "Yearly",
        planYearlyPrice: "490",
        planYearlyFor: "For startups, freelance permits and individuals.",
        planBusinessName: "Business plan",
        planBusinessPrice: "7,000",
        planBusinessPeriod: "/ per year",
        planBusinessVat: "Price excludes VAT.",
        planBusinessFor: "For companies and establishments with a commercial register.",
        planBusinessMembers: "Unlimited members",
        planBusinessItems: "Unlimited items",
        planBusinessChannels: "Telegram alerts",
        planBusinessImports: "Unlimited Excel imports",
        planBusinessCalendar: "ICS and Google calendar",
        planBusinessSupport: "Priority support",
        planYearlyPeriod: "/ year",
        planYearlyNote: "Equivalent to two months free compared with the monthly plan.",
        planYearlyMembers: "Up to 15 members",
        planYearlyItems: "Up to 20,000 tracked items",
        planYearlyChannels: "Telegram reminders",
        planYearlyImports: "Unlimited Excel imports",
        planYearlyCalendar: "ICS calendar and Google Calendar",
        planYearlySupport: "Priority support",
        planPaidCta: "Choose this plan",
        activationLabel: "1. How plans are activated today",
        activationText1: "Paid plans are currently activated by contacting our support team at",
        activationText2: "or through the chat assistant inside the platform. Once your request is confirmed, the plan is enabled on your company account. Online payment through a payment gateway will be available later.",
        vatLabel: "2. Value Added Tax",
        vatText: "Value Added Tax (VAT) is applied to paid plans in accordance with the regulations of the Zakat, Tax and Customs Authority (ZATCA) of the Kingdom of Saudi Arabia where applicable, and its amount is shown clearly before activation is completed.",
        renewalLabel: "3. Renewals and changes",
        renewalText: "You can subscribe to a paid plan during the trial or after it ends, and upgrade from the Monthly plan to the Yearly plan at any time. Each plan's limits (members, tracked items, reminder channels and imports) are enforced technically inside the platform. The trial lasts 14 days from the date the company is created, the Monthly plan runs for one month and the Yearly plan for a full 12 months from the activation date; renewals follow the same process described in section 1 until online payment becomes available. If the trial ends without a subscription your account and data remain available to view and export, while adding new items or members stops until a plan is activated.",
        refundLabel: "4. Refunds",
        refundText: "No refunds are issued for unused partial periods of a monthly or yearly subscription, except where required by the applicable laws of the Kingdom of Saudi Arabia.",
        contactLabel: "5. Contact",
        contactText1: "For questions about plans or to request activation of a paid plan, email us at",
        contactText2: "You can also use",
        contactFormLink: "the contact form on the home page",
        contactText3: ".",
        lastUpdated: "Last updated: September 2026",
        backBtn: "Back to Home",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        deleteAccountLink: "Delete account",
        loginLink: "Sign in",
        accountLabel: "Account",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        planTrialStorage: "200 Mo pour les fichiers",
        planFreelanceYearly: "Ou 3 000 par an — deux mois offerts.",
        planPersonalYearly: "Ou 1 500 par an — deux mois offerts.",
        planEnterpriseYearly: "Ou 7 000 par an — deux mois offerts.",
        planStartupYearly: "Ou 5 000 par an — deux mois offerts.",
        planStartupVat: "Prix hors TVA.",
        planEnterpriseVat: "Prix hors TVA.",
        planPersonalName: "Personnel",
        planPersonalPrice: "150",
        planPersonalPeriod: "/ mois",
        planPersonalNote: "Ou 190 par an — deux mois offerts.",
        planPersonalFor: "Pour organiser vos propres papiers et échéances.",
        planPersonalMembers: "Un utilisateur",
        planPersonalItems: "Jusqu'à 300 éléments",
        planPersonalStorage: "1 Go pour les fichiers",
        planPersonalCalendar: "ICS et Google Agenda",
        planPersonalImports: "Deux imports par mois",
        planPersonalScope: "Documents et échéances uniquement",
        planFreelanceName: "Indépendant",
        planFreelancePrice: "300",
        planFreelancePeriod: "/ mois",
        planFreelanceNote: "Ou 390 par an — deux mois offerts.",
        planFreelanceFor: "Pour les titulaires d'un permis de travail indépendant.",
        planFreelanceMembers: "Un utilisateur",
        planFreelanceItems: "Jusqu'à 1 500 éléments",
        planFreelanceStorage: "2 Go pour les fichiers",
        planFreelanceDocs: "Permis, IBAN, contrats et factures",
        planFreelanceChannels: "Rappels sur Telegram",
        planFreelanceCalendar: "ICS et Google Agenda",
        planStartupName: "Micro et petite entreprise",
        planStartupPrice: "500",
        planStartupPeriod: "/ mois",
        planStartupNote: "Siège supplémentaire 25 par mois au-delà du forfait.",
        planStartupFor: "Pour les établissements et jeunes entreprises avec registre de commerce.",
        planStartupMembers: "Jusqu'à 3 membres",
        planStartupItems: "Jusqu'à 10 000 éléments",
        planStartupStorage: "5 Go pour les fichiers",
        planStartupScope: "Toutes les fonctions : affaires, contrats, infractions, risques et équipe",
        planStartupChannels: "Rappels sur Telegram",
        planStartupImports: "Imports illimités",
        planEnterpriseName: "Moyenne et grande entreprise",
        planEnterprisePrice: "700",
        planEnterprisePeriod: "/ mois",
        planEnterpriseNote: "Siège supplémentaire 25 par mois au-delà du forfait.",
        planEnterpriseFor: "Pour les grandes sociétés avec équipes et services.",
        planEnterpriseMembers: "Jusqu'à 5 membres",
        planEnterpriseItems: "Jusqu'à 100 000 éléments",
        planEnterpriseStorage: "10 Go pour les fichiers",
        planEnterpriseScope: "Toutes les fonctions avec des limites plus larges",
        planEnterpriseChannels: "Rappels sur Telegram",
        planEnterpriseSupport: "Support prioritaire",
        title: "Forfaits et tarifs",
        intro: "MrZahi commence par un essai de 14 jours avec toutes les fonctions et sans carte bancaire, puis vous choisissez la formule adaptée à votre compte : Personnel, Indépendant, Entreprise, ou Grande entreprise. Toutes incluent l'agenda, les rappels avant échéance et l'import Excel.",
        planTrialName: "Essai",
        planTrialPrice: "0",
        planTrialPeriod: "/ pendant 14 jours",
        planTrialNote: "Essayez la plateforme quatorze jours sans carte bancaire, puis choisissez la formule adaptée.",
        planTrialMembers: "Un utilisateur",
        planTrialItems: "Jusqu'à 300 éléments",
        planTrialChannels: "Rappels sur Telegram",
        planTrialImports: "Deux imports",
        planTrialCalendar: "ICS et Google Agenda",
        planTrialSupport: "Assistance par e-mail",
        planTrialCta: "Commencer l'essai gratuit",
        planMonthlyName: "Mensuel",
        planMonthlyPrice: "49",
        planMonthlyPeriod: "/ mois",
        planMonthlyMembers: "Jusqu'à 5 membres",
        planMonthlyItems: "Jusqu'à 2 000 éléments suivis",
        planMonthlyChannels: "Rappels sur Telegram",
        planMonthlyImports: "Imports Excel illimités",
        planMonthlyCalendar: "Calendrier ICS et Google Agenda",
        planMonthlySupport: "Assistance par e-mail",
        planYearlyName: "Annuel",
        planYearlyPrice: "490",
        planYearlyFor: "Pour les startups, les permis freelance et les particuliers.",
        planBusinessName: "Offre entreprise",
        planBusinessPrice: "7 000",
        planBusinessPeriod: "/ par an",
        planBusinessVat: "Prix hors TVA.",
        planBusinessFor: "Pour les sociétés et établissements immatriculés.",
        planBusinessMembers: "Membres illimités",
        planBusinessItems: "Éléments illimités",
        planBusinessChannels: "Alertes Telegram",
        planBusinessImports: "Imports Excel illimités",
        planBusinessCalendar: "Calendrier ICS et Google",
        planBusinessSupport: "Support prioritaire",
        planYearlyPeriod: "/ an",
        planYearlyNote: "Soit deux mois gratuits par rapport au forfait mensuel.",
        planYearlyMembers: "Jusqu'à 15 membres",
        planYearlyItems: "Jusqu'à 20 000 éléments suivis",
        planYearlyChannels: "Rappels sur Telegram",
        planYearlyImports: "Imports Excel illimités",
        planYearlyCalendar: "Calendrier ICS et Google Agenda",
        planYearlySupport: "Assistance prioritaire",
        planPaidCta: "Choisir ce forfait",
        activationLabel: "1. Activation des forfaits aujourd'hui",
        activationText1: "Les forfaits payants sont actuellement activés en contactant notre équipe d'assistance à l'adresse",
        activationText2: "ou via l'assistant de discussion intégré à la plateforme. Une fois votre demande confirmée, le forfait est activé sur le compte de votre entreprise. Le paiement en ligne via une passerelle de paiement sera disponible ultérieurement.",
        vatLabel: "2. Taxe sur la valeur ajoutée",
        vatText: "La taxe sur la valeur ajoutée (TVA) s'applique aux forfaits payants conformément à la réglementation de l'Autorité de la Zakat, des Impôts et des Douanes (ZATCA) du Royaume d'Arabie saoudite, le cas échéant, et son montant est clairement indiqué avant la finalisation de l'activation.",
        renewalLabel: "3. Renouvellements et changements",
        renewalText: "Vous pouvez souscrire un forfait payant pendant l'essai ou après sa fin, et passer du forfait Mensuel au forfait Annuel à tout moment. Les limites de chaque forfait (membres, éléments suivis, canaux de rappel et imports) sont appliquées techniquement dans la plateforme. L'essai dure 14 jours à compter de la création de l'entreprise, le forfait Mensuel dure un mois et le forfait Annuel 12 mois complets à compter de la date d'activation ; les renouvellements suivent la procédure décrite à l'article 1 jusqu'à la mise en place du paiement en ligne. Si l'essai se termine sans abonnement, votre compte et vos données restent consultables et exportables, tandis que l'ajout de nouveaux éléments ou membres s'arrête jusqu'à l'activation d'un forfait.",
        refundLabel: "4. Remboursements",
        refundText: "Aucun remboursement n'est accordé pour les périodes partielles non utilisées d'un abonnement mensuel ou annuel, sauf lorsque la législation applicable du Royaume d'Arabie saoudite l'exige.",
        contactLabel: "5. Contact",
        contactText1: "Pour toute question sur les forfaits ou pour demander l'activation d'un forfait payant, écrivez-nous à",
        contactText2: "Vous pouvez également utiliser",
        contactFormLink: "le formulaire de contact de la page d'accueil",
        contactText3: ".",
        lastUpdated: "Dernière mise à jour : septembre 2026",
        backBtn: "Retour à l'accueil",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        deleteAccountLink: "Supprimer le compte",
        loginLink: "Connexion",
        accountLabel: "Compte",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        planTrialStorage: "فائلوں کے لیے 200 MB",
        planFreelanceYearly: "یا سالانہ 3,000 — دو مہینے مفت۔",
        planPersonalYearly: "یا سالانہ 1,500 — دو مہینے مفت۔",
        planEnterpriseYearly: "یا سالانہ 7,000 — دو مہینے مفت۔",
        planStartupYearly: "یا سالانہ 5,000 — دو مہینے مفت۔",
        planStartupVat: "قیمت میں ویٹ شامل نہیں۔",
        planEnterpriseVat: "قیمت میں ویٹ شامل نہیں۔",
        planPersonalName: "ذاتی",
        planPersonalPrice: "150",
        planPersonalPeriod: "/ ماہانہ",
        planPersonalNote: "یا سالانہ 190 — دو مہینے مفت۔",
        planPersonalFor: "اپنے کاغذات اور تاریخیں ترتیب دینے کے لیے۔",
        planPersonalMembers: "ایک صارف",
        planPersonalItems: "300 آئٹمز تک",
        planPersonalStorage: "فائلوں کے لیے 1 GB",
        planPersonalCalendar: "ICS اور Google Calendar",
        planPersonalImports: "ماہانہ دو درآمد",
        planPersonalScope: "صرف دستاویزات اور تاریخیں",
        planFreelanceName: "فری لانس",
        planFreelancePrice: "300",
        planFreelancePeriod: "/ ماہانہ",
        planFreelanceNote: "یا سالانہ 390 — دو مہینے مفت۔",
        planFreelanceFor: "فری لانس اجازت رکھنے والوں کے لیے۔",
        planFreelanceMembers: "ایک صارف",
        planFreelanceItems: "1,500 آئٹمز تک",
        planFreelanceStorage: "فائلوں کے لیے 2 GB",
        planFreelanceDocs: "اجازت نامہ، IBAN، معاہدے اور رسیدیں",
        planFreelanceChannels: "Telegram پر یاد دہانیاں",
        planFreelanceCalendar: "ICS اور Google Calendar",
        planStartupName: "مائیکرو اور چھوٹا ادارہ",
        planStartupPrice: "500",
        planStartupPeriod: "/ ماہانہ",
        planStartupNote: "پلان کی تعداد سے اوپر اضافی نشست 25 ماہانہ۔",
        planStartupFor: "کمرشل رجسٹر والے اداروں اور نئی کمپنیوں کے لیے۔",
        planStartupMembers: "3 ارکان تک",
        planStartupItems: "10,000 آئٹمز تک",
        planStartupStorage: "فائلوں کے لیے 5 GB",
        planStartupScope: "تمام خصوصیات: مقدمات، معاہدے، خلاف ورزیاں، خطرات اور ٹیم",
        planStartupChannels: "Telegram پر یاد دہانیاں",
        planStartupImports: "لامحدود درآمد",
        planEnterpriseName: "درمیانہ اور بڑا ادارہ",
        planEnterprisePrice: "700",
        planEnterprisePeriod: "/ ماہانہ",
        planEnterpriseNote: "پلان کی تعداد سے اوپر اضافی نشست 25 ماہانہ۔",
        planEnterpriseFor: "ٹیموں اور شعبوں والی بڑی کمپنیوں کے لیے۔",
        planEnterpriseMembers: "5 ارکان تک",
        planEnterpriseItems: "100,000 آئٹمز تک",
        planEnterpriseStorage: "فائلوں کے لیے 10 GB",
        planEnterpriseScope: "وسیع حدود کے ساتھ تمام خصوصیات",
        planEnterpriseChannels: "Telegram پر یاد دہانیاں",
        planEnterpriseSupport: "ترجیحی معاونت",
        title: "پلانز اور قیمتیں",
        intro: "MrZahi چودہ دن کی آزمائش سے شروع ہوتا ہے، تمام خصوصیات کے ساتھ اور بینک کارڈ کے بغیر، پھر آپ اپنے اکاؤنٹ کے مطابق درجہ منتخب کرتے ہیں: ذاتی، فری لانس، کاروبار، یا بڑا ادارہ۔ ہر درجے میں کیلنڈر، آخری تاریخ سے پہلے یاد دہانیاں، اور Excel درآمد شامل ہیں۔",
        planTrialName: "آزمائشی",
        planTrialPrice: "0",
        planTrialPeriod: "/ 14 دن کے لیے",
        planTrialNote: "چودہ دن بغیر بینک کارڈ آزمائیں، پھر اپنے اکاؤنٹ کے مطابق درجہ منتخب کریں۔",
        planTrialMembers: "ایک صارف",
        planTrialItems: "300 آئٹمز تک",
        planTrialChannels: "Telegram پر یاد دہانیاں",
        planTrialImports: "دو درآمد",
        planTrialCalendar: "ICS اور Google Calendar",
        planTrialSupport: "ای میل معاونت",
        planTrialCta: "مفت آزمائش شروع کریں",
        planMonthlyName: "ماہانہ",
        planMonthlyPrice: "49",
        planMonthlyPeriod: "/ ماہ",
        planMonthlyMembers: "5 اراکین تک",
        planMonthlyItems: "2,000 ٹریک شدہ آئٹمز تک",
        planMonthlyChannels: "ٹیلیگرام پر یاد دہانیاں",
        planMonthlyImports: "لامحدود ایکسل امپورٹس",
        planMonthlyCalendar: "ICS کیلنڈر اور گوگل کیلنڈر",
        planMonthlySupport: "ای میل سپورٹ",
        planYearlyName: "سالانہ",
        planYearlyPrice: "490",
        planYearlyFor: "اسٹارٹ اپ، فری لانس اجازت ناموں اور افراد کے لیے۔",
        planBusinessName: "کمپنی پیکیج",
        planBusinessPrice: "7,000",
        planBusinessPeriod: "/ سالانہ",
        planBusinessVat: "قیمت ویٹ کے بغیر ہے۔",
        planBusinessFor: "تجارتی رجسٹر رکھنے والی کمپنیوں کے لیے۔",
        planBusinessMembers: "لامحدود اراکین",
        planBusinessItems: "لامحدود آئٹمز",
        planBusinessChannels: "ٹیلیگرام اطلاعات",
        planBusinessImports: "لامحدود ایکسل درآمد",
        planBusinessCalendar: "ICS اور گوگل کیلنڈر",
        planBusinessSupport: "ترجیحی معاونت",
        planYearlyPeriod: "/ سال",
        planYearlyNote: "ماہانہ پلان کے مقابلے میں دو ماہ مفت کے برابر۔",
        planYearlyMembers: "15 اراکین تک",
        planYearlyItems: "20,000 ٹریک شدہ آئٹمز تک",
        planYearlyChannels: "ٹیلیگرام پر یاد دہانیاں",
        planYearlyImports: "لامحدود ایکسل امپورٹس",
        planYearlyCalendar: "ICS کیلنڈر اور گوگل کیلنڈر",
        planYearlySupport: "ترجیحی سپورٹ",
        planPaidCta: "یہ پلان منتخب کریں",
        activationLabel: "1. پلانز فی الحال کیسے فعال ہوتے ہیں",
        activationText1: "ادا شدہ پلانز فی الحال ہماری سپورٹ ٹیم سے رابطہ کر کے فعال کیے جاتے ہیں، ای میل کے ذریعے:",
        activationText2: "یا پلیٹ فارم کے اندر موجود چیٹ اسسٹنٹ کے ذریعے۔ آپ کی درخواست کی تصدیق کے بعد پلان آپ کی کمپنی کے اکاؤنٹ پر فعال کر دیا جاتا ہے۔ پیمنٹ گیٹ وے کے ذریعے آن لائن ادائیگی بعد میں دستیاب ہوگی۔",
        vatLabel: "2. ویلیو ایڈڈ ٹیکس",
        vatText: "ادا شدہ پلانز پر ویلیو ایڈڈ ٹیکس (VAT) مملکت سعودی عرب کی زکوۃ، ٹیکس اور کسٹمز اتھارٹی (ZATCA) کے ضوابط کے مطابق، جہاں لاگو ہو، عائد کیا جاتا ہے، اور اس کی رقم فعال کاری مکمل ہونے سے پہلے واضح طور پر دکھائی جاتی ہے۔",
        renewalLabel: "3. تجدید اور تبدیلیاں",
        renewalText: "آپ آزمائشی مدت کے دوران یا اس کے بعد ادا شدہ پلان کی سبسکرپشن لے سکتے ہیں، اور کسی بھی وقت ماہانہ پلان سے سالانہ پلان پر اپ گریڈ کر سکتے ہیں۔ ہر پلان کی حدود (اراکین، ٹریک شدہ آئٹمز، یاد دہانی چینلز اور امپورٹس) پلیٹ فارم کے اندر تکنیکی طور پر نافذ کی جاتی ہیں۔ آزمائشی مدت کمپنی بنانے کی تاریخ سے 14 دن، ماہانہ پلان ایک ماہ اور سالانہ پلان فعال کاری کی تاریخ سے پورے 12 ماہ ہے؛ آن لائن ادائیگی دستیاب ہونے تک تجدید سیکشن 1 میں بیان کردہ طریقے سے کی جاتی ہے۔ اگر آزمائشی مدت سبسکرپشن کے بغیر ختم ہو جائے تو آپ کا اکاؤنٹ اور ڈیٹا دیکھنے اور ایکسپورٹ کرنے کے لیے دستیاب رہتا ہے، جبکہ نئے آئٹمز یا اراکین کا اضافہ پلان فعال ہونے تک رک جاتا ہے۔",
        refundLabel: "4. رقم کی واپسی",
        refundText: "ماہانہ یا سالانہ سبسکرپشن کی غیر استعمال شدہ جزوی مدت کے لیے رقم واپس نہیں کی جاتی، سوائے اس کے کہ مملکت سعودی عرب کے قابل اطلاق قوانین اس کا تقاضا کریں۔",
        contactLabel: "5. رابطہ",
        contactText1: "پلانز کے بارے میں سوالات یا ادا شدہ پلان کی فعال کاری کی درخواست کے لیے ہمیں ای میل کریں:",
        contactText2: "آپ",
        contactFormLink: "ہوم پیج پر موجود رابطہ فارم",
        contactText3: " بھی استعمال کر سکتے ہیں۔",
        lastUpdated: "آخری اپ ڈیٹ: ستمبر 2026",
        backBtn: "واپس ہوم",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        deleteAccountLink: "اکاؤنٹ حذف کریں",
        loginLink: "سائن ان",
        accountLabel: "اکاؤنٹ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };

    const lang = () => localStorage.getItem("mrzahi_lang") || "ar";
    const theme = () => localStorage.getItem("mrzahi_theme") || "dark";
    const langNames = { ar: "العربية", en: "English", fr: "Français", ur: "اردو" };
    let l = lang();
    document.documentElement.lang = l;
    document.documentElement.dir = (l === "ar" || l === "ur") ? "rtl" : "ltr";

    function setLang(code) {
      localStorage.setItem("mrzahi_lang", code);
      l = code;
      document.documentElement.lang = code;
      document.documentElement.dir = (code === "ar" || code === "ur") ? "rtl" : "ltr";
      document.getElementById("currentLangDisplay").textContent = langNames[code] || code;
      ["ar","en","fr","ur"].forEach(c => {
        const el = document.getElementById("check-" + c);
        if (el) el.style.display = c === code ? "inline" : "none";
      });
      const th = theme();
      document.getElementById("currentThemeDisplay").textContent = t[code][th === "dark" ? "dark" : "light"];
      document.querySelectorAll("[data-i18n]").forEach(el => {
        const k = el.dataset.i18n;
        if (t[code] && t[code][k]) el.innerHTML = t[code][k];
      });
      document.title = (t[code] && t[code].title ? t[code].title : "Plans & Pricing") + " | MrZahi";
    }

    function setTheme(th) {
      localStorage.setItem("mrzahi_theme", th);
      document.documentElement.dataset.theme = th;
      const meta = document.getElementById("themeColorMeta");
      if (meta) meta.content = th === "dark" ? "#1a2933" : "#0068b8";
      const logo = document.getElementById("footerLogo");
      if (logo) logo.src = th === "dark" ? "mrzahi-logo-full-dark.png?v=2" : "mrzahi-logo-full-light.png?v=2";
      document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️";
      document.getElementById("currentThemeDisplay").textContent = t[l][th === "dark" ? "dark" : "light"];
      document.getElementById("check-light").style.display = th === "light" ? "inline" : "none";
      document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none";
    }

    document.getElementById("langMenuBtn").addEventListener("click", e => {
      e.stopPropagation();
      document.getElementById("langDropdown").classList.toggle("show");
      document.getElementById("themeDropdown").classList.remove("show");
    });
    // زر المظهر يبدل الثيم مباشرة بضغطة واحدة بلا قائمة (طلب المهندس رعد)
    document.getElementById("themeMenuBtn").addEventListener("click", e => {
      e.stopPropagation();
      setTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark");
      document.getElementById("langDropdown").classList.remove("show");
    });
    document.addEventListener("click", () => {
      document.getElementById("langDropdown").classList.remove("show");
      document.getElementById("themeDropdown").classList.remove("show");
    });

    document.querySelectorAll("#langDropdown .menu-dropdown-item").forEach(item => {
      item.addEventListener("click", () => setLang(item.dataset.lang));
    });
    document.querySelectorAll("#themeDropdown .menu-dropdown-item").forEach(item => {
      item.addEventListener("click", () => {
        setTheme(item.dataset.theme);
        document.getElementById("themeDropdown").classList.remove("show");
      });
    });

    document.querySelectorAll("[data-i18n]").forEach(el => {
      const k = el.dataset.i18n;
      if (t[l] && t[l][k]) el.textContent = t[l][k];
    });
    document.getElementById("currentLangDisplay").textContent = langNames[l] || l;
    ["ar","en","fr","ur"].forEach(c => {
      const el = document.getElementById("check-" + c);
      if (el) el.style.display = l === c ? "inline" : "none";
    });
    document.title = (t[l] && t[l].title ? t[l].title : "Plans & Pricing") + " | MrZahi";

    (function() {
      const th = theme();
      document.documentElement.dataset.theme = th;
      const meta = document.getElementById("themeColorMeta");
      if (meta) meta.content = th === "dark" ? "#1a2933" : "#0068b8";
      const logo = document.getElementById("footerLogo");
      if (logo) logo.src = th === "dark" ? "mrzahi-logo-full-dark.png?v=2" : "mrzahi-logo-full-light.png?v=2";
      document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️";
      document.getElementById("currentThemeDisplay").textContent = t[l][th === "dark" ? "dark" : "light"];
      document.getElementById("check-light").style.display = th === "light" ? "inline" : "none";
      document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none";
    })();
