/* migration: نقل مفاتيح التخزين من الاسم القديم الى mrzahi_ مرة واحدة لكل متصفح، فلا يفقد احد لغته ولا ثيمه ولا حسابه المختار */
try{["lang","theme","org","sidebar","dash_tab","bell_seen","chat_seen","cal_mode","cal_zoom","dp_cal","drive_folder","tr"].forEach(function(k){var o=localStorage.getItem("record_"+k);if(o!==null&&localStorage.getItem("mrzahi_"+k)===null){localStorage.setItem("mrzahi_"+k,o);localStorage.removeItem("record_"+k);}});}catch(e){}
const t = {
      ar: {
        title: "شروط الاستخدام",
        intro: "مرحبا بك في منصة MrZahi المتاحة عبر mrzahi.com. تمثل هذه الشروط اتفاقا ملزما بينك وبين منصة MrZahi. باستخدامك للمنصة أو الموقع الإلكتروني فإنك تقر بأنك قد قرأت هذه الشروط وفهمتها ووافقت على الالتزام بها. إذا لم توافق على أي من هذه الشروط، فيرجى عدم استخدام الخدمة.",
        lastUpdated: "تاريخ السريان: 2026-09-03",
        h1: "1. قبول الشروط",
        s1p1: "بالوصول إلى المنصة أو إنشاء حساب أو الانضمام إلى فريق شركة أو استخدام أي من خدماتها، فإنك توافق على هذه الشروط وعلى سياسة الخصوصية التي تشكل جزءا لا يتجزأ منها. وإذا كنت تستخدم المنصة نيابة عن شركة أو جهة، فإنك تقر بأنك مخول بإلزامها بهذه الشروط.",
        s1p2: "تشكل المستندات التالية جزءا لا يتجزأ من هذه الشروط:",
        s1li1: "سياسة الخصوصية",
        s1li1desc: "كيفية جمع بياناتك واستخدامها وحمايتها",
        s1li2: "الباقات والأسعار",
        s1li2desc: "تفاصيل كل باقة وحدودها وسعرها",
        h2: "2. الخدمة",
        s2p1: "MrZahi منصة اشتراك تساعد الشركات على تتبع العقود والتراخيص والتجديدات والمهام والمستحقات، وتشمل الخدمة:",
        s2li1: "استيراد العناصر من ملف Excel مع مطابقة الأعمدة (العنوان، تاريخ الاستحقاق، المسؤول)",
        s2li2: "عرض العناصر في قائمة وتقويم شهري، مع رابط تقويم (ICS) يعمل مع تقويم Apple وGoogle وOutlook",
        s2li3: "تذكيرات قبل مواعيد الاستحقاق عبر البريد الإلكتروني وTelegram وWhatsApp والرسائل النصية (SMS) وفق الباقة",
        s2li4: "حسابات فريق داخل الشركة مع إمكانية دعوة الزملاء وإسناد العناصر إليهم",
        s2p2: "قد نضيف مزايا أو نعدلها أو نوقف بعضها مع مرور الوقت، مع مراعاة ما ورد في بند «التوافر والتغييرات».",
        h3: "3. الحسابات",
        s3p1: "يمكنك تسجيل الدخول عبر Google أو Apple أو رابط يرسل إلى بريدك الإلكتروني أو رمز تحقق يرسل إلى هاتفك. وعند استخدام حسابك تلتزم بما يلي:",
        s3li1: "أن يكون الحساب لشخص واحد فقط، ولا يجوز مشاركته أو نقله إلى غيرك",
        s3li2: "أن تقدم بيانات صحيحة ودقيقة ومحدثة عن نفسك وعن شركتك",
        s3li3: "أن تحافظ على أمان وسائل الدخول إلى حسابك (بريدك الإلكتروني ورقم هاتفك) وأن تبلغنا فورا عن أي استخدام غير مصرح به",
        s3p2: "مالك حساب الشركة هو المسؤول عن الأعضاء الذين يدعوهم، وعن الصلاحيات التي يمنحها لهم، وعن جميع الأنشطة التي تتم من خلال حسابات فريقه.",
        h4: "4. الباقات والفوترة",
        s4p1: "تتوفر المنصة بالباقات التالية، وتفاصيلها الكاملة موضحة في صفحة الباقات والأسعار:",
        s4li1: "الفترة التجريبية: 14 يوما مجانا من تاريخ إنشاء الشركة، بكل المزايا وبلا بطاقة بنكية، ولا تتجدد تلقائيا",
        s4li2: "الشرائح الأربع بحسب نوع الحساب: شخصي 96 <span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span> شهريا أو 960 سنويا، ووثيقة عمل حر 196 شهريا أو 1,960 سنويا",
        s4li3: "منشأة متناهية الصغر 496 <span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span> شهريا أو 4,960 سنويا، ومنشأة كبيرة 696 شهريا أو 6,996 سنويا. السنوي بعشرة أشهر، أي شهران بلا مقابل",
        s4p2: "وتسري على الباقات المدفوعة الأحكام التالية:",
        s4li4: "تفعل الباقات المدفوعة حاليا بالتواصل مع فريق الدعم، وسيتاح الدفع الإلكتروني عبر المنصة لاحقا",
        s4li5: "أسعار الأفراد (شخصي ووثيقة عمل حر) شاملة ضريبة القيمة المضافة، وأسعار المنشآت لا تشمل الضريبة وتضاف عند الشراء",
        s4li6: "تجدد الباقة في نهاية كل فترة اشتراك ما لم تلغ قبل تاريخ التجديد، ويسري الإلغاء مع نهاية الفترة الجارية",
        s4li7: "لا تسترد المبالغ المدفوعة عن الفترات الجزئية أو غير المستخدمة، إلا فيما يوجبه النظام",
        s4li8: "تطبق حدود كل باقة (عدد الأعضاء والعناصر والاستيرادات وقنوات التنبيه) تقنيا، وعند بلوغ الحد يلزم الترقية لإضافة المزيد",
        s4li9: "يجوز لنا تعديل الأسعار مع إشعار مسبق، ولا يسري التعديل على الفترة المدفوعة الجارية",
        h5: "5. الاستخدام المقبول",
        s5p1: "تلتزم عند استخدام المنصة بعدم القيام بما يلي:",
        s5li1: "رفع أو تخزين أي بيانات غير مشروعة أو تنتهك حقوق الغير أو لا تملك صلاحية معالجتها",
        s5li2: "استخدام قنوات التنبيه (البريد الإلكتروني أو Telegram أو WhatsApp أو الرسائل النصية) لإرسال رسائل غير مرغوب فيها أو مضللة، أو إلى أشخاص لم يوافقوا على استقبالها",
        s5li3: "محاولة الهندسة العكسية للمنصة أو فك شفرتها أو الوصول غير المصرح به إلى أنظمتها أو إلى بيانات شركات أخرى",
        s5li4: "تعطيل عمل المنصة أو إثقالها، أو تجاوز حدود الباقة بوسائل آلية أو غير مشروعة",
        s5li5: "إعادة بيع الخدمة أو تأجيرها لأطراف ثالثة دون إذن كتابي مسبق",
        s5p2: "يحق لنا تعليق الحساب أو إنهاؤه عند مخالفة هذه القواعد.",
        h6: "6. التنبيهات والتذكيرات",
        s6p1: "نبذل جهدا معقولا لإرسال التذكيرات في مواعيدها، غير أن التنبيهات تقدم على أساس «أفضل جهد ممكن» ولا نضمن وصولها أو توقيتها. وعليه:",
        s6li1: "تبقى أنت وشركتك المسؤولين عن متابعة المواعيد والوفاء بالالتزامات في وقتها، ولا تعد المنصة بديلا عن المتابعة الذاتية",
        s6li2: "تعتمد قنوات التنبيه على أطراف ثالثة (مزودي البريد الإلكتروني وTelegram وWhatsApp ومشغلي الرسائل النصية) وقد تتأثر بأعطالهم أو سياساتهم أو إعدادات جهازك",
        s6li3: "يجب أن تكون بيانات الاتصال (البريد الإلكتروني ورقم الهاتف) صحيحة ومحدثة لتصلك التنبيهات",
        s6li4: "قد تتطلب بعض القنوات موافقة أو إعدادا مسبقا من جهتك (مثل بدء المحادثة مع بوت Telegram أو الموافقة على استقبال رسائل WhatsApp)",
        h7: "7. ملكية البيانات",
        s7p1: "البيانات التي ترفعها شركتك إلى المنصة (ملفات Excel والعناصر والمواعيد وبيانات الأعضاء) تبقى ملكا لها، ونحن نعالجها فقط بالقدر اللازم لتقديم الخدمة وفق سياسة الخصوصية. تعزل بيانات كل شركة عن غيرها على مستوى قاعدة البيانات، ولا يطلع عليها إلا أعضاء فريقك المخولون.",
        s7p2: "يمكنك تصدير بياناتك في أي وقت من داخل المنصة. وعند حذف الحساب أو انتهاء الاشتراك نحذف البيانات أو نجعلها مجهولة الهوية خلال مدة معقولة، ما لم يوجب النظام الاحتفاظ بها.",
        h8: "8. الملكية الفكرية",
        s8p1: "جميع حقوق الملكية الفكرية المتعلقة بمنصة MrZahi محفوظة، وتشمل العلامة التجارية والشعار وتصميم الواجهات والشفرة البرمجية والمحتوى. تمنح لك رخصة محدودة وغير حصرية وغير قابلة للنقل لاستخدام المنصة وفق هذه الشروط، ولا يجوز نسخ أي جزء من المنصة أو إعادة إنتاجه أو توزيعه دون إذن كتابي مسبق.",
        h9: "9. التوافر والتغييرات",
        s9p1: "نسعى إلى إبقاء المنصة متاحة على مدار الساعة، لكننا لا نضمن التشغيل دون انقطاع. قد تتوقف الخدمة مؤقتا بسبب الصيانة أو التحديثات أو أعطال لدى مزودي الاستضافة والبنية التحتية أو ظروف خارجة عن سيطرتنا. كما يجوز لنا تعديل المنصة أو مزاياها أو إيقاف أي منها، وسنخطرك مسبقا بقدر الإمكان عند التغييرات الجوهرية التي تؤثر في استخدامك.",
        h10: "10. الإنهاء",
        s10p1: "يمكنك إغلاق حسابك أو إلغاء اشتراكك في أي وقت من إعدادات الحساب أو بالتواصل مع الدعم. كما يحق لنا تعليق حسابك أو إنهاؤه في الحالات التالية:",
        s10li1: "مخالفة هذه الشروط أو سياسة الخصوصية",
        s10li2: "عدم سداد رسوم الاشتراك المستحقة بعد إشعارك",
        s10li3: "استخدام المنصة بطريقة تضر بها أو بمستخدميها أو بالغير",
        s10li4: "عدم النشاط لفترة طويلة بعد انتهاء الفترة التجريبية أو الاشتراك، وبعد إشعار مسبق",
        s10p2: "عند الإنهاء يتوقف وصولك إلى المنصة، وننصحك بتصدير بياناتك قبل ذلك. وتبقى الالتزامات المالية المستحقة قبل تاريخ الإنهاء سارية.",
        h11: "11. حدود المسؤولية",
        s11p1: "تقدم المنصة «كما هي» و«بحسب المتاح» دون أي ضمانات صريحة أو ضمنية بالقدر الذي يسمح به النظام. ولا نتحمل المسؤولية عن:",
        s11li1: "أي خسارة أو ضرر ناتج عن فوات موعد استحقاق أو تجديد أو التزام تعاقدي، سواء وصل التذكير أم لم يصل",
        s11li2: "الأضرار غير المباشرة أو التبعية أو خسارة الأرباح أو الفرص أو البيانات",
        s11li3: "تصرفات الأطراف الثالثة أو أعطالها، بمن فيهم مزودو الاستضافة وقواعد البيانات وقنوات التنبيه",
        s11li4: "دقة البيانات التي ترفعها أنت أو أعضاء فريقك إلى المنصة",
        s11p2: "وفي جميع الأحوال، لا تتجاوز مسؤوليتنا الإجمالية تجاهك مجموع ما دفعته للمنصة خلال 12 شهرا السابقة للمطالبة.",
        h12: "12. القانون الواجب التطبيق",
        s12p1: "تخضع هذه الشروط لأنظمة المملكة العربية السعودية وتفسر وفقا لها. وفي حال نشوء أي نزاع يتعلق بهذه الشروط أو باستخدام المنصة، تختص الجهات القضائية المختصة في المملكة العربية السعودية بالنظر فيه والفصل به.",
        h13: "13. التعديلات",
        s13p1: "يحق لنا تعديل هذه الشروط من وقت إلى آخر. وعند إجراء تعديلات جوهرية سنخطرك عبر المنصة أو البريد الإلكتروني المسجل قبل سريانها، وسنوضح تاريخ السريان. ويعد استمرارك في استخدام المنصة بعد ذلك التاريخ قبولا للشروط المعدلة.",
        h14: "14. التواصل",
        s14p1: "لأي استفسار بخصوص هذه الشروط أو خدمات المنصة، يمكنك التواصل معنا عبر:",
        s14li1: "البريد الإلكتروني:",
        backBtn: "العودة للرئيسية",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        deleteAccountLink: "حذف الحساب",
        loginLink: "تسجيل الدخول",
        accountLabel: "الحساب",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        title: "Terms of Use",
        intro: "Welcome to MrZahi, available at mrzahi.com. These terms constitute a binding agreement between you and the MrZahi platform. By using the platform or the website, you acknowledge that you have read, understood, and agree to be bound by these terms. If you do not agree to any of these terms, please do not use the service.",
        lastUpdated: "Effective date: 2026-09-03",
        h1: "1. Acceptance of the Terms",
        s1p1: "By accessing the platform, creating an account, joining a company team, or using any of its services, you agree to these terms and to the Privacy Policy, which forms an integral part of them. If you use the platform on behalf of a company or organization, you confirm that you are authorized to bind it to these terms.",
        s1p2: "The following documents form an integral part of these terms:",
        s1li1: "Privacy Policy",
        s1li1desc: "How we collect, use, and protect your data",
        s1li2: "Plans & Pricing",
        s1li2desc: "Details of each plan, its limits, and its price",
        h2: "2. The Service",
        s2p1: "MrZahi is a subscription platform that helps companies track contracts, licenses, renewals, tasks, and dues. The service includes:",
        s2li1: "Importing items from an Excel file, with column mapping (title, due date, assignee)",
        s2li2: "Displaying items in a list and a monthly calendar, with a calendar feed (ICS) that works with Apple, Google, and Outlook calendars",
        s2li3: "Reminders before due dates via email, Telegram, WhatsApp, and SMS, according to your plan",
        s2li4: "Team accounts within the company, with the ability to invite colleagues and assign items to them",
        s2p2: "We may add, modify, or discontinue features over time, subject to the \"Availability and Changes\" section.",
        h3: "3. Accounts",
        s3p1: "You can sign in with Google, Apple, a magic link sent to your email, or a one-time code sent to your phone. When using your account, you agree to the following:",
        s3li1: "The account is for one person only and may not be shared with or transferred to anyone else",
        s3li2: "You will provide accurate, correct, and up-to-date information about yourself and your company",
        s3li3: "You will keep your sign-in methods (your email address and phone number) secure and notify us immediately of any unauthorized use",
        s3p2: "The company account owner is responsible for the members they invite, the permissions they grant, and all activity carried out through their team's accounts.",
        h4: "4. Plans and Billing",
        s4p1: "The platform is offered under the following plans; full details are available on the Plans & Pricing page:",
        s4li1: "Trial period: 14 days free from the date the company is created, with every feature and no credit card; it does not renew automatically",
        s4li2: "Four tiers by account type: Personal 96 <span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span> a month or 960 a year, Freelance Permit 196 a month or 1,960 a year",
        s4li3: "Micro Enterprise 496 <span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span> a month or 4,960 a year, Large Enterprise 696 a month or 6,996 a year. The yearly price is ten months — two months free",
        s4p2: "The following terms apply to paid plans:",
        s4li4: "Paid plans are currently activated by contacting the support team; online payment through the platform will be available later",
        s4li5: "Individual plan prices (Personal, Freelance Permit) include VAT; enterprise plan prices exclude VAT, which is added at checkout",
        s4li6: "A plan renews at the end of each subscription period unless cancelled before the renewal date; cancellation takes effect at the end of the current period",
        s4li7: "Amounts paid for partial or unused periods are non-refundable, except as required by law",
        s4li8: "Each plan's limits (members, items, imports, and notification channels) are enforced technically; once a limit is reached, an upgrade is required to add more",
        s4li9: "We may change prices with prior notice; a change does not apply to the current paid period",
        h5: "5. Acceptable Use",
        s5p1: "When using the platform, you agree not to:",
        s5li1: "Upload or store any data that is unlawful, infringes the rights of others, or that you are not authorized to process",
        s5li2: "Use the notification channels (email, Telegram, WhatsApp, or SMS) to send unsolicited or misleading messages, or messages to people who have not agreed to receive them",
        s5li3: "Reverse engineer or decompile the platform, or attempt unauthorized access to its systems or to other companies' data",
        s5li4: "Disrupt or overload the platform, or circumvent plan limits by automated or unlawful means",
        s5li5: "Resell or rent the service to third parties without prior written permission",
        s5p2: "We may suspend or terminate an account that violates these rules.",
        h6: "6. Notifications and Reminders",
        s6p1: "We make reasonable efforts to send reminders on time; however, notifications are provided on a \"best-effort\" basis and we do not guarantee their delivery or timing. Accordingly:",
        s6li1: "You and your company remain responsible for monitoring deadlines and meeting obligations on time; the platform is not a substitute for your own follow-up",
        s6li2: "Notification channels depend on third parties (email providers, Telegram, WhatsApp, and SMS carriers) and may be affected by their outages, their policies, or your device settings",
        s6li3: "Your contact details (email address and phone number) must be correct and up to date for notifications to reach you",
        s6li4: "Some channels may require your prior consent or setup (such as starting a conversation with the Telegram bot or agreeing to receive WhatsApp messages)",
        h7: "7. Data Ownership",
        s7p1: "The data your company uploads to the platform (Excel files, items, dates, and member details) remains its property. We process it only to the extent necessary to provide the service, in accordance with the Privacy Policy. Each company's data is isolated from others at the database level and is accessible only to your authorized team members.",
        s7p2: "You can export your data at any time from within the platform. When an account is deleted or a subscription ends, we delete or anonymize the data within a reasonable period, unless the law requires us to retain it.",
        h8: "8. Intellectual Property",
        s8p1: "All intellectual property rights related to the MrZahi platform are reserved, including the trademark, logo, interface design, source code, and content. You are granted a limited, non-exclusive, non-transferable license to use the platform in accordance with these terms. No part of the platform may be copied, reproduced, or distributed without prior written permission.",
        h9: "9. Availability and Changes",
        s9p1: "We aim to keep the platform available around the clock, but we do not guarantee uninterrupted operation. The service may be temporarily unavailable due to maintenance, updates, outages at our hosting and infrastructure providers, or circumstances beyond our control. We may also modify the platform or its features, or discontinue any of them; where possible, we will notify you in advance of material changes that affect your use.",
        h10: "10. Termination",
        s10p1: "You may close your account or cancel your subscription at any time from your account settings or by contacting support. We may also suspend or terminate your account in the following cases:",
        s10li1: "Violation of these terms or the Privacy Policy",
        s10li2: "Failure to pay outstanding subscription fees after being notified",
        s10li3: "Using the platform in a way that harms it, its users, or others",
        s10li4: "Extended inactivity after the trial period or subscription has ended, following prior notice",
        s10p2: "Upon termination, your access to the platform ends; we recommend exporting your data beforehand. Financial obligations incurred before the termination date remain in effect.",
        h11: "11. Limitation of Liability",
        s11p1: "The platform is provided \"as is\" and \"as available\", without any express or implied warranties, to the extent permitted by law. We are not liable for:",
        s11li1: "Any loss or damage resulting from a missed due date, renewal, or contractual obligation, whether or not a reminder was delivered",
        s11li2: "Indirect or consequential damages, or loss of profits, opportunities, or data",
        s11li3: "The actions or failures of third parties, including hosting, database, and notification channel providers",
        s11li4: "The accuracy of the data uploaded to the platform by you or your team members",
        s11p2: "In all cases, our total liability to you shall not exceed the total amount you paid to the platform during the 12 months preceding the claim.",
        h12: "12. Governing Law",
        s12p1: "These terms are governed by and construed in accordance with the laws of the Kingdom of Saudi Arabia. In the event of any dispute arising from these terms or the use of the platform, the competent judicial authorities in the Kingdom of Saudi Arabia shall have jurisdiction.",
        h13: "13. Amendments",
        s13p1: "We may amend these terms from time to time. In the event of material changes, we will notify you via the platform or your registered email before they take effect, and we will state the effective date. Your continued use of the platform after that date constitutes acceptance of the amended terms.",
        h14: "14. Contact Us",
        s14p1: "For any questions regarding these terms or the platform's services, you can reach us through:",
        s14li1: "Email:",
        backBtn: "Back to Home",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        deleteAccountLink: "Delete account",
        loginLink: "Sign in",
        accountLabel: "Account",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        title: "Conditions d'utilisation",
        intro: "Bienvenue sur la plateforme MrZahi, accessible sur mrzahi.com. Les présentes conditions constituent un accord contraignant entre vous et la plateforme MrZahi. En utilisant la plateforme ou le site web, vous reconnaissez avoir lu et compris ces conditions et acceptez de vous y conformer. Si vous n'acceptez pas l'une de ces conditions, veuillez ne pas utiliser le service.",
        lastUpdated: "Date d'entrée en vigueur : 2026-09-03",
        h1: "1. Acceptation des conditions",
        s1p1: "En accédant à la plateforme, en créant un compte, en rejoignant l'équipe d'une entreprise ou en utilisant l'un de ses services, vous acceptez les présentes conditions ainsi que la politique de confidentialité, qui en fait partie intégrante. Si vous utilisez la plateforme au nom d'une entreprise ou d'une organisation, vous confirmez être habilité à l'engager par ces conditions.",
        s1p2: "Les documents suivants font partie intégrante des présentes conditions :",
        s1li1: "Politique de confidentialité",
        s1li1desc: "Comment nous collectons, utilisons et protégeons vos données",
        s1li2: "Forfaits et tarifs",
        s1li2desc: "Détails de chaque forfait, ses limites et son prix",
        h2: "2. Le service",
        s2p1: "MrZahi est une plateforme par abonnement qui aide les entreprises à suivre leurs contrats, licences, renouvellements, tâches et échéances. Le service comprend :",
        s2li1: "L'importation d'éléments depuis un fichier Excel, avec correspondance des colonnes (titre, date d'échéance, responsable)",
        s2li2: "L'affichage des éléments dans une liste et un calendrier mensuel, avec un flux de calendrier (ICS) compatible avec les calendriers Apple, Google et Outlook",
        s2li3: "Des rappels avant les dates d'échéance par e-mail, Telegram, WhatsApp et SMS, selon votre forfait",
        s2li4: "Des comptes d'équipe au sein de l'entreprise, avec la possibilité d'inviter des collègues et de leur attribuer des éléments",
        s2p2: "Nous pouvons ajouter, modifier ou retirer des fonctionnalités au fil du temps, sous réserve de la section « Disponibilité et modifications ».",
        h3: "3. Comptes",
        s3p1: "Vous pouvez vous connecter avec Google, Apple, un lien magique envoyé par e-mail ou un code à usage unique envoyé sur votre téléphone. En utilisant votre compte, vous vous engagez à ce qui suit :",
        s3li1: "Le compte est destiné à une seule personne et ne peut être partagé ni transféré à un tiers",
        s3li2: "Vous fournissez des informations exactes, correctes et à jour sur vous-même et sur votre entreprise",
        s3li3: "Vous protégez vos moyens de connexion (votre adresse e-mail et votre numéro de téléphone) et nous informez immédiatement de toute utilisation non autorisée",
        s3p2: "Le propriétaire du compte de l'entreprise est responsable des membres qu'il invite, des autorisations qu'il leur accorde et de toute activité effectuée via les comptes de son équipe.",
        h4: "4. Forfaits et facturation",
        s4p1: "La plateforme est proposée selon les forfaits suivants ; les détails complets figurent sur la page Forfaits et tarifs :",
        s4li1: "Période d'essai : 14 jours gratuits à compter de la création de l'entreprise, avec toutes les fonctionnalités et sans carte bancaire ; elle ne se renouvelle pas automatiquement",
        s4li2: "Quatre formules selon le type de compte : Personnel 96 <span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span> par mois ou 960 par an, Permis freelance 196 par mois ou 1 960 par an",
        s4li3: "Micro-entreprise 496 <span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span> par mois ou 4 960 par an, Grande entreprise 696 par mois ou 6 996 par an. Le tarif annuel vaut dix mois — deux mois offerts",
        s4p2: "Les conditions suivantes s'appliquent aux forfaits payants :",
        s4li4: "Les forfaits payants sont actuellement activés en contactant l'équipe d'assistance ; le paiement en ligne via la plateforme sera disponible ultérieurement",
        s4li5: "Les tarifs des forfaits individuels (Personnel, Permis freelance) sont TVA incluse ; les tarifs des forfaits entreprise sont hors TVA, ajoutée au paiement",
        s4li6: "Un forfait se renouvelle à la fin de chaque période d'abonnement sauf résiliation avant la date de renouvellement ; la résiliation prend effet à la fin de la période en cours",
        s4li7: "Les montants payés pour des périodes partielles ou non utilisées ne sont pas remboursables, sauf si la loi l'exige",
        s4li8: "Les limites de chaque forfait (membres, éléments, importations et canaux de notification) sont appliquées techniquement ; une fois une limite atteinte, une mise à niveau est nécessaire pour en ajouter davantage",
        s4li9: "Nous pouvons modifier les prix moyennant un préavis ; une modification ne s'applique pas à la période payée en cours",
        h5: "5. Utilisation acceptable",
        s5p1: "En utilisant la plateforme, vous vous engagez à ne pas :",
        s5li1: "Téléverser ou stocker des données illicites, portant atteinte aux droits d'autrui ou que vous n'êtes pas autorisé à traiter",
        s5li2: "Utiliser les canaux de notification (e-mail, Telegram, WhatsApp ou SMS) pour envoyer des messages non sollicités ou trompeurs, ou des messages à des personnes n'ayant pas consenti à les recevoir",
        s5li3: "Procéder à l'ingénierie inverse ou à la décompilation de la plateforme, ni tenter d'accéder sans autorisation à ses systèmes ou aux données d'autres entreprises",
        s5li4: "Perturber ou surcharger la plateforme, ni contourner les limites des forfaits par des moyens automatisés ou illicites",
        s5li5: "Revendre ou louer le service à des tiers sans autorisation écrite préalable",
        s5p2: "Nous pouvons suspendre ou résilier tout compte qui enfreint ces règles.",
        h6: "6. Notifications et rappels",
        s6p1: "Nous faisons des efforts raisonnables pour envoyer les rappels à temps ; toutefois, les notifications sont fournies selon le principe du « meilleur effort » et nous ne garantissons ni leur remise ni leur délai. En conséquence :",
        s6li1: "Vous et votre entreprise restez responsables du suivi des échéances et du respect de vos obligations dans les délais ; la plateforme ne remplace pas votre propre suivi",
        s6li2: "Les canaux de notification dépendent de tiers (fournisseurs de messagerie, Telegram, WhatsApp et opérateurs SMS) et peuvent être affectés par leurs pannes, leurs politiques ou les réglages de votre appareil",
        s6li3: "Vos coordonnées (adresse e-mail et numéro de téléphone) doivent être correctes et à jour pour que les notifications vous parviennent",
        s6li4: "Certains canaux peuvent exiger votre consentement ou une configuration préalable (par exemple démarrer une conversation avec le bot Telegram ou accepter de recevoir des messages WhatsApp)",
        h7: "7. Propriété des données",
        s7p1: "Les données que votre entreprise téléverse sur la plateforme (fichiers Excel, éléments, dates et informations sur les membres) restent sa propriété. Nous les traitons uniquement dans la mesure nécessaire à la fourniture du service, conformément à la politique de confidentialité. Les données de chaque entreprise sont isolées des autres au niveau de la base de données et ne sont accessibles qu'aux membres autorisés de votre équipe.",
        s7p2: "Vous pouvez exporter vos données à tout moment depuis la plateforme. Lors de la suppression d'un compte ou de la fin d'un abonnement, nous supprimons ou anonymisons les données dans un délai raisonnable, sauf si la loi nous impose de les conserver.",
        h8: "8. Propriété intellectuelle",
        s8p1: "Tous les droits de propriété intellectuelle relatifs à la plateforme MrZahi sont réservés, y compris la marque, le logo, la conception des interfaces, le code source et le contenu. Une licence limitée, non exclusive et non transférable vous est accordée pour utiliser la plateforme conformément aux présentes conditions. Aucune partie de la plateforme ne peut être copiée, reproduite ou distribuée sans autorisation écrite préalable.",
        h9: "9. Disponibilité et modifications",
        s9p1: "Nous nous efforçons de maintenir la plateforme disponible en permanence, sans toutefois garantir un fonctionnement ininterrompu. Le service peut être temporairement indisponible en raison d'opérations de maintenance, de mises à jour, de pannes chez nos fournisseurs d'hébergement et d'infrastructure ou de circonstances indépendantes de notre volonté. Nous pouvons également modifier la plateforme ou ses fonctionnalités, ou en retirer certaines ; dans la mesure du possible, nous vous informerons à l'avance des modifications importantes affectant votre utilisation.",
        h10: "10. Résiliation",
        s10p1: "Vous pouvez fermer votre compte ou annuler votre abonnement à tout moment depuis les paramètres de votre compte ou en contactant l'assistance. Nous pouvons également suspendre ou résilier votre compte dans les cas suivants :",
        s10li1: "Violation des présentes conditions ou de la politique de confidentialité",
        s10li2: "Non-paiement des frais d'abonnement dus après notification",
        s10li3: "Utilisation de la plateforme d'une manière qui lui nuit, ou qui nuit à ses utilisateurs ou à des tiers",
        s10li4: "Inactivité prolongée après la fin de la période d'essai ou de l'abonnement, après préavis",
        s10p2: "En cas de résiliation, votre accès à la plateforme prend fin ; nous vous recommandons d'exporter vos données au préalable. Les obligations financières nées avant la date de résiliation restent applicables.",
        h11: "11. Limitation de responsabilité",
        s11p1: "La plateforme est fournie « telle quelle » et « selon disponibilité », sans aucune garantie expresse ou implicite, dans la mesure permise par la loi. Nous ne sommes pas responsables :",
        s11li1: "De toute perte ou de tout dommage résultant d'une échéance, d'un renouvellement ou d'une obligation contractuelle manqués, qu'un rappel ait été remis ou non",
        s11li2: "Des dommages indirects ou consécutifs, ni des pertes de profits, d'opportunités ou de données",
        s11li3: "Des actes ou défaillances de tiers, y compris les fournisseurs d'hébergement, de base de données et de canaux de notification",
        s11li4: "De l'exactitude des données téléversées sur la plateforme par vous ou les membres de votre équipe",
        s11p2: "En tout état de cause, notre responsabilité totale envers vous ne saurait excéder le montant total que vous avez versé à la plateforme au cours des 12 mois précédant la réclamation.",
        h12: "12. Droit applicable",
        s12p1: "Les présentes conditions sont régies et interprétées conformément aux lois du Royaume d'Arabie saoudite. En cas de litige relatif à ces conditions ou à l'utilisation de la plateforme, les autorités judiciaires compétentes du Royaume d'Arabie saoudite sont seules compétentes.",
        h13: "13. Modifications",
        s13p1: "Nous pouvons modifier les présentes conditions de temps à autre. En cas de modifications importantes, nous vous en informerons via la plateforme ou votre adresse e-mail enregistrée avant leur entrée en vigueur, en précisant la date d'effet. Votre utilisation continue de la plateforme après cette date vaut acceptation des conditions modifiées.",
        h14: "14. Contact",
        s14p1: "Pour toute question concernant les présentes conditions ou les services de la plateforme, vous pouvez nous joindre via :",
        s14li1: "E-mail :",
        backBtn: "Retour à l'accueil",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        deleteAccountLink: "Supprimer le compte",
        loginLink: "Connexion",
        accountLabel: "Compte",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        title: "استعمال کی شرائط",
        intro: "MrZahi پلیٹ فارم میں خوش آمدید، جو mrzahi.com پر دستیاب ہے۔ یہ شرائط آپ اور MrZahi پلیٹ فارم کے درمیان ایک پابند معاہدہ ہیں۔ پلیٹ فارم یا ویب سائٹ استعمال کرکے آپ تسلیم کرتے ہیں کہ آپ نے یہ شرائط پڑھ اور سمجھ لی ہیں اور ان کی پابندی پر متفق ہیں۔ اگر آپ ان میں سے کسی شرط سے متفق نہیں ہیں تو براہ کرم سروس استعمال نہ کریں۔",
        lastUpdated: "نفاذ کی تاریخ: 2026-09-03",
        h1: "1. شرائط کی قبولیت",
        s1p1: "پلیٹ فارم تک رسائی، اکاؤنٹ بنانے، کسی کمپنی کی ٹیم میں شامل ہونے یا اس کی کوئی بھی سروس استعمال کرنے سے آپ ان شرائط اور رازداری کی پالیسی سے متفق ہوتے ہیں، جو ان شرائط کا لازمی حصہ ہے۔ اگر آپ کسی کمپنی یا ادارے کی جانب سے پلیٹ فارم استعمال کر رہے ہیں تو آپ تصدیق کرتے ہیں کہ آپ اسے ان شرائط کا پابند بنانے کے مجاز ہیں۔",
        s1p2: "درج ذیل دستاویزات ان شرائط کا لازمی حصہ ہیں:",
        s1li1: "رازداری کی پالیسی",
        s1li1desc: "ہم آپ کا ڈیٹا کیسے جمع، استعمال اور محفوظ کرتے ہیں",
        s1li2: "پلانز اور قیمتیں",
        s1li2desc: "ہر پلان کی تفصیلات، اس کی حدود اور قیمت",
        h2: "2. سروس",
        s2p1: "MrZahi ایک سبسکرپشن پلیٹ فارم ہے جو کمپنیوں کو معاہدوں، لائسنسوں، تجدیدات، کاموں اور واجبات کی نگرانی میں مدد دیتا ہے۔ سروس میں شامل ہے:",
        s2li1: "ایکسل فائل سے آئٹمز درآمد کرنا، کالمز کی مطابقت کے ساتھ (عنوان، آخری تاریخ، ذمہ دار)",
        s2li2: "آئٹمز کو فہرست اور ماہانہ کیلنڈر میں دکھانا، کیلنڈر فیڈ (ICS) کے ساتھ جو Apple، Google اور Outlook کیلنڈرز کے ساتھ کام کرتی ہے",
        s2li3: "آپ کے پلان کے مطابق آخری تاریخوں سے پہلے ای میل، ٹیلیگرام، واٹس ایپ اور SMS کے ذریعے یاد دہانیاں",
        s2li4: "کمپنی کے اندر ٹیم اکاؤنٹس، ساتھیوں کو مدعو کرنے اور انہیں آئٹمز تفویض کرنے کی سہولت کے ساتھ",
        s2p2: "ہم وقت کے ساتھ خصوصیات شامل، تبدیل یا بند کر سکتے ہیں، «دستیابی اور تبدیلیاں» کے سیکشن کے تابع۔",
        h3: "3. اکاؤنٹس",
        s3p1: "آپ Google، Apple، ای میل پر بھیجے گئے میجک لنک یا اپنے فون پر بھیجے گئے یک بارگی کوڈ کے ذریعے سائن ان کر سکتے ہیں۔ اپنا اکاؤنٹ استعمال کرتے وقت آپ درج ذیل کی پابندی کرتے ہیں:",
        s3li1: "اکاؤنٹ صرف ایک شخص کے لیے ہے اور اسے کسی اور کے ساتھ شیئر یا منتقل نہیں کیا جا سکتا",
        s3li2: "آپ اپنے اور اپنی کمپنی کے بارے میں درست، صحیح اور تازہ ترین معلومات فراہم کریں گے",
        s3li3: "آپ اپنے سائن ان کے ذرائع (اپنا ای میل ایڈریس اور فون نمبر) محفوظ رکھیں گے اور کسی بھی غیر مجاز استعمال کی فورا اطلاع دیں گے",
        s3p2: "کمپنی کے اکاؤنٹ کا مالک ان ارکان کا ذمہ دار ہے جنہیں وہ مدعو کرتا ہے، ان اجازتوں کا جو وہ انہیں دیتا ہے، اور اپنی ٹیم کے اکاؤنٹس کے ذریعے ہونے والی تمام سرگرمیوں کا۔",
        h4: "4. پلانز اور بلنگ",
        s4p1: "پلیٹ فارم درج ذیل پلانز کے تحت پیش کیا جاتا ہے؛ مکمل تفصیلات پلانز اور قیمتیں کے صفحے پر موجود ہیں:",
        s4li1: "آزمائشی مدت: کمپنی بنانے کی تاریخ سے 14 دن مفت، تمام خصوصیات کے ساتھ اور کریڈٹ کارڈ کے بغیر؛ یہ خود بخود تجدید نہیں ہوتی",
        s4li2: "اکاؤنٹ کی قسم کے مطابق چار درجے: ذاتی 96 <span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span> ماہانہ یا 960 سالانہ، فری لانس پرمٹ 196 ماہانہ یا 1,960 سالانہ",
        s4li3: "مائیکرو ادارہ 496 <span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span> ماہانہ یا 4,960 سالانہ، بڑا ادارہ 696 ماہانہ یا 6,996 سالانہ۔ سالانہ قیمت دس ماہ کے برابر — دو مہینے مفت",
        s4p2: "ادا شدہ پلانز پر درج ذیل شرائط لاگو ہوتی ہیں:",
        s4li4: "ادا شدہ پلانز فی الحال سپورٹ ٹیم سے رابطہ کرکے فعال کیے جاتے ہیں؛ پلیٹ فارم کے ذریعے آن لائن ادائیگی بعد میں دستیاب ہوگی",
        s4li5: "انفرادی پلانز (ذاتی، فری لانس پرمٹ) کی قیمتیں ویٹ سمیت ہیں؛ اداروں کے پلانز کی قیمتوں میں ویٹ شامل نہیں اور خریداری پر شامل ہوتا ہے",
        s4li6: "پلان ہر سبسکرپشن مدت کے اختتام پر تجدید ہوتا ہے جب تک کہ تجدید کی تاریخ سے پہلے منسوخ نہ کیا جائے؛ منسوخی موجودہ مدت کے اختتام پر مؤثر ہوتی ہے",
        s4li7: "جزوی یا غیر استعمال شدہ مدتوں کے لیے ادا کی گئی رقوم واپس نہیں کی جاتیں، سوائے اس کے کہ قانون تقاضا کرے",
        s4li8: "ہر پلان کی حدود (ارکان، آئٹمز، درآمدات اور نوٹیفکیشن چینلز) تکنیکی طور پر نافذ کی جاتی ہیں؛ حد تک پہنچنے پر مزید شامل کرنے کے لیے اپ گریڈ ضروری ہے",
        s4li9: "ہم پیشگی اطلاع کے ساتھ قیمتیں تبدیل کر سکتے ہیں؛ تبدیلی موجودہ ادا شدہ مدت پر لاگو نہیں ہوتی",
        h5: "5. قابل قبول استعمال",
        s5p1: "پلیٹ فارم استعمال کرتے وقت آپ درج ذیل نہ کرنے کا عہد کرتے ہیں:",
        s5li1: "ایسا ڈیٹا اپ لوڈ یا محفوظ کرنا جو غیر قانونی ہو، دوسروں کے حقوق کی خلاف ورزی کرے، یا جس پر کارروائی کے آپ مجاز نہ ہوں",
        s5li2: "نوٹیفکیشن چینلز (ای میل، ٹیلیگرام، واٹس ایپ یا SMS) کو غیر مطلوبہ یا گمراہ کن پیغامات بھیجنے، یا ایسے افراد کو پیغامات بھیجنے کے لیے استعمال کرنا جنہوں نے انہیں وصول کرنے پر رضامندی نہیں دی",
        s5li3: "پلیٹ فارم کی ریورس انجینئرنگ یا ڈی کمپائلنگ، یا اس کے سسٹمز یا دیگر کمپنیوں کے ڈیٹا تک غیر مجاز رسائی کی کوشش",
        s5li4: "پلیٹ فارم میں خلل ڈالنا یا اس پر زائد بوجھ ڈالنا، یا خودکار یا غیر قانونی ذرائع سے پلان کی حدود کو نظرانداز کرنا",
        s5li5: "پیشگی تحریری اجازت کے بغیر سروس کو تیسرے فریق کو دوبارہ فروخت یا کرائے پر دینا",
        s5p2: "ہم ان قواعد کی خلاف ورزی کرنے والے اکاؤنٹ کو معطل یا ختم کر سکتے ہیں۔",
        h6: "6. نوٹیفکیشنز اور یاد دہانیاں",
        s6p1: "ہم یاد دہانیاں بروقت بھیجنے کی معقول کوشش کرتے ہیں؛ تاہم نوٹیفکیشنز «بہترین کوشش» کی بنیاد پر فراہم کی جاتی ہیں اور ہم ان کی ترسیل یا وقت کی ضمانت نہیں دیتے۔ لہذا:",
        s6li1: "آپ اور آپ کی کمپنی آخری تاریخوں کی نگرانی اور ذمہ داریوں کی بروقت تکمیل کے ذمہ دار رہتے ہیں؛ پلیٹ فارم آپ کی اپنی نگرانی کا متبادل نہیں ہے",
        s6li2: "نوٹیفکیشن چینلز تیسرے فریق (ای میل فراہم کنندگان، ٹیلیگرام، واٹس ایپ اور SMS آپریٹرز) پر منحصر ہیں اور ان کی خرابیوں، پالیسیوں یا آپ کے آلے کی ترتیبات سے متاثر ہو سکتے ہیں",
        s6li3: "نوٹیفکیشنز آپ تک پہنچنے کے لیے آپ کی رابطہ معلومات (ای میل ایڈریس اور فون نمبر) درست اور تازہ ترین ہونی چاہئیں",
        s6li4: "کچھ چینلز کے لیے آپ کی پیشگی رضامندی یا سیٹ اپ درکار ہو سکتا ہے (جیسے ٹیلیگرام بوٹ کے ساتھ گفتگو شروع کرنا یا واٹس ایپ پیغامات وصول کرنے پر رضامندی دینا)",
        h7: "7. ڈیٹا کی ملکیت",
        s7p1: "آپ کی کمپنی جو ڈیٹا پلیٹ فارم پر اپ لوڈ کرتی ہے (ایکسل فائلیں، آئٹمز، تاریخیں اور ارکان کی تفصیلات) اس کی ملکیت رہتا ہے۔ ہم اس پر صرف اتنی کارروائی کرتے ہیں جتنی سروس فراہم کرنے کے لیے ضروری ہو، رازداری کی پالیسی کے مطابق۔ ہر کمپنی کا ڈیٹا ڈیٹابیس کی سطح پر دوسروں سے الگ رکھا جاتا ہے اور صرف آپ کی ٹیم کے مجاز ارکان ہی اس تک رسائی رکھتے ہیں۔",
        s7p2: "آپ پلیٹ فارم کے اندر سے کسی بھی وقت اپنا ڈیٹا برآمد کر سکتے ہیں۔ اکاؤنٹ حذف ہونے یا سبسکرپشن ختم ہونے پر ہم معقول مدت کے اندر ڈیٹا حذف یا گمنام کر دیتے ہیں، سوائے اس کے کہ قانون ہمیں اسے محفوظ رکھنے کا پابند کرے۔",
        h8: "8. دانشورانہ ملکیت",
        s8p1: "MrZahi پلیٹ فارم سے متعلق تمام دانشورانہ ملکیت کے حقوق محفوظ ہیں، بشمول ٹریڈ مارک، لوگو، انٹرفیس ڈیزائن، سورس کوڈ اور مواد۔ آپ کو ان شرائط کے مطابق پلیٹ فارم استعمال کرنے کے لیے محدود، غیر خصوصی اور ناقابل منتقلی لائسنس دیا جاتا ہے۔ پیشگی تحریری اجازت کے بغیر پلیٹ فارم کا کوئی حصہ نقل، دوبارہ تیار یا تقسیم نہیں کیا جا سکتا۔",
        h9: "9. دستیابی اور تبدیلیاں",
        s9p1: "ہم پلیٹ فارم کو ہر وقت دستیاب رکھنے کی کوشش کرتے ہیں، لیکن بلا تعطل کام کی ضمانت نہیں دیتے۔ دیکھ بھال، اپ ڈیٹس، ہماری ہوسٹنگ اور انفراسٹرکچر فراہم کنندگان کی خرابیوں یا ہمارے قابو سے باہر حالات کی وجہ سے سروس عارضی طور پر دستیاب نہیں ہو سکتی۔ ہم پلیٹ فارم یا اس کی خصوصیات میں تبدیلی بھی کر سکتے ہیں یا ان میں سے کسی کو بند کر سکتے ہیں؛ جہاں ممکن ہو، آپ کے استعمال کو متاثر کرنے والی اہم تبدیلیوں سے ہم آپ کو پیشگی آگاہ کریں گے۔",
        h10: "10. اختتام",
        s10p1: "آپ کسی بھی وقت اپنے اکاؤنٹ کی ترتیبات سے یا سپورٹ سے رابطہ کرکے اپنا اکاؤنٹ بند یا سبسکرپشن منسوخ کر سکتے ہیں۔ ہم درج ذیل صورتوں میں آپ کا اکاؤنٹ معطل یا ختم بھی کر سکتے ہیں:",
        s10li1: "ان شرائط یا رازداری کی پالیسی کی خلاف ورزی",
        s10li2: "اطلاع کے بعد واجب الادا سبسکرپشن فیس کی عدم ادائیگی",
        s10li3: "پلیٹ فارم کو اس طرح استعمال کرنا جو اسے، اس کے صارفین یا دوسروں کو نقصان پہنچائے",
        s10li4: "آزمائشی مدت یا سبسکرپشن ختم ہونے کے بعد طویل عرصے تک غیر فعال رہنا، پیشگی اطلاع کے بعد",
        s10p2: "اختتام پر پلیٹ فارم تک آپ کی رسائی ختم ہو جاتی ہے؛ ہم تجویز کرتے ہیں کہ اس سے پہلے اپنا ڈیٹا برآمد کر لیں۔ اختتام کی تاریخ سے پہلے واجب ہونے والی مالی ذمہ داریاں برقرار رہتی ہیں۔",
        h11: "11. ذمہ داری کی حد",
        s11p1: "پلیٹ فارم «جیسا ہے» اور «جیسا دستیاب ہے» کی بنیاد پر فراہم کیا جاتا ہے، قانون کی اجازت کی حد تک کسی واضح یا مضمر ضمانت کے بغیر۔ ہم درج ذیل کے ذمہ دار نہیں ہیں:",
        s11li1: "کسی آخری تاریخ، تجدید یا معاہداتی ذمہ داری کے چھوٹ جانے سے ہونے والا کوئی نقصان، خواہ یاد دہانی پہنچی ہو یا نہ پہنچی ہو",
        s11li2: "بالواسطہ یا نتیجتا ہونے والے نقصانات، یا منافع، مواقع یا ڈیٹا کا نقصان",
        s11li3: "تیسرے فریق کے اقدامات یا ناکامیاں، بشمول ہوسٹنگ، ڈیٹابیس اور نوٹیفکیشن چینل فراہم کنندگان",
        s11li4: "آپ یا آپ کی ٹیم کے ارکان کے پلیٹ فارم پر اپ لوڈ کردہ ڈیٹا کی درستی",
        s11p2: "بہر صورت، آپ کے تئیں ہماری مجموعی ذمہ داری اس کل رقم سے زیادہ نہیں ہوگی جو آپ نے دعوے سے پہلے کے 12 ماہ کے دوران پلیٹ فارم کو ادا کی ہو۔",
        h12: "12. قابل اطلاق قانون",
        s12p1: "یہ شرائط مملکت سعودی عرب کے قوانین کے تابع ہیں اور انہی کے مطابق ان کی تشریح کی جائے گی۔ ان شرائط یا پلیٹ فارم کے استعمال سے متعلق کسی تنازع کی صورت میں مملکت سعودی عرب کے مجاز عدالتی ادارے دائرہ اختیار رکھتے ہیں۔",
        h13: "13. ترامیم",
        s13p1: "ہم وقتا فوقتا ان شرائط میں ترمیم کر سکتے ہیں۔ اہم تبدیلیوں کی صورت میں ہم ان کے نفاذ سے پہلے پلیٹ فارم یا آپ کے رجسٹرڈ ای میل کے ذریعے آپ کو مطلع کریں گے اور نفاذ کی تاریخ بتائیں گے۔ اس تاریخ کے بعد پلیٹ فارم کا آپ کا مسلسل استعمال ترمیم شدہ شرائط کی قبولیت سمجھا جائے گا۔",
        h14: "14. رابطہ",
        s14p1: "ان شرائط یا پلیٹ فارم کی سروسز سے متعلق کسی بھی سوال کے لیے آپ ہم سے رابطہ کر سکتے ہیں:",
        s14li1: "ای میل:",
        backBtn: "واپس ہوم",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        deleteAccountLink: "اکاؤنٹ حذف کریں",
        loginLink: "سائن ان",
        accountLabel: "اکاؤنٹ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };
    const lang = () => localStorage.getItem("mrzahi_lang") || "ar";
    const theme = () => localStorage.getItem("mrzahi_theme") || "dark";
    const langNames = { ar: "العربية", en: "English", fr: "Français", ur: "اردو" };
    let l = lang();
    document.documentElement.lang = l;
    document.documentElement.dir = (l === "ar" || l === "ur") ? "rtl" : "ltr";
    function setLang(c) { localStorage.setItem("mrzahi_lang", c); l = c; document.documentElement.lang = c; document.documentElement.dir = (c === "ar" || c === "ur") ? "rtl" : "ltr"; document.getElementById("currentLangDisplay").textContent = langNames[c] || c; ["ar","en","fr","ur"].forEach(x => { const e = document.getElementById("check-" + x); if (e) e.style.display = c === x ? "inline" : "none"; }); document.querySelectorAll("[data-i18n]").forEach(el => { const k = el.dataset.i18n; if (t[c] && t[c][k]) el.innerHTML = t[c][k]; }); document.getElementById("currentThemeDisplay").textContent = t[c][theme() === "dark" ? "dark" : "light"]; document.title = (t[c]?.title || "Terms of Use") + " | MrZahi"; }
    function setTheme(th) { localStorage.setItem("mrzahi_theme", th); document.documentElement.dataset.theme = th; document.getElementById("themeColorMeta").content = th === "dark" ? "#1a2933" : "#0068b8"; document.getElementById("footerLogo").src = th === "dark" ? "mrzahi-logo-full-dark.png?v=2" : "mrzahi-logo-full-light.png?v=2"; document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️"; document.getElementById("currentThemeDisplay").textContent = t[l][th === "dark" ? "dark" : "light"]; document.getElementById("check-light").style.display = th === "light" ? "inline" : "none"; document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none"; }
    document.getElementById("langMenuBtn").onclick = e => { e.stopPropagation(); document.getElementById("langDropdown").classList.toggle("show"); document.getElementById("themeDropdown").classList.remove("show"); };
    // زر المظهر يبدل الثيم مباشرة بضغطة واحدة بلا قائمة (طلب المهندس رعد)
    document.getElementById("themeMenuBtn").onclick = e => { e.stopPropagation(); setTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark"); document.getElementById("langDropdown").classList.remove("show"); };
    document.addEventListener("click", () => { document.getElementById("langDropdown").classList.remove("show"); document.getElementById("themeDropdown").classList.remove("show"); });
    document.querySelectorAll("#langDropdown .menu-dropdown-item").forEach(item => item.onclick = () => setLang(item.dataset.lang));
    document.querySelectorAll("#themeDropdown .menu-dropdown-item").forEach(item => item.onclick = () => { setTheme(item.dataset.theme); document.getElementById("themeDropdown").classList.remove("show"); });
    document.querySelectorAll("[data-i18n]").forEach(el => { const k = el.dataset.i18n; if (t[l] && t[l][k]) el.innerHTML = t[l][k]; });
    document.getElementById("currentLangDisplay").textContent = langNames[l] || l;
    ["ar","en","fr","ur"].forEach(x => { const e = document.getElementById("check-" + x); if (e) e.style.display = l === x ? "inline" : "none"; });
    document.title = (t[l]?.title || "Terms of Use") + " | MrZahi";
    (function(){ const th = theme(); document.documentElement.dataset.theme = th; document.getElementById("themeColorMeta").content = th === "dark" ? "#1a2933" : "#0068b8"; document.getElementById("footerLogo").src = th === "dark" ? "mrzahi-logo-full-dark.png?v=2" : "mrzahi-logo-full-light.png?v=2"; document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️"; document.getElementById("currentThemeDisplay").textContent = t[l][th === "dark" ? "dark" : "light"]; document.getElementById("check-light").style.display = th === "light" ? "inline" : "none"; document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none"; })();
