/* migration: نقل مفاتيح التخزين من الاسم القديم الى mrzahi_ مرة واحدة لكل متصفح، فلا يفقد احد لغته ولا ثيمه ولا حسابه المختار */
try{["lang","theme","org","sidebar","dash_tab","bell_seen","chat_seen","cal_mode","cal_zoom","dp_cal","drive_folder","tr"].forEach(function(k){var o=localStorage.getItem("record_"+k);if(o!==null&&localStorage.getItem("mrzahi_"+k)===null){localStorage.setItem("mrzahi_"+k,o);localStorage.removeItem("record_"+k);}});}catch(e){}
    const translations = {
      ar: {
        title: "لوحة إدارة المنصة",
        loading: "جاري التحميل...",
        serviceUnavailableTitle: "تعذر الاتصال بالخدمة",
        serviceUnavailableText: "انقطع الاتصال بالخدمة. تحقق من اتصالك ثم أعد المحاولة.",
        deniedTitle: "غير مصرح",
        deniedText: "هذه الصفحة مخصصة لمشرفي المنصة فقط.",
        dashboardBtn: "العودة إلى لوحة التحكم",
        orgsTitle: "الشركات",
        usersTitle: "المستخدمون",
        usersIntro: "كل من سجل في المنصة، وحساباته، وواجهة كل حساب. تغيير الواجهة من بطاقة الشركة.",
        usersCountLabel: "عدد المستخدمين:",
        usersEmpty: "لا يوجد مستخدمون بعد.",
        colPhone: "الجوال",
        colUserNumber: "الرقم القياسي",
        colNameAr: "الاسم الكامل",
        colNameEn: "الاسم بالإنجليزية",
        colOrgs: "الحسابات",
        colAdmin: "مدير منصة",
        colPack: "الواجهة",
        yes: "نعم",
        no: "لا",
        packChanged: "تم تغيير الواجهة.",
        packOnlyPersonal: "الواجهة الشخصية للحسابات الشخصية فقط.",
        packPersonalLocked: "الحساب الشخصي يبقى على الواجهة الشخصية.",
        packUnknown: "واجهة غير معروفة.",
        paTitle: "مديرو المنصة",
        paIntro: "من له صلاحية هذه الصفحة. أضف مديرا ببريده إن كان مسجلا في المنصة.",
        paAddBtn: "إضافة مدير",
        paRemoveBtn: "إزالة",
        paYou: "أنت",
        paSaving: "جاري الحفظ...",
        paAdded: "أضيف {email} كمدير منصة.",
        paRemoved: "أزيلت صلاحية {email}.",
        paNoUser: "لا يوجد مستخدم مسجل بهذا البريد.",
        paCannotSelfRemove: "لا يمكنك إزالة صلاحيتك عن نفسك.",
        paLastAdmin: "لا يمكن ترك المنصة بلا مدير.",
        orgsIntro: "جميع الشركات المسجلة في المنصة مع باقتها الحالية وعدد أعضائها وعناصرها.",
        filterPlaceholder: "ابحث باسم الشركة أو بريد المالك",
        userFilterPh: "ابحث بالاسم أو البريد أو الجوال",
        userPickPh: "اضغط لعرض كل المسجلين، أو اكتب للتصفية",
        colLang: "اللغة", colStore: "مكان الحفظ", colTelegram: "تيليغرام", colLastSeen: "آخر ظهور", colDeleteReq: "طلب حذف الحساب",
        storePlatform: "خادم مستر زاهي (جدة)", storeDrive: "Google Drive الخاص به", linkedYes: "مرتبط", linkedNo: "غير مرتبط",
        paEmailPh: "بريد المستخدم",
        refreshBtn: "تحديث",
        orgsEmpty: "لا توجد شركات مسجلة بعد.",
        colPersonal: "حسابه الشخصي", colMemberOf: "منضم إلى", noPersonal: "لا حساب شخصي بعد", noCompanies: "لا شركات",
        roleOwner: "مالك", roleAdmin: "مشرف", roleMember: "عضو", itemsCountShort: "{n} عنصرا",
        personalOrgsTitle: "الحسابات الشخصية",
        personalOrgsIntro: "مساحة كل شخص لاوراقه ومواعيده، بلا سجل تجاري ولا فريق.",
        personalOrgsEmpty: "لا حسابات شخصية بعد.",
        personalOrgsCountLabel: "عدد الحسابات الشخصية:",
        orgsCountLabel: "عدد الشركات:",
        colOwner: "بريد المالك",
        colPlan: "الباقة الحالية",
        colExpires: "انتهاء الباقة",
        colMembers: "عدد الأعضاء",
        colItems: "عدد العناصر",
        colCreated: "تاريخ الإنشاء",
        noExpiry: "بلا انتهاء",
        expired: "منتهية",
        activateRowBtn: "تفعيل اشتراك",
        activateTitle: "تفعيل اشتراك",
        activateIntro: "اختر الشركة والباقة والمدة ثم اضغط «تفعيل». يسجل الاشتراك باسمك وتحدث باقة الشركة فورا.",
        orgSelectPlaceholder: "اختر الشركة",
        planSelectPlaceholder: "اختر الباقة",
        monthsOne: "شهر واحد",
        monthsTwelve: "12 شهرا",
        notePlaceholder: "ملاحظة (اختياري)",
        activateBtn: "تفعيل",
        activating: "جاري التفعيل...",
        activated: "تم تفعيل الاشتراك بنجاح.",
        activateMissing: "اختر الشركة والباقة أولا.",
        messagesTitle: "رسائل التواصل",
        messagesIntro: "الرسائل الواردة من نموذج التواصل في الموقع، الأحدث أولا.",
        messagesEmpty: "لا توجد رسائل بعد.",
        tgMsgsTitle: "رسائل Telegram",
        tgMsgsIntro: "كل ما يصل بوت Telegram من المستخدمين، الأحدث أولا.",
        tgMsgsEmpty: "لا رسائل بعد.",
        colChat: "المحادثة",
        colUser: "المستخدم",
        colText: "النص",
        colAction: "الإجراء",
        tgAction_none: "—",
        tgAction_reply: "رد البوت",
        tgAction_agent: "رد ذكي",
        tgAction_menu: "قائمة",
        tgAction_add: "تسجيل",
        tgAction_done: "إنجاز",
        tgAction_list: "عرض",
        tgAction_search: "بحث",
        tgAction_import: "استيراد",
        tgAction_linked: "تم الربط",
        tgAction_bad_code: "رمز خاطئ",
        tgMsgsCountLabel: "عدد الرسائل:",
        tgConvsCountLabel: "عدد المحادثات:",
        backBtn: "رجوع",
        messagesCountLabel: "عدد الرسائل:",
        colDate: "التاريخ",
        colName: "الاسم",
        colEmail: "البريد الإلكتروني",
        colStatus: "الحالة",
        requestsTitle: "طلبات الترقية",
        requestsEmpty: "لا توجد طلبات.",
        approveBtn: "موافقة وتفعيل",
        rejectBtn: "رفض",
        monthsLabel: "شهرا",
        orgNameLabel: "الشركة",
        savingReq: "جاري التنفيذ...",
        savedReq: "تم التنفيذ.",
        reqStatus_pending: "قيد المراجعة",
        reqStatus_approved: "مفعل",
        reqStatus_rejected: "مرفوض",
        reqStatus_cancelled: "ملغى",
        noSubject: "بدون موضوع",
        statusNew: "جديدة",
        statusRead: "مقروءة",
        statusReplied: "تم الرد",
        statusClosed: "مغلقة",
        loadError: "تعذر التحميل:",
        genericError: "حدث خطأ، حاول مرة أخرى.",
        planLimitItems: "وصلت إلى الحد الأقصى لعدد العناصر في باقتك الحالية، رق باقتك لإضافة المزيد.",
        planLimitMembers: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية، رق باقتك لإضافة المزيد.",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        loginLink: "تسجيل الدخول",
        dashboardLink: "لوحة التحكم",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        title: "Platform Admin Console",
        loading: "Loading...",
        serviceUnavailableTitle: "Could not reach the service",
        serviceUnavailableText: "The connection to the service was lost. Check your connection and try again.",
        deniedTitle: "Not authorized",
        deniedText: "This page is for platform administrators only.",
        dashboardBtn: "Back to Dashboard",
        orgsTitle: "Organizations",
        usersTitle: "Users",
        usersIntro: "Everyone registered on the platform, their accounts, and each account's interface. Change the interface from the organisation card.",
        usersCountLabel: "Users:",
        usersEmpty: "No users yet.",
        colPhone: "Phone",
        colUserNumber: "Reference number",
        colNameAr: "Full name",
        colNameEn: "Name in English",
        colOrgs: "Accounts",
        colAdmin: "Platform admin",
        colPack: "Interface",
        yes: "Yes",
        no: "No",
        packChanged: "Interface changed.",
        packOnlyPersonal: "The personal interface is for personal accounts only.",
        packPersonalLocked: "A personal account keeps the personal interface.",
        packUnknown: "Unknown interface.",
        paTitle: "Platform admins",
        paIntro: "Who has access to this page. Add an admin by email if they are registered on the platform.",
        paAddBtn: "Add admin",
        paRemoveBtn: "Remove",
        paYou: "You",
        paSaving: "Saving...",
        paAdded: "{email} added as a platform admin.",
        paRemoved: "{email}'s access removed.",
        paNoUser: "No registered user with that email.",
        paCannotSelfRemove: "You cannot remove your own access.",
        paLastAdmin: "The platform cannot be left with no admin.",
        orgsIntro: "All organizations registered on the platform, with their current plan, member count and item count.",
        filterPlaceholder: "Search by organization name or owner email",
        userFilterPh: "Search by name, email or phone",
        userPickPh: "Click to list everyone registered, or type to filter",
        colLang: "Language", colStore: "Storage", colTelegram: "Telegram", colLastSeen: "Last seen", colDeleteReq: "Deletion requested",
        storePlatform: "Mr.Zahi server (Jeddah)", storeDrive: "Their own Google Drive", linkedYes: "Linked", linkedNo: "Not linked",
        paEmailPh: "User email",
        refreshBtn: "Refresh",
        orgsEmpty: "No organizations registered yet.",
        colPersonal: "Personal account", colMemberOf: "Member of", noPersonal: "No personal account yet", noCompanies: "No companies",
        roleOwner: "Owner", roleAdmin: "Admin", roleMember: "Member", itemsCountShort: "{n} items",
        personalOrgsTitle: "Personal accounts",
        personalOrgsIntro: "A private space for one person's papers and dates, with no commercial register and no team.",
        personalOrgsEmpty: "No personal accounts yet.",
        personalOrgsCountLabel: "Personal accounts:",
        orgsCountLabel: "Organizations:",
        colOwner: "Owner email",
        colPlan: "Current plan",
        colExpires: "Plan expires",
        colMembers: "Members",
        colItems: "Items",
        colCreated: "Created",
        noExpiry: "No expiry",
        expired: "expired",
        activateRowBtn: "Activate subscription",
        activateTitle: "Activate a subscription",
        activateIntro: "Choose the organization, plan and duration, then press Activate. The subscription is recorded under your name and the organization's plan is updated immediately.",
        orgSelectPlaceholder: "Choose organization",
        planSelectPlaceholder: "Choose plan",
        monthsOne: "1 month",
        monthsTwelve: "12 months",
        notePlaceholder: "Note (optional)",
        activateBtn: "Activate",
        activating: "Activating...",
        activated: "Subscription activated successfully.",
        activateMissing: "Choose the organization and plan first.",
        messagesTitle: "Contact messages",
        messagesIntro: "Messages received through the website contact form, newest first.",
        messagesEmpty: "No messages yet.",
        tgMsgsTitle: "Telegram messages",
        tgMsgsIntro: "Everything users send to the Telegram bot, newest first.",
        tgMsgsEmpty: "No messages yet.",
        colChat: "Chat",
        colUser: "User",
        colText: "Text",
        colAction: "Action",
        tgAction_none: "—",
        tgAction_reply: "Bot reply",
        tgAction_agent: "Smart reply",
        tgAction_menu: "Menu",
        tgAction_add: "Add",
        tgAction_done: "Done",
        tgAction_list: "List",
        tgAction_search: "Search",
        tgAction_import: "Import",
        tgAction_linked: "Linked",
        tgAction_bad_code: "Wrong code",
        tgMsgsCountLabel: "Messages:",
        tgConvsCountLabel: "Conversations:",
        backBtn: "Back",
        messagesCountLabel: "Messages:",
        colDate: "Date",
        colName: "Name",
        colEmail: "Email",
        colStatus: "Status",
        requestsTitle: "Upgrade requests",
        requestsEmpty: "No requests.",
        approveBtn: "Approve & activate",
        rejectBtn: "Reject",
        monthsLabel: "months",
        orgNameLabel: "Company",
        savingReq: "Working...",
        savedReq: "Done.",
        reqStatus_pending: "Under review",
        reqStatus_approved: "Activated",
        reqStatus_rejected: "Rejected",
        reqStatus_cancelled: "Cancelled",
        noSubject: "No subject",
        statusNew: "New",
        statusRead: "Read",
        statusReplied: "Replied",
        statusClosed: "Closed",
        loadError: "Could not load:",
        genericError: "Something went wrong. Please try again.",
        planLimitItems: "You have reached the item limit of your current plan. Upgrade to add more.",
        planLimitMembers: "You have reached the member limit of your current plan. Upgrade to add more.",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        loginLink: "Sign in",
        dashboardLink: "Dashboard",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        title: "Console d'administration",
        loading: "Chargement...",
        serviceUnavailableTitle: "Service injoignable",
        serviceUnavailableText: "La connexion au service a ete perdue. Verifiez votre connexion et reessayez.",
        deniedTitle: "Accès non autorisé",
        deniedText: "Cette page est réservée aux administrateurs de la plateforme.",
        dashboardBtn: "Retour au tableau de bord",
        orgsTitle: "Entreprises",
        usersTitle: "Utilisateurs",
        usersIntro: "Toute personne inscrite, ses comptes et l'interface de chaque compte. Changez l'interface depuis la fiche de l'entreprise.",
        usersCountLabel: "Utilisateurs :",
        usersEmpty: "Aucun utilisateur.",
        colPhone: "Téléphone",
        colUserNumber: "Numéro de référence",
        colNameAr: "Nom complet",
        colNameEn: "Nom en anglais",
        colOrgs: "Comptes",
        colAdmin: "Administrateur",
        colPack: "Interface",
        yes: "Oui",
        no: "Non",
        packChanged: "Interface modifiée.",
        packOnlyPersonal: "L'interface personnelle est reservee aux comptes personnels.",
        packPersonalLocked: "Un compte personnel garde l'interface personnelle.",
        packUnknown: "Interface inconnue.",
        paTitle: "Administrateurs de la plateforme",
        paIntro: "Qui a accès à cette page. Ajoutez un administrateur par e-mail s'il est inscrit sur la plateforme.",
        paAddBtn: "Ajouter un administrateur",
        paRemoveBtn: "Retirer",
        paYou: "Vous",
        paSaving: "Enregistrement...",
        paAdded: "{email} ajouté comme administrateur.",
        paRemoved: "Accès de {email} retiré.",
        paNoUser: "Aucun utilisateur inscrit avec cet e-mail.",
        paCannotSelfRemove: "Vous ne pouvez pas retirer votre propre accès.",
        paLastAdmin: "La plateforme ne peut pas rester sans administrateur.",
        orgsIntro: "Toutes les entreprises inscrites sur la plateforme, avec leur forfait actuel, le nombre de membres et le nombre d'éléments.",
        filterPlaceholder: "Rechercher par nom d'entreprise ou e-mail du propriétaire",
        userFilterPh: "Rechercher par nom, e-mail ou téléphone",
        userPickPh: "Cliquez pour lister tous les inscrits, ou tapez pour filtrer",
        colLang: "Langue", colStore: "Stockage", colTelegram: "Telegram", colLastSeen: "Derniere visite", colDeleteReq: "Suppression demandee",
        storePlatform: "Serveur Mr.Zahi (Djeddah)", storeDrive: "Son propre Google Drive", linkedYes: "Lie", linkedNo: "Non lie",
        paEmailPh: "E-mail de l'utilisateur",
        refreshBtn: "Actualiser",
        orgsEmpty: "Aucune entreprise inscrite pour le moment.",
        colPersonal: "Compte personnel", colMemberOf: "Membre de", noPersonal: "Pas encore de compte personnel", noCompanies: "Aucune entreprise",
        roleOwner: "Proprietaire", roleAdmin: "Administrateur", roleMember: "Membre", itemsCountShort: "{n} elements",
        personalOrgsTitle: "Comptes personnels",
        personalOrgsIntro: "Un espace prive pour les papiers et les echeances d'une personne, sans registre de commerce ni equipe.",
        personalOrgsEmpty: "Aucun compte personnel pour le moment.",
        personalOrgsCountLabel: "Comptes personnels :",
        orgsCountLabel: "Nombre d'entreprises :",
        colOwner: "E-mail du propriétaire",
        colPlan: "Forfait actuel",
        colExpires: "Expiration du forfait",
        colMembers: "Membres",
        colItems: "Éléments",
        colCreated: "Date de création",
        noExpiry: "Sans expiration",
        expired: "expiré",
        activateRowBtn: "Activer un abonnement",
        activateTitle: "Activer un abonnement",
        activateIntro: "Choisissez l'entreprise, le forfait et la durée, puis cliquez sur « Activer ». L'abonnement est enregistré à votre nom et le forfait de l'entreprise est mis à jour immédiatement.",
        orgSelectPlaceholder: "Choisir l'entreprise",
        planSelectPlaceholder: "Choisir le forfait",
        monthsOne: "1 mois",
        monthsTwelve: "12 mois",
        notePlaceholder: "Note (facultatif)",
        activateBtn: "Activer",
        activating: "Activation en cours...",
        activated: "Abonnement activé avec succès.",
        activateMissing: "Choisissez d'abord l'entreprise et le forfait.",
        messagesTitle: "Messages de contact",
        messagesIntro: "Messages reçus via le formulaire de contact du site, les plus récents en premier.",
        messagesEmpty: "Aucun message pour le moment.",
        tgMsgsTitle: "Messages Telegram",
        tgMsgsIntro: "Tout ce que les utilisateurs envoient au bot Telegram, du plus récent au plus ancien.",
        tgMsgsEmpty: "Aucun message pour le moment.",
        colChat: "Conversation",
        colUser: "Utilisateur",
        colText: "Texte",
        colAction: "Action",
        tgAction_none: "—",
        tgAction_reply: "Réponse du bot",
        tgAction_agent: "Réponse intelligente",
        tgAction_menu: "Menu",
        tgAction_add: "Ajout",
        tgAction_done: "Terminé",
        tgAction_list: "Liste",
        tgAction_search: "Recherche",
        tgAction_import: "Import",
        tgAction_linked: "Lié",
        tgAction_bad_code: "Code erroné",
        tgMsgsCountLabel: "Messages :",
        tgConvsCountLabel: "Conversations :",
        backBtn: "Retour",
        messagesCountLabel: "Nombre de messages :",
        colDate: "Date",
        colName: "Nom",
        colEmail: "E-mail",
        colStatus: "Statut",
        requestsTitle: "Demandes de mise à niveau",
        requestsEmpty: "Aucune demande.",
        approveBtn: "Approuver et activer",
        rejectBtn: "Refuser",
        monthsLabel: "mois",
        orgNameLabel: "Entreprise",
        savingReq: "En cours...",
        savedReq: "Terminé.",
        reqStatus_pending: "En cours d'examen",
        reqStatus_approved: "Activé",
        reqStatus_rejected: "Refusé",
        reqStatus_cancelled: "Annulé",
        noSubject: "Sans objet",
        statusNew: "Nouveau",
        statusRead: "Lu",
        statusReplied: "Répondu",
        statusClosed: "Fermé",
        loadError: "Chargement impossible :",
        genericError: "Une erreur est survenue. Veuillez réessayer.",
        planLimitItems: "Vous avez atteint la limite d'éléments de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        planLimitMembers: "Vous avez atteint la limite de membres de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        loginLink: "Connexion",
        dashboardLink: "Tableau de bord",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        title: "پلیٹ فارم ایڈمن پینل",
        loading: "لوڈ ہو رہا ہے...",
        serviceUnavailableTitle: "سروس تک رسائی نہیں ہو سکی",
        serviceUnavailableText: "سروس سے رابطہ منقطع ہو گیا۔ اپنا رابطہ چیک کر کے دوبارہ کوشش کریں۔",
        deniedTitle: "اجازت نہیں",
        deniedText: "یہ صفحہ صرف پلیٹ فارم ایڈمنز کے لیے ہے۔",
        dashboardBtn: "ڈیش بورڈ پر واپس جائیں",
        orgsTitle: "کمپنیاں",
        usersTitle: "صارفین",
        usersIntro: "پلیٹ فارم پر رجسٹرڈ سب افراد، ان کے اکاؤنٹس اور ہر اکاؤنٹ کا انٹرفیس۔ انٹرفیس کمپنی کارڈ سے بدلیں۔",
        usersCountLabel: "صارفین:",
        usersEmpty: "ابھی کوئی صارف نہیں۔",
        colPhone: "فون",
        colUserNumber: "حوالہ نمبر",
        colNameAr: "پورا نام",
        colNameEn: "انگریزی میں نام",
        colOrgs: "اکاؤنٹس",
        colAdmin: "پلیٹ فارم ایڈمن",
        colPack: "انٹرفیس",
        yes: "ہاں",
        no: "نہیں",
        packChanged: "انٹرفیس بدل گیا۔",
        packOnlyPersonal: "ذاتی انٹرفیس صرف ذاتی اکاؤنٹس کے لیے ہے۔",
        packPersonalLocked: "ذاتی اکاؤنٹ ذاتی انٹرفیس پر ہی رہتا ہے۔",
        packUnknown: "نامعلوم انٹرفیس۔",
        paTitle: "پلیٹ فارم ایڈمنز",
        paIntro: "اس صفحے تک کس کی رسائی ہے۔ اگر رجسٹرڈ ہو تو ای میل سے ایڈمن شامل کریں۔",
        paAddBtn: "ایڈمن شامل کریں",
        paRemoveBtn: "ہٹائیں",
        paYou: "آپ",
        paSaving: "محفوظ ہو رہا ہے...",
        paAdded: "{email} کو ایڈمن بنا دیا گیا۔",
        paRemoved: "{email} کی رسائی ہٹا دی گئی۔",
        paNoUser: "اس ای میل سے کوئی رجسٹرڈ صارف نہیں۔",
        paCannotSelfRemove: "آپ اپنی رسائی خود نہیں ہٹا سکتے۔",
        paLastAdmin: "پلیٹ فارم بغیر ایڈمن کے نہیں رہ سکتا۔",
        orgsIntro: "پلیٹ فارم پر رجسٹرڈ تمام کمپنیاں، ان کے موجودہ پلان، اراکین اور آئٹمز کی تعداد کے ساتھ۔",
        filterPlaceholder: "کمپنی کے نام یا مالک کے ای میل سے تلاش کریں",
        userFilterPh: "نام، ای میل یا فون سے تلاش کریں",
        userPickPh: "تمام رجسٹرڈ افراد دیکھنے کے لیے دبائیں، یا فلٹر کے لیے لکھیں",
        colLang: "زبان", colStore: "اسٹوریج", colTelegram: "ٹیلیگرام", colLastSeen: "آخری بار", colDeleteReq: "حذف کی درخواست",
        storePlatform: "مسٹر زاہی سرور (جدہ)", storeDrive: "اس کا اپنا Google Drive", linkedYes: "منسلک", linkedNo: "غیر منسلک",
        paEmailPh: "صارف کا ای میل",
        refreshBtn: "تازہ کریں",
        orgsEmpty: "ابھی کوئی کمپنی رجسٹرڈ نہیں۔",
        colPersonal: "ذاتی اکاؤنٹ", colMemberOf: "رکن ہے", noPersonal: "ابھی ذاتی اکاؤنٹ نہیں", noCompanies: "کوئی کمپنی نہیں",
        roleOwner: "مالک", roleAdmin: "ایڈمن", roleMember: "ممبر", itemsCountShort: "{n} آئٹمز",
        personalOrgsTitle: "ذاتی اکاؤنٹس",
        personalOrgsIntro: "ایک شخص کے کاغذات اور تاریخوں کی نجی جگہ، بغیر کمرشل رجسٹر اور بغیر ٹیم۔",
        personalOrgsEmpty: "ابھی کوئی ذاتی اکاؤنٹ نہیں۔",
        personalOrgsCountLabel: "ذاتی اکاؤنٹس:",
        orgsCountLabel: "کمپنیوں کی تعداد:",
        colOwner: "مالک کا ای میل",
        colPlan: "موجودہ پلان",
        colExpires: "پلان کی میعاد ختم",
        colMembers: "اراکین کی تعداد",
        colItems: "آئٹمز کی تعداد",
        colCreated: "بنانے کی تاریخ",
        noExpiry: "بلا میعاد",
        expired: "میعاد ختم",
        activateRowBtn: "سبسکرپشن فعال کریں",
        activateTitle: "سبسکرپشن فعال کریں",
        activateIntro: "کمپنی، پلان اور مدت منتخب کریں، پھر «فعال کریں» دبائیں۔ سبسکرپشن آپ کے نام سے درج ہو گی اور کمپنی کا پلان فورا اپ ڈیٹ ہو جائے گا۔",
        orgSelectPlaceholder: "کمپنی منتخب کریں",
        planSelectPlaceholder: "پلان منتخب کریں",
        monthsOne: "ایک مہینہ",
        monthsTwelve: "12 مہینے",
        notePlaceholder: "نوٹ (اختیاری)",
        activateBtn: "فعال کریں",
        activating: "فعال کیا جا رہا ہے...",
        activated: "سبسکرپشن کامیابی سے فعال ہو گئی۔",
        activateMissing: "پہلے کمپنی اور پلان منتخب کریں۔",
        messagesTitle: "رابطہ پیغامات",
        messagesIntro: "ویب سائٹ کے رابطہ فارم سے موصول پیغامات، تازہ ترین پہلے۔",
        messagesEmpty: "ابھی کوئی پیغام نہیں۔",
        tgMsgsTitle: "ٹیلیگرام پیغامات",
        tgMsgsIntro: "صارفین ٹیلیگرام بوٹ کو جو کچھ بھیجتے ہیں، تازہ ترین پہلے۔",
        tgMsgsEmpty: "ابھی کوئی پیغام نہیں۔",
        colChat: "چیٹ",
        colUser: "صارف",
        colText: "متن",
        colAction: "کارروائی",
        tgAction_none: "—",
        tgAction_reply: "بوٹ کا جواب",
        tgAction_agent: "ہوشیار جواب",
        tgAction_menu: "مینو",
        tgAction_add: "اندراج",
        tgAction_done: "مکمل",
        tgAction_list: "فہرست",
        tgAction_search: "تلاش",
        tgAction_import: "درآمد",
        tgAction_linked: "منسلک",
        tgAction_bad_code: "غلط کوڈ",
        tgMsgsCountLabel: "پیغامات:",
        tgConvsCountLabel: "گفتگوئیں:",
        backBtn: "واپس",
        messagesCountLabel: "پیغامات کی تعداد:",
        colDate: "تاریخ",
        colName: "نام",
        colEmail: "ای میل",
        colStatus: "حیثیت",
        requestsTitle: "اپ گریڈ کی درخواستیں",
        requestsEmpty: "کوئی درخواست نہیں۔",
        approveBtn: "منظور کر کے فعال کریں",
        rejectBtn: "مسترد",
        monthsLabel: "مہینے",
        orgNameLabel: "کمپنی",
        savingReq: "جاری ہے...",
        savedReq: "ہو گیا۔",
        reqStatus_pending: "زیر جائزہ",
        reqStatus_approved: "فعال",
        reqStatus_rejected: "مسترد",
        reqStatus_cancelled: "منسوخ",
        noSubject: "بغیر موضوع",
        statusNew: "نیا",
        statusRead: "پڑھا گیا",
        statusReplied: "جواب دیا گیا",
        statusClosed: "بند",
        loadError: "لوڈ نہیں ہو سکا:",
        genericError: "کچھ غلط ہو گیا، براہ کرم دوبارہ کوشش کریں۔",
        planLimitItems: "آپ اپنے موجودہ پلان میں آئٹمز کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        planLimitMembers: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        loginLink: "سائن ان",
        dashboardLink: "ڈیش بورڈ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };

    const lang = () => localStorage.getItem("mrzahi_lang") || "ar";
    const theme = () => localStorage.getItem("mrzahi_theme") || "dark";
    const langNames = { ar: "العربية", en: "English", fr: "Français", ur: "اردو" };
    let l = lang();
    document.documentElement.lang = l;
    document.documentElement.dir = (l === "ar" || l === "ur") ? "rtl" : "ltr";

    const placeholderKeys = { orgFilter: "filterPlaceholder", actNote: "notePlaceholder" };
    function applyPlaceholders(code) {
      const dict = translations[code] || translations.ar;
      /* السمة data-i18n-placeholder في الترميز لم يكن يقرؤها أحد، فيبقى النص
         العربي في كل اللغات. تقرأ هنا مرة واحدة لكل من يحملها. */
      document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
        var k = el.getAttribute("data-i18n-placeholder");
        if (k && dict[k]) el.placeholder = dict[k];
      });
      Object.keys(placeholderKeys).forEach(id => {
        const el = document.getElementById(id);
        if (el && dict[placeholderKeys[id]]) el.placeholder = dict[placeholderKeys[id]];
      });
    }

    function setLang(code) {
      localStorage.setItem("mrzahi_lang", code);
      l = code;
      document.documentElement.lang = code;
      document.documentElement.dir = (code === "ar" || code === "ur") ? "rtl" : "ltr";
      document.getElementById("currentLangDisplay").textContent = langNames[code] || code;
      ["ar","en","fr","ur"].forEach(c => {
        const el = document.getElementById("check-" + c);
        if (el) el.style.display = c === code ? "inline" : "none";
      });
      const th = theme();
      document.getElementById("currentThemeDisplay").textContent = translations[code][th === "dark" ? "dark" : "light"];
      document.querySelectorAll("[data-i18n]").forEach(el => {
        const k = el.dataset.i18n;
        if (translations[code] && translations[code][k]) el.innerHTML = translations[code][k];
      });
      applyPlaceholders(code);
      document.title = (translations[code] && translations[code].title ? translations[code].title : "Admin") + " | MrZahi";
      if (typeof window.__mrzahiAuthRefresh === "function") window.__mrzahiAuthRefresh();
      if (typeof window.__adminRefresh === "function") window.__adminRefresh();
    }

    function setTheme(th) {
      localStorage.setItem("mrzahi_theme", th);
      document.documentElement.dataset.theme = th;
      const meta = document.getElementById("themeColorMeta");
      if (meta) meta.content = th === "dark" ? "#1a2933" : "#0068b8";
      const logo = document.getElementById("footerLogo");
      if (logo) logo.src = th === "dark" ? "/mrzahi-logo-full-dark.png?v=2" : "/mrzahi-logo-full-light.png?v=2";
      document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️";
      document.getElementById("currentThemeDisplay").textContent = translations[l][th === "dark" ? "dark" : "light"];
      document.getElementById("check-light").style.display = th === "light" ? "inline" : "none";
      document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none";
    }

    document.getElementById("langMenuBtn").addEventListener("click", e => {
      e.stopPropagation();
      document.getElementById("langDropdown").classList.toggle("show");
      document.getElementById("themeDropdown").classList.remove("show");
    });
    // زر المظهر يبدل الثيم مباشرة بضغطة واحدة بلا قائمة (طلب المهندس رعد)
    document.getElementById("themeMenuBtn").addEventListener("click", e => {
      e.stopPropagation();
      setTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark");
      document.getElementById("langDropdown").classList.remove("show");
    });
    document.addEventListener("click", () => {
      document.getElementById("langDropdown").classList.remove("show");
      document.getElementById("themeDropdown").classList.remove("show");
    });

    document.querySelectorAll("#langDropdown .menu-dropdown-item").forEach(item => {
      item.addEventListener("click", () => setLang(item.dataset.lang));
    });
    document.querySelectorAll("#themeDropdown .menu-dropdown-item").forEach(item => {
      item.addEventListener("click", () => {
        setTheme(item.dataset.theme);
        document.getElementById("themeDropdown").classList.remove("show");
      });
    });

    document.querySelectorAll("[data-i18n]").forEach(el => {
      const k = el.dataset.i18n;
      if (translations[l] && translations[l][k]) el.textContent = translations[l][k];
    });
    applyPlaceholders(l);
    document.getElementById("currentLangDisplay").textContent = langNames[l] || l;
    ["ar","en","fr","ur"].forEach(c => {
      const el = document.getElementById("check-" + c);
      if (el) el.style.display = l === c ? "inline" : "none";
    });
    document.title = (translations[l] && translations[l].title ? translations[l].title : "Admin") + " | MrZahi";

    (function() {
      const th = theme();
      document.documentElement.dataset.theme = th;
      const meta = document.getElementById("themeColorMeta");
      if (meta) meta.content = th === "dark" ? "#1a2933" : "#0068b8";
      const logo = document.getElementById("footerLogo");
      if (logo) logo.src = th === "dark" ? "/mrzahi-logo-full-dark.png?v=2" : "/mrzahi-logo-full-light.png?v=2";
      document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️";
      document.getElementById("currentThemeDisplay").textContent = translations[l][th === "dark" ? "dark" : "light"];
      document.getElementById("check-light").style.display = th === "light" ? "inline" : "none";
      document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none";
    })();
  