    /* نصوص الحضور والانصراف بالاربع لغات، تدمج في قاموس الصفحة قبل ان يقرأه المطبق */
    const ATT_I18N = {
      ar: {
        title: "الحضور والانصراف", attTitle: "الحضور والانصراف",
        meTitle: "حضوري", punchIn: "تسجيل حضور", punchOut: "تسجيل انصراف", meToday: "بصمات اليوم", meNone: "لم تبصم اليوم بعد.",
        meNotStaff: "حسابك غير مربوط بملف موظف. يربط حين يكتب بريدك نفسه في ملفك عند الموارد البشرية.",
        workHours: "الدوام", locating: "يحدد موقعك…",
        st_ok_in: "سجل حضورك.", st_ok_out: "سجل انصرافك.", st_outside: "أنت خارج نطاق مقر العمل ({d} م، والمسموح {r} م).",
        st_need_location: "اسمح للمتصفح بمعرفة موقعك ثم أعد المحاولة.", st_too_soon: "بصمت قبل أقل من دقيقة.",
        st_app_disabled: "البصمة من التطبيق موقوفة في هذا الحساب.", st_not_staff: "حسابك غير مربوط بملف موظف.",
        boardTitle: "لوحة الموارد البشرية", tabToday: "اليوم", tabMonth: "الشهر", tabSettings: "الإعدادات والأجهزة",
        colEmployee: "الموظف", colStatus: "الحالة", colIn: "الدخول", colOut: "الخروج", colLate: "التأخر", colWorked: "ساعات العمل",
        colPresent: "حضور", colAbsent: "غياب", colLeave: "إجازة", colLateMin: "دقائق التأخر",
        s_present: "حاضر", s_absent: "غائب", s_leave: "إجازة", s_weekend: "عطلة", s_pending: "لم يبصم بعد", s_untracked: "قبل بدء التتبع",
        minutes: "د", noStaff: "لا موظفين على رأس العمل. أضفهم من شاشة الموظفين.",
        month: "الشهر", closeMonth: "قفل الشهر للرواتب", reopenMonth: "فتح الشهر", closedBadge: "مقفل — يقرؤه مسيّر الرواتب",
        openBadge: "مفتوح — المسيّر لا يخصم شيئا قبل القفل", r_not_ended: "لا يقفل الشهر قبل أن ينتهي.",
        r_payroll_locked: "مسيّر هذا الشهر معتمد، فأعد فتحه أولا.", r_closed: "قفل الشهر: {n} موظف.",
        manualTitle: "بصمة يدوية", fStaff: "الموظف", fAt: "الوقت", fDirection: "النوع", dirIn: "دخول", dirOut: "خروج", dirAuto: "تلقائي",
        fReason: "السبب (إلزامي)", addPunch: "إضافة البصمة", r_need_note: "اكتب سبب البصمة اليدوية.", r_future: "لا تضاف بصمة في المستقبل.",
        unlinkedTitle: "بصمات من الجهاز بأرقام لا تطابق موظفا: {pins}. اكتب رقم البصمة في ملف الموظف (رقم البصمة أو الرقم الوظيفي) ثم اضغط «ربط».",
        relink: "ربط", r_linked: "ربطت {n} بصمة.",
        setTitle: "إعدادات الدوام", sStart: "بداية الدوام", sEnd: "نهاية الدوام", sGrace: "دقائق السماح", sWeekend: "العطلة الأسبوعية",
        sSince: "بداية التتبع (فارغ = أول بصمة)", sApp: "البصمة من التطبيق", sFence: "نطاق مقر العمل للبصمة من التطبيق",
        sLat: "خط العرض", sLng: "خط الطول", sRadius: "نصف القطر بالمتر (فارغ = بلا نطاق)", useMyLocation: "استعمل موقعي الآن",
        save: "حفظ", saved: "تم الحفظ.", badValue: "قيمة غير صحيحة.", adminOnly: "الإعدادات والأجهزة للمالك أو المشرف.",
        days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
        devTitle: "أجهزة البصمة", devSerial: "الرقم التسلسلي (SN)", devName: "الاسم", devStatus: "الحالة", devSeen: "آخر اتصال",
        devTotal: "البصمات", devAdd: "تسجيل الجهاز", devNever: "لم يتصل بعد", devActive: "يعمل", devDisabled: "موقوف",
        devDisable: "إيقاف", devEnable: "تشغيل", devDelete: "حذف", r_bad_serial: "الرقم التسلسلي حروف وأرقام من 6 إلى 32.",
        r_taken: "هذا الجهاز مسجل في حساب آخر.", r_seen: "سجل الجهاز، وقد اتصل بالمنصة من قبل فستصل بصماته الآن.", r_registered: "سجل الجهاز. اضبطه كما في الخطوات ليتصل.",
        devHowTitle: "ضبط الجهاز (ZKTeco)",
        devHow: "في الجهاز: القائمة ← الاتصال ← إعدادات الخادم السحابي (Cloud Server / ADMS). عنوان الخادم: mrzahi.com، المنفذ 443 مع تفعيل HTTPS إن كان الجهاز يدعمه، وإلا المنفذ 80. فعّل «الإرسال الفوري». ثم اكتب الرقم التسلسلي للجهاز هنا. رقم الموظف في الجهاز يجب أن يطابق رقم البصمة أو الرقم الوظيفي في ملفه.",
        devHttpNote: "الأجهزة القديمة التي لا تدعم HTTPS تحتاج استثناء المسار /iclock من التحويل الإجباري إلى HTTPS في Cloudflare.",
        genericError: "حدث خطأ، حاول مرة أخرى.", notAllowed: "لا تملك صلاحية هذا الإجراء.", choose: "اختر"
      },
      en: {
        title: "Attendance", attTitle: "Attendance",
        meTitle: "My attendance", punchIn: "Check in", punchOut: "Check out", meToday: "Today's punches", meNone: "No punches today yet.",
        meNotStaff: "Your account is not linked to an employee file. It links when your same email is written in your file by HR.",
        workHours: "Working hours", locating: "Locating you…",
        st_ok_in: "Checked in.", st_ok_out: "Checked out.", st_outside: "You are outside the workplace area ({d} m; allowed {r} m).",
        st_need_location: "Allow the browser to know your location and try again.", st_too_soon: "You punched less than a minute ago.",
        st_app_disabled: "App punching is turned off for this account.", st_not_staff: "Your account is not linked to an employee file.",
        boardTitle: "HR board", tabToday: "Today", tabMonth: "Month", tabSettings: "Settings & devices",
        colEmployee: "Employee", colStatus: "Status", colIn: "In", colOut: "Out", colLate: "Late", colWorked: "Worked",
        colPresent: "Present", colAbsent: "Absent", colLeave: "Leave", colLateMin: "Late minutes",
        s_present: "Present", s_absent: "Absent", s_leave: "Leave", s_weekend: "Weekend", s_pending: "Not yet", s_untracked: "Before tracking",
        minutes: "min", noStaff: "No active employees. Add them from the Employees screen.",
        month: "Month", closeMonth: "Close month for payroll", reopenMonth: "Reopen month", closedBadge: "Closed — read by payroll",
        openBadge: "Open — payroll deducts nothing until it is closed", r_not_ended: "A month cannot close before it ends.",
        r_payroll_locked: "This month's payroll is approved; reopen it first.", r_closed: "Month closed: {n} employees.",
        manualTitle: "Manual punch", fStaff: "Employee", fAt: "Time", fDirection: "Type", dirIn: "In", dirOut: "Out", dirAuto: "Automatic",
        fReason: "Reason (required)", addPunch: "Add punch", r_need_note: "Write the reason for the manual punch.", r_future: "A punch cannot be in the future.",
        unlinkedTitle: "Device punches with numbers that match no employee: {pins}. Write the punch number in the employee file (device PIN or employee number), then press “Link”.",
        relink: "Link", r_linked: "Linked {n} punches.",
        setTitle: "Working hours settings", sStart: "Start", sEnd: "End", sGrace: "Grace minutes", sWeekend: "Weekend",
        sSince: "Tracking start (empty = first punch)", sApp: "App punching", sFence: "Workplace area for app punching",
        sLat: "Latitude", sLng: "Longitude", sRadius: "Radius in meters (empty = no area)", useMyLocation: "Use my current location",
        save: "Save", saved: "Saved.", badValue: "Invalid value.", adminOnly: "Settings and devices are for the owner or an admin.",
        days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        devTitle: "Attendance devices", devSerial: "Serial number (SN)", devName: "Name", devStatus: "Status", devSeen: "Last contact",
        devTotal: "Punches", devAdd: "Register device", devNever: "Never connected", devActive: "Active", devDisabled: "Disabled",
        devDisable: "Disable", devEnable: "Enable", devDelete: "Delete", r_bad_serial: "The serial is 6 to 32 letters and digits.",
        r_taken: "This device is registered to another account.", r_seen: "Registered. The device already contacted the platform, so its punches arrive now.", r_registered: "Registered. Set the device up as below so it connects.",
        devHowTitle: "Device setup (ZKTeco)",
        devHow: "On the device: Menu → Communication → Cloud Server (ADMS). Server address: mrzahi.com, port 443 with HTTPS enabled if supported, otherwise port 80. Turn on real-time upload. Then enter the device serial here. The user number on the device must match the device PIN or employee number in the employee file.",
        devHttpNote: "Older devices without HTTPS need the /iclock path exempted from forced HTTPS in Cloudflare.",
        genericError: "Something went wrong. Please try again.", notAllowed: "You do not have permission for this action.", choose: "Choose"
      },
      fr: {
        title: "Présences", attTitle: "Présences",
        meTitle: "Ma présence", punchIn: "Pointer l'arrivée", punchOut: "Pointer le départ", meToday: "Pointages du jour", meNone: "Aucun pointage aujourd'hui.",
        meNotStaff: "Votre compte n'est lié à aucune fiche employé. Il se lie quand votre e-mail figure dans votre fiche RH.",
        workHours: "Horaires", locating: "Localisation…",
        st_ok_in: "Arrivée enregistrée.", st_ok_out: "Départ enregistré.", st_outside: "Vous êtes hors de la zone de travail ({d} m ; autorisé {r} m).",
        st_need_location: "Autorisez la localisation puis réessayez.", st_too_soon: "Vous avez pointé il y a moins d'une minute.",
        st_app_disabled: "Le pointage par l'application est désactivé.", st_not_staff: "Votre compte n'est lié à aucune fiche employé.",
        boardTitle: "Tableau RH", tabToday: "Aujourd'hui", tabMonth: "Mois", tabSettings: "Paramètres et appareils",
        colEmployee: "Employé", colStatus: "Statut", colIn: "Arrivée", colOut: "Départ", colLate: "Retard", colWorked: "Travaillé",
        colPresent: "Présent", colAbsent: "Absent", colLeave: "Congé", colLateMin: "Minutes de retard",
        s_present: "Présent", s_absent: "Absent", s_leave: "Congé", s_weekend: "Week-end", s_pending: "Pas encore", s_untracked: "Avant le suivi",
        minutes: "min", noStaff: "Aucun employé actif. Ajoutez-les depuis l'écran Employés.",
        month: "Mois", closeMonth: "Clôturer le mois pour la paie", reopenMonth: "Rouvrir le mois", closedBadge: "Clôturé — lu par la paie",
        openBadge: "Ouvert — la paie ne retient rien avant la clôture", r_not_ended: "Un mois ne se clôture pas avant sa fin.",
        r_payroll_locked: "La paie de ce mois est approuvée ; rouvrez-la d'abord.", r_closed: "Mois clôturé : {n} employés.",
        manualTitle: "Pointage manuel", fStaff: "Employé", fAt: "Heure", fDirection: "Type", dirIn: "Arrivée", dirOut: "Départ", dirAuto: "Automatique",
        fReason: "Motif (obligatoire)", addPunch: "Ajouter", r_need_note: "Indiquez le motif du pointage manuel.", r_future: "Pas de pointage dans le futur.",
        unlinkedTitle: "Pointages d'appareil dont le numéro ne correspond à aucun employé : {pins}. Saisissez le numéro dans la fiche (PIN ou matricule), puis « Lier ».",
        relink: "Lier", r_linked: "{n} pointages liés.",
        setTitle: "Paramètres des horaires", sStart: "Début", sEnd: "Fin", sGrace: "Minutes de tolérance", sWeekend: "Week-end",
        sSince: "Début du suivi (vide = premier pointage)", sApp: "Pointage par l'application", sFence: "Zone de travail pour le pointage par l'application",
        sLat: "Latitude", sLng: "Longitude", sRadius: "Rayon en mètres (vide = sans zone)", useMyLocation: "Utiliser ma position",
        save: "Enregistrer", saved: "Enregistré.", badValue: "Valeur invalide.", adminOnly: "Paramètres et appareils réservés au propriétaire ou à un admin.",
        days: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
        devTitle: "Pointeuses", devSerial: "Numéro de série (SN)", devName: "Nom", devStatus: "Statut", devSeen: "Dernier contact",
        devTotal: "Pointages", devAdd: "Enregistrer l'appareil", devNever: "Jamais connecté", devActive: "Actif", devDisabled: "Désactivé",
        devDisable: "Désactiver", devEnable: "Activer", devDelete: "Supprimer", r_bad_serial: "Le numéro de série compte 6 à 32 lettres et chiffres.",
        r_taken: "Cet appareil est enregistré sur un autre compte.", r_seen: "Enregistré. L'appareil a déjà contacté la plateforme : ses pointages arrivent.", r_registered: "Enregistré. Configurez l'appareil comme ci-dessous.",
        devHowTitle: "Configuration (ZKTeco)",
        devHow: "Sur l'appareil : Menu → Communication → Serveur cloud (ADMS). Adresse : mrzahi.com, port 443 avec HTTPS si possible, sinon port 80. Activez l'envoi en temps réel. Puis saisissez ici le numéro de série. Le numéro d'utilisateur sur l'appareil doit correspondre au PIN ou au matricule de la fiche.",
        devHttpNote: "Les appareils anciens sans HTTPS exigent d'exempter le chemin /iclock du HTTPS forcé dans Cloudflare.",
        genericError: "Une erreur s'est produite. Réessayez.", notAllowed: "Vous n'avez pas l'autorisation pour cette action.", choose: "Choisir"
      },
      ur: {
        title: "حاضری", attTitle: "حاضری",
        meTitle: "میری حاضری", punchIn: "آمد درج کریں", punchOut: "رخصت درج کریں", meToday: "آج کی حاضریاں", meNone: "آج ابھی کوئی حاضری نہیں۔",
        meNotStaff: "آپ کا اکاؤنٹ کسی ملازم فائل سے منسلک نہیں۔ جب HR آپ کی فائل میں یہی ای میل لکھے گا تو منسلک ہو جائے گا۔",
        workHours: "اوقاتِ کار", locating: "مقام معلوم کیا جا رہا ہے…",
        st_ok_in: "آمد درج ہو گئی۔", st_ok_out: "رخصت درج ہو گئی۔", st_outside: "آپ دفتر کے دائرے سے باہر ہیں ({d} م؛ اجازت {r} م)۔",
        st_need_location: "براؤزر کو مقام کی اجازت دیں اور دوبارہ کوشش کریں۔", st_too_soon: "آپ نے ایک منٹ سے کم پہلے حاضری لگائی۔",
        st_app_disabled: "ایپ سے حاضری اس اکاؤنٹ میں بند ہے۔", st_not_staff: "آپ کا اکاؤنٹ کسی ملازم فائل سے منسلک نہیں۔",
        boardTitle: "HR بورڈ", tabToday: "آج", tabMonth: "مہینہ", tabSettings: "ترتیبات اور آلات",
        colEmployee: "ملازم", colStatus: "حالت", colIn: "آمد", colOut: "رخصت", colLate: "تاخیر", colWorked: "کام",
        colPresent: "حاضر", colAbsent: "غیر حاضر", colLeave: "چھٹی", colLateMin: "تاخیر کے منٹ",
        s_present: "حاضر", s_absent: "غیر حاضر", s_leave: "چھٹی", s_weekend: "ہفتہ وار تعطیل", s_pending: "ابھی نہیں", s_untracked: "ٹریکنگ سے پہلے",
        minutes: "منٹ", noStaff: "کوئی فعال ملازم نہیں۔ ملازمین کی سکرین سے شامل کریں۔",
        month: "مہینہ", closeMonth: "پے رول کے لیے مہینہ بند کریں", reopenMonth: "مہینہ کھولیں", closedBadge: "بند — پے رول پڑھتا ہے",
        openBadge: "کھلا — بند ہونے تک پے رول کوئی کٹوتی نہیں کرتا", r_not_ended: "مہینہ ختم ہونے سے پہلے بند نہیں ہوتا۔",
        r_payroll_locked: "اس مہینے کا پے رول منظور ہے؛ پہلے اسے کھولیں۔", r_closed: "مہینہ بند: {n} ملازمین۔",
        manualTitle: "دستی حاضری", fStaff: "ملازم", fAt: "وقت", fDirection: "قسم", dirIn: "آمد", dirOut: "رخصت", dirAuto: "خودکار",
        fReason: "وجہ (لازمی)", addPunch: "شامل کریں", r_need_note: "دستی حاضری کی وجہ لکھیں۔", r_future: "مستقبل کی حاضری شامل نہیں ہو سکتی۔",
        unlinkedTitle: "آلے کی ایسی حاضریاں جن کا نمبر کسی ملازم سے نہیں ملتا: {pins}۔ ملازم کی فائل میں نمبر لکھیں (آلہ PIN یا ملازم نمبر)، پھر «منسلک کریں» دبائیں۔",
        relink: "منسلک کریں", r_linked: "{n} حاضریاں منسلک ہوئیں۔",
        setTitle: "اوقاتِ کار کی ترتیبات", sStart: "آغاز", sEnd: "اختتام", sGrace: "رعایتی منٹ", sWeekend: "ہفتہ وار تعطیل",
        sSince: "ٹریکنگ کا آغاز (خالی = پہلی حاضری)", sApp: "ایپ سے حاضری", sFence: "ایپ حاضری کے لیے دفتر کا دائرہ",
        sLat: "عرض بلد", sLng: "طول بلد", sRadius: "رداس میٹر میں (خالی = بغیر دائرہ)", useMyLocation: "میرا موجودہ مقام استعمال کریں",
        save: "محفوظ کریں", saved: "محفوظ ہو گیا۔", badValue: "غلط قدر۔", adminOnly: "ترتیبات اور آلات مالک یا منتظم کے لیے ہیں۔",
        days: ["اتوار", "پیر", "منگل", "بدھ", "جمعرات", "جمعہ", "ہفتہ"],
        devTitle: "حاضری کے آلات", devSerial: "سیریل نمبر (SN)", devName: "نام", devStatus: "حالت", devSeen: "آخری رابطہ",
        devTotal: "حاضریاں", devAdd: "آلہ درج کریں", devNever: "کبھی منسلک نہیں ہوا", devActive: "فعال", devDisabled: "بند",
        devDisable: "بند کریں", devEnable: "چالو کریں", devDelete: "حذف", r_bad_serial: "سیریل 6 سے 32 حروف و اعداد کا ہوتا ہے۔",
        r_taken: "یہ آلہ کسی اور اکاؤنٹ میں درج ہے۔", r_seen: "درج ہو گیا۔ آلہ پہلے ہی پلیٹ فارم سے رابطہ کر چکا ہے، اس کی حاضریاں اب پہنچیں گی۔", r_registered: "درج ہو گیا۔ نیچے کے مطابق آلہ ترتیب دیں۔",
        devHowTitle: "آلے کی ترتیب (ZKTeco)",
        devHow: "آلے میں: مینو ← کمیونیکیشن ← کلاؤڈ سرور (ADMS)۔ سرور کا پتہ: mrzahi.com، پورٹ 443 اور HTTPS اگر ممکن ہو، ورنہ پورٹ 80۔ ریئل ٹائم اپ لوڈ چالو کریں۔ پھر یہاں آلے کا سیریل لکھیں۔ آلے میں صارف نمبر ملازم کی فائل کے PIN یا ملازم نمبر سے ملنا چاہیے۔",
        devHttpNote: "HTTPS کے بغیر پرانے آلات کے لیے Cloudflare میں /iclock کو لازمی HTTPS سے مستثنیٰ کرنا ہوگا۔",
        genericError: "کچھ غلط ہو گیا، دوبارہ کوشش کریں۔", notAllowed: "آپ کو اس عمل کی اجازت نہیں۔", choose: "منتخب کریں"
      }
    };
    Object.keys(ATT_I18N).forEach(function (k) { if (translations[k]) Object.assign(translations[k], ATT_I18N[k]); });

