    /* نصوص مسيرات الرواتب بالاربع لغات، تدمج في قاموس الصفحة قبل ان يقرأه المطبق */
    const PAYROLL_I18N = {
      ar: {
        title: "مسيرات الرواتب", payTitle: "مسيرات الرواتب",
        payIntro: "مسير كل شهر يولد من ملفات الموظفين: الراتب والبدلات الشهرية، والتأمينات تلقائيا، والإجازة بلا راتب، والغياب والتأخر من الحضور. يعتمده المالك أو المشرف فيقفل، ثم يصدر ملف التحويل البنكي والقسائم، ويقيد في المحاسبة حين يدفع.",
        month: "الشهر", generate: "توليد المسير", settingsBtn: "الإعدادات",
        runsTitle: "المسيرات", colMonth: "الشهر", colEmployees: "الموظفون", colGross: "الإجمالي", colDeductions: "الاستقطاعات",
        colNet: "الصافي", colStatus: "الحالة", colAcct: "المحاسبة", open: "فتح", noRuns: "لا مسيرات بعد. اختر الشهر واضغط «توليد المسير».",
        st_draft: "مسودة", st_approved: "معتمد", st_paid: "مدفوع",
        runOf: "مسير شهر", back: "رجوع", refresh: "تحديث من ملفات الموظفين",
        tEmployees: "الموظفون", tGross: "الإجمالي", tDeductions: "الاستقطاعات", tNet: "صافي الرواتب", tGosiEmployer: "تأمينات على المنشأة",
        warnNoIban: "موظفون بلا آيبان: {n} — لن يدخلوا ملف التحويل حتى يكتب الآيبان في ملف الموظف.",
        warnNegative: "صافي سالب عند {n} — راجع الاستقطاعات.",
        colEmployee: "الموظف", colDays: "الأيام", colEarned: "المستحق", colAdditions: "إضافات", colGosi: "التأمينات",
        colAbsence: "غياب وتأخر", colUnpaid: "بلا راتب", colOtherDed: "سلف وخصومات", actions: "الإجراءات",
        edit: "تعديل", payslip: "قسيمة", removeLine: "إخراج من المسير",
        approve: "اعتماد المسير", reopen: "إعادة فتح", markPaid: "تم الدفع", bankFile: "ملف التحويل البنكي",
        bankXlsx: "Excel", bankCsv: "CSV", printSlips: "طباعة كل القسائم", deleteRun: "حذف المسودة",
        empty: "لا موظفين نشطين في هذا الشهر. تأكد أن مرحلة الموظف «على رأس العمل» وأن راتبه مكتوب في ملفه.",
        approveConfirm: "بعد الاعتماد يقفل المسير فلا يعدل سطر فيه. اعتماد؟",
        paidConfirm: "تسجيل المسير مدفوعا نهائي، ويرسل قيده إلى المحاسبة إن كانت مربوطة. متابعة؟",
        acct_pending: "ينتظر الإرسال", acct_sending: "يرسل الآن", acct_sent: "قيد في المحاسبة", acct_failed: "تعذر القيد",
        acct_waiting: "ينتظر اختيار الحسابات", acctRetry: "إعادة الإرسال", acctNone: "-",
        lineEditTitle: "تعديل سطر", fOvertime: "عمل إضافي", fBonus: "مكافأة", fExtraAbsence: "أيام غياب إضافية",
        fAdvance: "خصم سلفة", fOtherDed: "خصومات أخرى", fDaysOverride: "أيام الاستحقاق (فارغ = تلقائي)", fIsSaudi: "سعودي (تأمينات المواطن)",
        fNote: "ملاحظة", save: "حفظ", cancel: "إلغاء", saved: "تم الحفظ.",
        locked: "المسير معتمد أو مدفوع، فلا يعدل.", ownerOnly: "إعادة الفتح للمالك وحده.", notAllowed: "لا تملك صلاحية هذا الإجراء.",
        emptyRun: "المسير فارغ، فلا يعتمد.", badValue: "قيمة غير صحيحة.", genericError: "حدث خطأ، حاول مرة أخرى.",
        setTitle: "إعدادات الرواتب", sGosiTitle: "التأمينات الاجتماعية",
        ratesNote: "النسب الافتراضية: على الموظف السعودي 9.75% وعلى المنشأة 11.75%، وعلى غير السعودي 2% أخطار مهنية على المنشأة، والوعاء الأساسي مع السكن بسقف 45,000. نسبة المعاش للمنضمين بعد يوليو 2024 تتدرج سنويا، فراجعها مع التأمينات قبل أول مسير حقيقي.",
        sGosiSaudiEmp: "على الموظف السعودي %", sGosiSaudiEr: "على المنشأة للسعودي %", sGosiNonEmp: "على الموظف غير السعودي %",
        sGosiNonEr: "على المنشأة لغير السعودي %", sGosiCap: "سقف الوعاء", sIncludeHousing: "السكن داخل الوعاء",
        sHours: "ساعات العمل في اليوم", sDeductLate: "خصم التأخر", sBankTitle: "التحويل البنكي",
        sMolId: "رقم المنشأة في مدد", sEmployerIban: "آيبان المنشأة",
        sAccountsTitle: "حسابات قيد الرواتب", sAccountsHint: "يرسل المسير المدفوع قيد يومية واحدا إلى قيود بهذه الحسابات.",
        notConnected: "لا ربط محاسبي لهذا الحساب. اربطه من الإعدادات ← الربط المحاسبي لترسل القيود.",
        adminOnlySettings: "الإعدادات يحفظها المالك أو المشرف.",
        aSalariesExpense: "مصروف الرواتب", aGosiExpense: "مصروف التأمينات", aGosiPayable: "التأمينات المستحقة",
        aSalariesPayable: "الرواتب المستحقة", aAdvances: "سلف الموظفين", choose: "اختر",
        slipTitle: "قسيمة راتب", slipEarnings: "المستحقات", slipDeductions: "الاستقطاعات", slipNet: "صافي الراتب",
        basic: "الراتب الأساسي", housing: "بدل السكن", transport: "بدل النقل", otherAllow: "بدلات أخرى",
        overtime: "عمل إضافي", bonus: "مكافأة", gosi: "التأمينات الاجتماعية", absence: "غياب", late: "تأخر",
        unpaidLeave: "إجازة بلا راتب", advance: "سلفة", otherDed: "خصومات أخرى", daysPaid: "أيام الاستحقاق",
        idNumber: "رقم الهوية", empNumber: "الرقم الوظيفي", iban: "الآيبان", riyal: "ريال",
        bankCols: ["الاسم", "رقم الهوية", "الرقم الوظيفي", "رمز البنك", "الآيبان", "الأساسي", "السكن", "بدلات أخرى", "الاستقطاعات", "الصافي"],
        bankNote: "رمز البنك مأخوذ من الآيبان. تحقق من قالب بنكك أو مدد قبل الرفع."
      },
      en: {
        title: "Payroll", payTitle: "Payroll",
        payIntro: "Each month's payroll is built from employee files: salary and monthly allowances, social insurance computed automatically, unpaid leave, and absence and lateness from attendance. An owner or admin approves it and it locks; then the bank file and payslips are issued, and it is booked in accounting once paid.",
        month: "Month", generate: "Generate payroll", settingsBtn: "Settings",
        runsTitle: "Payroll runs", colMonth: "Month", colEmployees: "Employees", colGross: "Gross", colDeductions: "Deductions",
        colNet: "Net", colStatus: "Status", colAcct: "Accounting", open: "Open", noRuns: "No payroll yet. Pick a month and press “Generate payroll”.",
        st_draft: "Draft", st_approved: "Approved", st_paid: "Paid",
        runOf: "Payroll for", back: "Back", refresh: "Refresh from employee files",
        tEmployees: "Employees", tGross: "Gross", tDeductions: "Deductions", tNet: "Net payroll", tGosiEmployer: "Employer insurance",
        warnNoIban: "Employees without IBAN: {n} — they stay out of the bank file until the IBAN is added to the employee file.",
        warnNegative: "Negative net for {n} — review the deductions.",
        colEmployee: "Employee", colDays: "Days", colEarned: "Earned", colAdditions: "Additions", colGosi: "Insurance",
        colAbsence: "Absence & late", colUnpaid: "Unpaid", colOtherDed: "Advances & other", actions: "Actions",
        edit: "Edit", payslip: "Payslip", removeLine: "Remove from payroll",
        approve: "Approve payroll", reopen: "Reopen", markPaid: "Mark paid", bankFile: "Bank transfer file",
        bankXlsx: "Excel", bankCsv: "CSV", printSlips: "Print all payslips", deleteRun: "Delete draft",
        empty: "No active employees this month. Make sure the employee stage is “Active” and the salary is in the file.",
        approveConfirm: "After approval the payroll locks and no line can be edited. Approve?",
        paidConfirm: "Marking the payroll paid is final, and its entry is sent to accounting if connected. Continue?",
        acct_pending: "Waiting to send", acct_sending: "Sending", acct_sent: "Booked in accounting", acct_failed: "Booking failed",
        acct_waiting: "Waiting for accounts", acctRetry: "Send again", acctNone: "-",
        lineEditTitle: "Edit line", fOvertime: "Overtime", fBonus: "Bonus", fExtraAbsence: "Extra absence days",
        fAdvance: "Advance deduction", fOtherDed: "Other deductions", fDaysOverride: "Paid days (empty = automatic)", fIsSaudi: "Saudi (citizen insurance)",
        fNote: "Note", save: "Save", cancel: "Cancel", saved: "Saved.",
        locked: "The payroll is approved or paid, so it cannot be edited.", ownerOnly: "Only the owner can reopen.", notAllowed: "You do not have permission for this action.",
        emptyRun: "The payroll is empty and cannot be approved.", badValue: "Invalid value.", genericError: "Something went wrong. Please try again.",
        setTitle: "Payroll settings", sGosiTitle: "Social insurance (GOSI)",
        ratesNote: "Defaults: 9.75% on Saudi employees and 11.75% on the employer, 2% occupational hazards on the employer for non-Saudis, on basic plus housing capped at 45,000. The pension rate for those who joined after July 2024 rises yearly, so confirm it with GOSI before the first real run.",
        sGosiSaudiEmp: "Saudi employee %", sGosiSaudiEr: "Employer for Saudis %", sGosiNonEmp: "Non-Saudi employee %",
        sGosiNonEr: "Employer for non-Saudis %", sGosiCap: "Contribution cap", sIncludeHousing: "Housing in the base",
        sHours: "Working hours per day", sDeductLate: "Deduct lateness", sBankTitle: "Bank transfer",
        sMolId: "Establishment number in Mudad", sEmployerIban: "Establishment IBAN",
        sAccountsTitle: "Payroll entry accounts", sAccountsHint: "A paid payroll sends one journal entry to Qoyod with these accounts.",
        notConnected: "No accounting link for this account. Connect it from Settings → Accounting to send entries.",
        adminOnlySettings: "Settings are saved by the owner or an admin.",
        aSalariesExpense: "Salaries expense", aGosiExpense: "Insurance expense", aGosiPayable: "Insurance payable",
        aSalariesPayable: "Salaries payable", aAdvances: "Employee advances", choose: "Choose",
        slipTitle: "Payslip", slipEarnings: "Earnings", slipDeductions: "Deductions", slipNet: "Net pay",
        basic: "Basic salary", housing: "Housing allowance", transport: "Transport allowance", otherAllow: "Other allowances",
        overtime: "Overtime", bonus: "Bonus", gosi: "Social insurance", absence: "Absence", late: "Lateness",
        unpaidLeave: "Unpaid leave", advance: "Advance", otherDed: "Other deductions", daysPaid: "Paid days",
        idNumber: "ID number", empNumber: "Employee number", iban: "IBAN", riyal: "SAR",
        bankCols: ["Name", "ID number", "Employee number", "Bank code", "IBAN", "Basic", "Housing", "Other allowances", "Deductions", "Net"],
        bankNote: "The bank code is taken from the IBAN. Check your bank or Mudad template before uploading."
      },
      fr: {
        title: "Paie", payTitle: "Paie",
        payIntro: "La paie de chaque mois est construite à partir des fiches des employés : salaire et indemnités mensuelles, assurance sociale calculée automatiquement, congés sans solde, absences et retards issus des présences. Le propriétaire ou un admin l'approuve et elle se verrouille ; puis le fichier bancaire et les bulletins sont émis, et elle est comptabilisée une fois payée.",
        month: "Mois", generate: "Générer la paie", settingsBtn: "Paramètres",
        runsTitle: "Paies", colMonth: "Mois", colEmployees: "Employés", colGross: "Brut", colDeductions: "Retenues",
        colNet: "Net", colStatus: "Statut", colAcct: "Comptabilité", open: "Ouvrir", noRuns: "Aucune paie. Choisissez le mois et appuyez sur « Générer la paie ».",
        st_draft: "Brouillon", st_approved: "Approuvée", st_paid: "Payée",
        runOf: "Paie de", back: "Retour", refresh: "Actualiser depuis les fiches",
        tEmployees: "Employés", tGross: "Brut", tDeductions: "Retenues", tNet: "Net à payer", tGosiEmployer: "Assurance employeur",
        warnNoIban: "Employés sans IBAN : {n} — exclus du fichier bancaire tant que l'IBAN manque dans la fiche.",
        warnNegative: "Net négatif pour {n} — vérifiez les retenues.",
        colEmployee: "Employé", colDays: "Jours", colEarned: "Acquis", colAdditions: "Ajouts", colGosi: "Assurance",
        colAbsence: "Absences et retards", colUnpaid: "Sans solde", colOtherDed: "Avances et autres", actions: "Actions",
        edit: "Modifier", payslip: "Bulletin", removeLine: "Retirer de la paie",
        approve: "Approuver la paie", reopen: "Rouvrir", markPaid: "Marquer payée", bankFile: "Fichier de virement",
        bankXlsx: "Excel", bankCsv: "CSV", printSlips: "Imprimer tous les bulletins", deleteRun: "Supprimer le brouillon",
        empty: "Aucun employé actif ce mois-ci. Vérifiez que l'étape est « En poste » et que le salaire figure dans la fiche.",
        approveConfirm: "Après approbation, la paie est verrouillée et aucune ligne ne peut être modifiée. Approuver ?",
        paidConfirm: "Marquer la paie payée est définitif, et son écriture est envoyée à la comptabilité si elle est liée. Continuer ?",
        acct_pending: "En attente d'envoi", acct_sending: "Envoi en cours", acct_sent: "Comptabilisée", acct_failed: "Échec de l'écriture",
        acct_waiting: "En attente des comptes", acctRetry: "Renvoyer", acctNone: "-",
        lineEditTitle: "Modifier la ligne", fOvertime: "Heures supplémentaires", fBonus: "Prime", fExtraAbsence: "Jours d'absence en plus",
        fAdvance: "Retenue d'avance", fOtherDed: "Autres retenues", fDaysOverride: "Jours payés (vide = automatique)", fIsSaudi: "Saoudien (assurance citoyen)",
        fNote: "Note", save: "Enregistrer", cancel: "Annuler", saved: "Enregistré.",
        locked: "La paie est approuvée ou payée, elle ne peut pas être modifiée.", ownerOnly: "Seul le propriétaire peut rouvrir.", notAllowed: "Vous n'avez pas l'autorisation pour cette action.",
        emptyRun: "La paie est vide et ne peut pas être approuvée.", badValue: "Valeur invalide.", genericError: "Une erreur s'est produite. Réessayez.",
        setTitle: "Paramètres de paie", sGosiTitle: "Assurance sociale (GOSI)",
        ratesNote: "Par défaut : 9,75 % pour l'employé saoudien et 11,75 % pour l'employeur, 2 % risques professionnels à l'employeur pour les non-Saoudiens, sur le salaire de base plus le logement plafonné à 45 000. Le taux de retraite pour les adhérents après juillet 2024 augmente chaque année : vérifiez-le auprès de la GOSI avant la première paie réelle.",
        sGosiSaudiEmp: "Employé saoudien %", sGosiSaudiEr: "Employeur pour Saoudiens %", sGosiNonEmp: "Employé non saoudien %",
        sGosiNonEr: "Employeur pour non-Saoudiens %", sGosiCap: "Plafond de cotisation", sIncludeHousing: "Logement dans l'assiette",
        sHours: "Heures de travail par jour", sDeductLate: "Retenir les retards", sBankTitle: "Virement bancaire",
        sMolId: "Numéro d'établissement Mudad", sEmployerIban: "IBAN de l'établissement",
        sAccountsTitle: "Comptes de l'écriture de paie", sAccountsHint: "Une paie payée envoie une écriture de journal à Qoyod avec ces comptes.",
        notConnected: "Aucune liaison comptable pour ce compte. Liez-la depuis Paramètres → Comptabilité pour envoyer les écritures.",
        adminOnlySettings: "Les paramètres sont enregistrés par le propriétaire ou un admin.",
        aSalariesExpense: "Charges de salaires", aGosiExpense: "Charges d'assurance", aGosiPayable: "Assurance à payer",
        aSalariesPayable: "Salaires à payer", aAdvances: "Avances au personnel", choose: "Choisir",
        slipTitle: "Bulletin de paie", slipEarnings: "Gains", slipDeductions: "Retenues", slipNet: "Net à payer",
        basic: "Salaire de base", housing: "Indemnité de logement", transport: "Indemnité de transport", otherAllow: "Autres indemnités",
        overtime: "Heures supplémentaires", bonus: "Prime", gosi: "Assurance sociale", absence: "Absence", late: "Retard",
        unpaidLeave: "Congé sans solde", advance: "Avance", otherDed: "Autres retenues", daysPaid: "Jours payés",
        idNumber: "Numéro d'identité", empNumber: "Matricule", iban: "IBAN", riyal: "SAR",
        bankCols: ["Nom", "Numéro d'identité", "Matricule", "Code banque", "IBAN", "Base", "Logement", "Autres indemnités", "Retenues", "Net"],
        bankNote: "Le code banque est tiré de l'IBAN. Vérifiez le modèle de votre banque ou de Mudad avant l'envoi."
      },
      ur: {
        title: "پے رول", payTitle: "پے رول",
        payIntro: "ہر مہینے کا پے رول ملازمین کی فائلوں سے بنتا ہے: تنخواہ اور ماہانہ الاؤنس، سماجی بیمہ خودکار، بغیر تنخواہ چھٹی، اور حاضری سے غیر حاضری اور تاخیر۔ مالک یا منتظم منظور کرے تو یہ مقفل ہو جاتا ہے، پھر بینک فائل اور پے سلپ جاری ہوتی ہیں، اور ادائیگی پر اکاؤنٹنگ میں درج ہوتا ہے۔",
        month: "مہینہ", generate: "پے رول بنائیں", settingsBtn: "ترتیبات",
        runsTitle: "پے رول", colMonth: "مہینہ", colEmployees: "ملازمین", colGross: "کل", colDeductions: "کٹوتیاں",
        colNet: "خالص", colStatus: "حالت", colAcct: "اکاؤنٹنگ", open: "کھولیں", noRuns: "ابھی کوئی پے رول نہیں۔ مہینہ منتخب کر کے «پے رول بنائیں» دبائیں۔",
        st_draft: "مسودہ", st_approved: "منظور", st_paid: "ادا شدہ",
        runOf: "پے رول برائے", back: "واپس", refresh: "ملازمین کی فائلوں سے تازہ کریں",
        tEmployees: "ملازمین", tGross: "کل", tDeductions: "کٹوتیاں", tNet: "خالص تنخواہیں", tGosiEmployer: "ادارے کا بیمہ",
        warnNoIban: "بغیر IBAN ملازمین: {n} — فائل میں IBAN لکھے جانے تک بینک فائل سے باہر رہیں گے۔",
        warnNegative: "{n} کی خالص رقم منفی ہے — کٹوتیاں دیکھیں۔",
        colEmployee: "ملازم", colDays: "دن", colEarned: "واجب", colAdditions: "اضافے", colGosi: "بیمہ",
        colAbsence: "غیر حاضری و تاخیر", colUnpaid: "بغیر تنخواہ", colOtherDed: "پیشگی و دیگر", actions: "اقدامات",
        edit: "ترمیم", payslip: "پے سلپ", removeLine: "پے رول سے نکالیں",
        approve: "پے رول منظور کریں", reopen: "دوبارہ کھولیں", markPaid: "ادا شدہ", bankFile: "بینک منتقلی فائل",
        bankXlsx: "Excel", bankCsv: "CSV", printSlips: "تمام پے سلپ پرنٹ کریں", deleteRun: "مسودہ حذف کریں",
        empty: "اس مہینے کوئی فعال ملازم نہیں۔ یقینی بنائیں کہ ملازم کا مرحلہ «برسرِ کار» ہے اور تنخواہ فائل میں درج ہے۔",
        approveConfirm: "منظوری کے بعد پے رول مقفل ہو جائے گا اور کوئی سطر نہیں بدلے گی۔ منظور کریں؟",
        paidConfirm: "پے رول کو ادا شدہ کرنا حتمی ہے، اور اکاؤنٹنگ جڑی ہو تو اس کا اندراج بھیجا جائے گا۔ جاری رکھیں؟",
        acct_pending: "بھیجنے کا انتظار", acct_sending: "بھیجا جا رہا ہے", acct_sent: "اکاؤنٹنگ میں درج", acct_failed: "اندراج ناکام",
        acct_waiting: "اکاؤنٹس کے انتخاب کا انتظار", acctRetry: "دوبارہ بھیجیں", acctNone: "-",
        lineEditTitle: "سطر میں ترمیم", fOvertime: "اوور ٹائم", fBonus: "بونس", fExtraAbsence: "اضافی غیر حاضر دن",
        fAdvance: "پیشگی کی کٹوتی", fOtherDed: "دیگر کٹوتیاں", fDaysOverride: "واجب دن (خالی = خودکار)", fIsSaudi: "سعودی (شہری بیمہ)",
        fNote: "نوٹ", save: "محفوظ کریں", cancel: "منسوخ", saved: "محفوظ ہو گیا۔",
        locked: "پے رول منظور یا ادا شدہ ہے، اس میں ترمیم نہیں ہو سکتی۔", ownerOnly: "صرف مالک دوبارہ کھول سکتا ہے۔", notAllowed: "آپ کو اس عمل کی اجازت نہیں۔",
        emptyRun: "پے رول خالی ہے، منظور نہیں ہو سکتا۔", badValue: "غلط قدر۔", genericError: "کچھ غلط ہو گیا، دوبارہ کوشش کریں۔",
        setTitle: "پے رول کی ترتیبات", sGosiTitle: "سماجی بیمہ (GOSI)",
        ratesNote: "طے شدہ: سعودی ملازم پر 9.75% اور ادارے پر 11.75%، غیر سعودی کے لیے ادارے پر 2% پیشہ ورانہ خطرات، بنیادی جمع رہائش پر 45,000 کی حد کے ساتھ۔ جولائی 2024 کے بعد شامل ہونے والوں کی پنشن شرح ہر سال بڑھتی ہے، پہلے حقیقی پے رول سے پہلے GOSI سے تصدیق کریں۔",
        sGosiSaudiEmp: "سعودی ملازم %", sGosiSaudiEr: "سعودی کے لیے ادارہ %", sGosiNonEmp: "غیر سعودی ملازم %",
        sGosiNonEr: "غیر سعودی کے لیے ادارہ %", sGosiCap: "بیمہ کی حد", sIncludeHousing: "رہائش بیمہ کی بنیاد میں",
        sHours: "روزانہ کام کے گھنٹے", sDeductLate: "تاخیر کی کٹوتی", sBankTitle: "بینک منتقلی",
        sMolId: "مدد میں ادارے کا نمبر", sEmployerIban: "ادارے کا IBAN",
        sAccountsTitle: "پے رول اندراج کے اکاؤنٹس", sAccountsHint: "ادا شدہ پے رول ان اکاؤنٹس کے ساتھ قیود کو ایک روزنامچہ اندراج بھیجتا ہے۔",
        notConnected: "اس اکاؤنٹ کا اکاؤنٹنگ ربط نہیں۔ اندراج بھیجنے کے لیے ترتیبات ← اکاؤنٹنگ سے جوڑیں۔",
        adminOnlySettings: "ترتیبات مالک یا منتظم محفوظ کرتا ہے۔",
        aSalariesExpense: "تنخواہوں کا خرچ", aGosiExpense: "بیمہ کا خرچ", aGosiPayable: "واجب الادا بیمہ",
        aSalariesPayable: "واجب الادا تنخواہیں", aAdvances: "ملازمین کی پیشگیاں", choose: "منتخب کریں",
        slipTitle: "پے سلپ", slipEarnings: "آمدنی", slipDeductions: "کٹوتیاں", slipNet: "خالص تنخواہ",
        basic: "بنیادی تنخواہ", housing: "رہائشی الاؤنس", transport: "سفری الاؤنس", otherAllow: "دیگر الاؤنس",
        overtime: "اوور ٹائم", bonus: "بونس", gosi: "سماجی بیمہ", absence: "غیر حاضری", late: "تاخیر",
        unpaidLeave: "بغیر تنخواہ چھٹی", advance: "پیشگی", otherDed: "دیگر کٹوتیاں", daysPaid: "واجب دن",
        idNumber: "شناختی نمبر", empNumber: "ملازم نمبر", iban: "IBAN", riyal: "ریال",
        bankCols: ["نام", "شناختی نمبر", "ملازم نمبر", "بینک کوڈ", "IBAN", "بنیادی", "رہائش", "دیگر الاؤنس", "کٹوتیاں", "خالص"],
        bankNote: "بینک کوڈ IBAN سے لیا گیا ہے۔ اپ لوڈ سے پہلے اپنے بینک یا مدد کا سانچہ دیکھیں۔"
      }
    };
    Object.keys(PAYROLL_I18N).forEach(function (k) { if (translations[k]) Object.assign(translations[k], PAYROLL_I18N[k]); });

