        wizBack: "پچھلا",
        wizNext: "اگلا",
        fCode: "کوڈ",
        contextTitle: "سیاق",
        inputsTitle: "داخل",
        outputsTitle: "نتائج",
        sendToReview: "جائزے کے لیے بھیجیں",
        approvePublish: "منظور اور شائع کریں",
        requestChanges: "تبدیلیاں طلب کریں",
        rejectProc: "مسترد",
        unpublish: "اشاعت ہٹائیں",
        continueEditing: "ترمیم جاری رکھیں",
        awaitingYou: "یہ طریقہ کار آپ کی منظوری کا منتظر ہے۔ خاکہ اور میٹرکس دیکھ کر منظور کریں یا تبدیلی طلب کریں۔",
        changesAsked: "اس مسودے پر تبدیلیاں طلب کی گئی ہیں۔",
        reviewNoteLabel: "نوٹ",
        askChangesPrompt: "کیا تبدیل کرنا ہے؟",
        noProcesses: "اس شعبے میں کوئی طریقہ کار نہیں۔",
        stepsCount: "مراحل",
        ownerLabel: "ذمہ دار",
        authorLabel: "بنانے والا",
        areaLabel: "شعبہ",
        freqLabel: "تکرار",
        fCase: "مقدمہ",
        title: "طریقہ کار لائبریری",
        libTitle: "طریقہ کار لائبریری",
        libIntro: "دفتر کے منظور شدہ قانونی طریقہ کار مرحلہ وار: کون کیا کرتا ہے (RACI)، آغاز کیا ہے اور نتیجہ کیا۔",
        newProcess: "＋ نیا طریقہ کار",
        colCode: "کوڈ",
        colName: "طریقہ کار",
        colArea: "شعبہ",
        colOwner: "ذمہ دار",
        colSteps: "مراحل",
        colStatus: "حالت",
        libEmpty: "ابھی کوئی طریقہ کار نہیں۔",
        editorNew: "نیا طریقہ کار",
        editorEdit: "ترمیم",
        fName: "نام",
        fArea: "شعبہ",
        fOwner: "ذمہ دار",
        fFrequency: "تکرار",
        fTrigger: "محرک",
        fStatus: "حالت",
        fInputs: "ان پٹ",
        fOutputs: "آؤٹ پٹ",
        fDescription: "تفصیل",
        stepsTitle: "مراحل",
        addStep: "＋ مرحلہ",
        noMembersYet: "پہلے ٹیم کے صفحے سے اپنی ٹیم کو مدعو کریں",
        stepType: "قسم",
        typeTask: "کام",
        typeDecision: "فیصلہ (ہاں/نہیں)",
        stepTitle: "مرحلہ",
        stepNote: "نوٹ",
        raci_R: "انجام دہندہ",
        raci_A: "جواب دہ",
        raci_C: "مشاورت",
        raci_I: "اطلاع",
        yesTo: "ہاں → مرحلہ",
        noTo: "نہیں → مرحلہ",
        moveUp: "اوپر",
        moveDown: "نیچے",
        raciTitle: "RACI میٹرکس",
        flowTitle: "فلو چارٹ",
        yes: "ہاں",
        no: "نہیں",
        noSteps: "کوئی مرحلہ نہیں۔",
        edit: "ترمیم",
        back: "واپس",
        save: "محفوظ",
        cancel: "منسوخ",
        none: "—",
        allAreas: "تمام شعبے",
        saveFailed: "محفوظ نہیں ہو سکا۔",
        deleteConfirm: "مستقل حذف کریں؟",
        area_lawsuits: "مقدمات",
        area_violations: "خلاف ورزیاں",
        area_contracts: "معاہدے",
        area_licenses: "لائسنس",
        area_documents: "دستاویزات",
        area_other: "دیگر",
        status_draft: "مسودہ",
        status_review: "زیر جائزہ",
        status_published: "منظور",
        status_archived: "محفوظ شدہ",
        docAddTitle: "دستاویز شامل کریں",
        docAddIntro: "کمرشل رجسٹر، ٹیکس سرٹیفکیٹ، لائسنس، دعوی یا کوئی بھی دستاویز (PDF یا تصویر) اپ لوڈ کریں؛ نظام اسے پڑھ کر قسم، نمبر اور میعاد نکالتا ہے اور ٹریکنگ و یاد دہانی میں شامل کرتا ہے۔",
        docDropHint: "دستاویز یہاں ڈالیں یا فائل چنیں",
        docChoose: "فائل چنیں",
        docKind: "دستاویز کی قسم",
        docTitleField: "عنوان",
        docNumber: "دستاویز نمبر",
        docIssuer: "جاری کنندہ",
        docParty: "کمپنی / مالک",
        docIssueDate: "اجرا کی تاریخ",
        docExpiry: "میعاد / مقررہ تاریخ",
        docAmount: "رقم (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "مقدمہ نمبر",
        docCourt: "عدالت",
        docSave: "محفوظ کریں اور ٹریک کریں",
        docListTitle: "کمپنی کی دستاویزات",
        docLeft: "باقی",
        docFiles: "فائلیں",
        docsEmpty: "ابھی کوئی دستاویز نہیں۔",
        docReading: "دستاویز پڑھی جا رہی ہے...",
        docOcr: "تصویری دستاویز — AI سے پڑھی جا رہی ہے...",
        docReady: "پڑھ لی گئی — خانے جانچ کر محفوظ کریں۔",
        docFailed: "پڑھی نہیں جا سکی؛ واضح فائل آزمائیں۔",
        docSaving: "محفوظ ہو رہا ہے...",
        docSaved: "محفوظ ہو کر ٹریکنگ میں شامل ہو گئی۔",
        docFileFailed: "ڈیٹا محفوظ ہوا مگر فائل اپ لوڈ نہیں ہو سکی۔",
        docStorageLimit: "ڈیٹا محفوظ ہوا مگر پیکج کی اسٹوریج بھر گئی۔",
        docExpired: "ختم",
        docDays: "دن",
        docDeleteConfirm: "دستاویز اور فائلیں مستقل حذف کریں؟",
        allKinds: "تمام اقسام",
        search: "تلاش",
        actions: "کارروائیاں",
        delete: "حذف",
        confirmDeleteStep: "یہ مرحلہ حذف کریں؟",
        unavailable: "خدمت دستیاب نہیں۔",
        kind_commercial_register: "کمرشل رجسٹر",
        kind_vat_certificate: "ٹیکس سرٹیفکیٹ",
        kind_license: "لائسنس",
        kind_contract: "معاہدہ",
        kind_case_filing: "دعوی / دستاویزات",
        kind_court_ruling: "عدالتی فیصلہ",
        kind_hearing_notice: "سماعت کا نوٹس",
        kind_violation: "خلاف ورزی",
        kind_invoice: "انوائس",
        kind_power_of_attorney: "مختار نامہ",
        kind_id_document: "شناختی دستاویز",
        kind_other: "دیگر دستاویز",
        intro: "اپنی ٹیم کے اراکین شامل کریں، ان کے کردار طے کریں اور زیر التوا دعوتوں پر نظر رکھیں۔",
        backBtn: "ڈیش بورڈ پر واپس جائیں",
        serviceUnavailableTitle: "سروس تیار کی جا رہی ہے",
        serviceUnavailableText: "ہم سروس تیار کر رہے ہیں، براہ کرم بعد میں دوبارہ کوشش کریں۔",
        noOrg: "کوئی کمپنی منتخب نہیں، پہلے اپنی کمپنی بنائیں۔",
        noOrgHint: "اپنی کمپنی بنانے کے لیے ڈیش بورڈ پر جائیں، پھر اس صفحے پر واپس آئیں۔",
        loading: "لوڈ ہو رہا ہے...",
        loadError: "ٹیم کا ڈیٹا لوڈ نہیں ہو سکا، براہ کرم دوبارہ کوشش کریں۔",
        membersTitle: "ٹیم کے اراکین",
        membersEmpty: "ابھی کوئی رکن نہیں ہے۔",
        readOnlyNote: "صرف مالک اور منتظمین اراکین اور دعوتوں کا انتظام کر سکتے ہیں۔",
        capacityLimited: "اراکین: {limit} میں سے {used}",
        capacityUnlimited: "اراکین: {used} (لامحدود)",
        capacityPending: "زیر التوا دعوتیں: {n}",
        capacityFull: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں۔",
        upgradeLink: "پلان اپ گریڈ کریں",
        roleOwner: "مالک",
        roleAdmin: "منتظم",
        roleMember: "رکن",
        roleLabel: "کردار",
        statusInvited: "سائن ان کا انتظار",
        you: "آپ",
        emailLabel: "ای میل",
        joinedLabel: "شمولیت کی تاریخ",
        changeRoleLabel: "کردار تبدیل کریں",
        removeBtn: "ہٹائیں",
        confirmRemove: "کیا آپ {name} کو ٹیم سے ہٹانا چاہتے ہیں؟",
        memberRemoved: "رکن ہٹا دیا گیا۔",
        roleUpdated: "کردار اپ ڈیٹ ہو گیا۔",
        inviteTitle: "نئے رکن کو دعوت دیں",
        inviteIntro: "رکن کا ای میل درج کریں اور اس کا کردار منتخب کریں۔ اگر وہ پلیٹ فارم پر رجسٹرڈ ہے تو اسے فورا بیل میں اطلاع ملے گی، اور ایپ کھولتے ہی ٹیم میں شامل ہو جائے گا۔ ورنہ اسے سائن ان لنک بھیجیں:",
        copyLinkBtn: "سائن ان لنک کاپی کریں",
        linkCopied: "لنک کاپی ہو گیا۔",
        inviteEmailPlaceholder: "رکن کا ای میل ایڈریس",
        inviteBtn: "دعوت دیں",
        lookupTitle: "یا رجسٹرڈ صارفین میں سے",
        inviteByEmailTitle: "ای میل سے",
        lookupBtn: "صارفین دکھائیں",
        lookupPlaceholder: "ای میل، موبائل یا صارف نمبر",
        lookupNone: "کوئی صارف نہیں ملا۔ آپ ای میل سے دعوت دے سکتے ہیں۔",
        inviteSending: "شامل کیا جا رہا ہے...",
        inviteCreated: "{email} کے لیے دعوت شامل کر دی گئی، سائن ان کرتے ہی وہ خود بخود شامل ہو جائے گا۔",
        workloadTitle: "کام کی تقسیم",
        workloadIntro: "کام کو رکن پر گھسیٹیں۔",
        rasiTitle: "RASI میٹرکس",
        rasiIntro: "ہر مقدمے، خلاف ورزی یا کام کے لیے: کون کرتا ہے (R)، کون منظور اور جواب دہ ہے (A — صرف ایک)، کون معاونت کرتا ہے (S)، کسے مطلع رکھا جائے (I)۔ کردار بدلنے کے لیے خانہ دبائیں؛ متعلقہ شخص کو فورا اطلاع ملتی ہے۔",
        rasiLegendR: "ذمہ دار",
        rasiLegendA: "منظور کنندہ",
        rasiLegendS: "معاون",
        rasiLegendI: "مطلع",
        rasiSearch: "عنوان یا نمبر سے تلاش",
        rasiEmpty: "دکھانے کے لیے کوئی کھلا آئٹم نہیں۔",
        rasiItemCol: "آئٹم",
        rasiSaved: "کردار محفوظ ہو گیا۔",
        rasiNoMembers: "پہلے ٹیم میں ارکان شامل کریں۔",
        quickTitle: "فوری تقسیم",
        quickHint: "آئٹم پر رکن کا نام دبائیں: ایک بار = ذمہ دار (R) اور آپ خود بخود منظور کنندہ (A)، دوسری بار = معاون (S)، تیسری بار = ہٹائیں۔",
        rasiShowMatrix: "مکمل میٹرکس دکھائیں",
        rasiHideMatrix: "میٹرکس چھپائیں",
        quickAddTitle: "فوری اندراج",
        quickAddHint: "جیسے آپ کہتے ہیں ویسے لکھیں: «مقدمہ 4521 کی سماعت، الابراج، اتوار 10 بجے، احمد کے لیے» — قسم، تاریخ، کلائنٹ، مقدمہ نمبر اور ذمہ دار سمجھ کر ایک ہی بار میں درج اور تقسیم ہو جاتا ہے۔",
        quickAddBtn: "شامل کریں",
        quickAddPh: "کام، ذمہ دار اور وقت لکھیں…",
        quickAddNobody: "ابھی کوئی ذمہ دار نہیں",
        quickAddParsing: "سمجھ رہا ہوں…",
        quickAddDone: "«{title}» درج ہو گیا{who}۔",
        quickAddNoTitle: "اس متن سے کوئی کام سمجھ نہیں آیا — کم از کم عنوان لکھیں۔",
        quickAddNeedsParent: "یہ کام کس مقدمے یا خلاف ورزی سے متعلق ہے؟ — کوئی کام الگ نہیں۔",
        quickAddLink: "منسلک کریں اور درج کریں",
        unassignedTitle: "بغیر ذمہ دار کام",
        unassignedEmpty: "تمام کام تفویض ہو چکے ہیں۔",
        wlOpen: "جاری",
        wlOverdue: "تاخیر شدہ",
        wlDone: "مکمل",
        assignTo: "تفویض کریں",
        assignPick: "رکن منتخب کریں",
        assignDone: "{name} کے سپرد کر دیا گیا۔",
        unassign: "بغیر ذمہ دار",
        noDue: "کوئی تاریخ نہیں",
        chatTitle: "ٹیم رابطہ",
        chatThreads: "گفتگوئیں",
        chatTeam: "پوری ٹیم",
        chatTeamHint: "سب کو",
        chatPrivate: "نجی",
        chatPlaceholder: "پیغام لکھیں... (Enter بھیجنے کے لیے، Shift+Enter نئی سطر)",
        chatSend: "بھیجیں",
        chatSendFile: "فائل بھیجیں",
        chatCancel: "منسوخ",
        chatFiles: "📁 فائلیں",
        chatFilesEmpty: "اس گفتگو میں ابھی کوئی فائل نہیں۔",
        chatDownload: "ڈاؤن لوڈ",
        chatFileNoLink: "کسی مقدمے سے منسلک نہیں",
        chatFileTooBig: "فائل 25 MB سے بڑی ہے۔",
        chatUploading: "اپ لوڈ ہو رہی ہے…",
        chatEmpty: "ابھی کوئی پیغام نہیں۔",
        chatLoadError: "پیغامات لوڈ نہیں ہو سکے۔",
        chatDelete: "حذف کریں",
        chatConfirmDelete: "یہ پیغام حذف کریں؟",
        chatUnread: "{n} نئے",
        chatToday: "آج",
        chatLive: "لائیو",
        chatOffline: "دوبارہ جوڑا جا رہا ہے...",
        invitationsTitle: "زیر التوا دعوتیں",
        invitationsEmpty: "کوئی زیر التوا دعوت نہیں۔",
        invitedOn: "شامل کی گئی: {date}",
        cancelInviteBtn: "منسوخ کریں",
        confirmCancelInvite: "کیا آپ {email} کی دعوت منسوخ کرنا چاہتے ہیں؟",
        inviteCancelled: "دعوت منسوخ کر دی گئی۔",
        invalidEmail: "درست ای میل ایڈریس درج کریں۔",
        alreadyMember: "یہ ای میل پہلے ہی ٹیم کے ایک رکن کا ہے۔",
        alreadyInvited: "اس ای میل کے لیے پہلے ہی ایک دعوت زیر التوا ہے۔",
        notAllowed: "آپ کو یہ کارروائی کرنے کی اجازت نہیں ہے۔",
        genericError: "کچھ غلط ہو گیا، براہ کرم دوبارہ کوشش کریں۔",
        planLimitMembers: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        loginLink: "سائن ان",
        dashboardLink: "ڈیش بورڈ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };

