-- الترحيل كما طبق على Supabase (version 20260905224556, name packs_departments_hr_finance_sales_procurement_marketing_design); اضيف الى المستودع 2026-09-11 لسد فجوة الترحيلات
-- ست واجهات أخرى بأمر المهندس رعد 2026-09-06: موارد بشرية، مالية، مبيعات، مشتريات، تسويق، تصاميم.
-- كلها صفوف بيانات فوق النواة نفسها (لوحة + مصاريف + مستندات + إعدادات) — لا سطر شيفرة واحد.
insert into public.ui_packs (key, names, hints, icon, sort_order, entity_default, entity_choices, labels, active, is_default) values
 ('trainer',
  '{"ar":"مدرب أو محاضر","en":"Trainer or lecturer","fr":"Formateur ou conferencier","ur":"ٹرینر یا لیکچرار"}',
  '{"ar":"دوراتك وجلساتها ومتدربوك وشهاداتك وفواتيرك","en":"Your courses, sessions, attendees, certificates and invoices","fr":"Vos formations, seances, participants, attestations et factures","ur":"آپ کے کورسز، سیشنز، شرکاء، اسناد اور رسیدیں"}',
  'M18 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V4a2 2 0 00-2-2zm0 18H6V4h2v7l2-1.5L12 11V4h6v16z',
  4, 'freelance', '{freelance,establishment,company,individual}',
  '{"fieldClient":{"ar":"الجهة الطالبة","en":"Client organisation","fr":"Organisme demandeur","ur":"درخواست گزار ادارہ"},"fieldCaseNumber":{"ar":"رقم الدورة","en":"Course number","fr":"Numero de formation","ur":"کورس نمبر"}}',
  true, false),
 ('legal',
  '{"ar":"محاماة وإدارة قانونية","en":"Law practice or legal department","fr":"Cabinet ou service juridique","ur":"وکالت یا قانونی شعبہ"}',
  '{"ar":"للمحامي والمكتب والإدارة القانونية: قضايا ومخالفات ومستندات وفريق وإجراءات ومخاطر","en":"For a lawyer, a firm or a legal department: cases, violations, documents, team, processes and risks","fr":"Pour un avocat, un cabinet ou un service juridique : affaires, infractions, documents, equipe","ur":"وکیل، فرم یا قانونی شعبے کے لیے: مقدمات، خلاف ورزیاں، دستاویزات، ٹیم"}',
  'M12 3l9 4v6c0 5.25-3.75 10.15-9 11.5C6.75 23.15 3 18.25 3 13V7l9-4zm-1 6v2H9v2h2v2h2v-2h2v-2h-2V9h-2z',
  3, 'company', '{company,establishment,nonprofit,government,freelance,individual}', '{}', true, true),
 ('hr',
  '{"ar":"موارد بشرية","en":"Human resources","fr":"Ressources humaines","ur":"انسانی وسائل"}',
  '{"ar":"الموظفون وعقودهم ووثائقهم ورواتبهم وإجراءات التوظيف","en":"Employees, contracts, documents, payroll and hiring processes","fr":"Employes, contrats, documents, paie et recrutement","ur":"ملازمین، معاہدے، دستاویزات، تنخواہیں اور بھرتی"}',
  'M16 11c1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3 1.34 3 3 3zm-8 0c1.66 0 3-1.34 3-3S9.66 5 8 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5C15 14.17 10.33 13 8 13zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z',
  7, 'company', '{company,establishment,nonprofit,government}',
  '{"fieldClient":{"ar":"الموظف","en":"Employee","fr":"Employe","ur":"ملازم"},"fieldCaseNumber":{"ar":"الرقم الوظيفي","en":"Employee number","fr":"Matricule","ur":"ملازم نمبر"}}',
  true, false),
 ('finance',
  '{"ar":"مالية","en":"Finance","fr":"Finance","ur":"مالیات"}',
  '{"ar":"المصاريف والإيرادات والفواتير والمستحقات والمخاطر المالية","en":"Expenses, revenue, invoices, dues and financial risks","fr":"Depenses, revenus, factures, echeances et risques financiers","ur":"اخراجات، آمدنی، رسیدیں، واجبات اور مالی خطرات"}',
  'M11.8 10.9c-2.27-.59-3-1.2-3-2.15 0-1.09 1.01-1.85 2.7-1.85 1.78 0 2.44.85 2.5 2.1h2.21c-.07-1.72-1.12-3.3-3.21-3.81V3h-3v2.16c-1.94.42-3.5 1.68-3.5 3.61 0 2.31 1.91 3.46 4.7 4.13 2.5.6 3 1.48 3 2.41 0 .69-.49 1.79-2.7 1.79-2.06 0-2.87-.92-2.98-2.1h-2.2c.12 2.19 1.76 3.42 3.68 3.83V21h3v-2.15c1.95-.37 3.5-1.5 3.5-3.55 0-2.84-2.43-3.81-4.7-4.4z',
  8, 'company', '{company,establishment,freelance,nonprofit,government}',
  '{"fieldClient":{"ar":"الجهة","en":"Party","fr":"Tiers","ur":"ادارہ"},"fieldCaseNumber":{"ar":"رقم المستند المالي","en":"Financial document number","fr":"Numero de piece","ur":"مالی دستاویز نمبر"}}',
  true, false),
 ('sales',
  '{"ar":"مبيعات","en":"Sales","fr":"Ventes","ur":"فروخت"}',
  '{"ar":"العملاء والصفقات وعروض الأسعار والعقود والفواتير","en":"Clients, deals, quotations, contracts and invoices","fr":"Clients, affaires, devis, contrats et factures","ur":"گاہک، سودے، کوٹیشنز، معاہدے اور رسیدیں"}',
  'M7 18c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm10 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zM7.2 14.6l.9-1.6h7.4c.75 0 1.41-.41 1.75-1.03l3.58-6.49L19.1 4.7l-3.6 6.5H8.5L4.3 2H1v2h2l3.6 7.6-1.35 2.44C4.52 15.37 5.48 17 7 17h12v-2H7l.2-.4z',
  9, 'company', '{company,establishment,freelance}',
  '{"fieldClient":{"ar":"العميل","en":"Client","fr":"Client","ur":"گاہک"},"fieldCaseNumber":{"ar":"رقم الصفقة","en":"Deal number","fr":"Numero d''affaire","ur":"سودے کا نمبر"}}',
  true, false),
 ('procurement',
  '{"ar":"مشتريات","en":"Procurement","fr":"Achats","ur":"خریداری"}',
  '{"ar":"أوامر الشراء والموردون وعقودهم ومدفوعاتهم","en":"Purchase orders, suppliers, their contracts and payments","fr":"Bons de commande, fournisseurs, contrats et paiements","ur":"خریداری کے آرڈر، سپلائرز، معاہدے اور ادائیگیاں"}',
  'M19 6h-2c0-2.76-2.24-5-5-5S7 3.24 7 6H5a2 2 0 00-2 2v12a2 2 0 002 2h14a2 2 0 002-2V8a2 2 0 00-2-2zm-7-3c1.66 0 3 1.34 3 3H9c0-1.66 1.34-3 3-3zm7 17H5V8h14v12z',
  10, 'company', '{company,establishment,freelance,nonprofit,government}',
  '{"fieldClient":{"ar":"المورد","en":"Supplier","fr":"Fournisseur","ur":"سپلائر"},"fieldCaseNumber":{"ar":"رقم أمر الشراء","en":"Purchase order number","fr":"Numero de commande","ur":"آرڈر نمبر"}}',
  true, false),
 ('marketing',
  '{"ar":"تسويق","en":"Marketing","fr":"Marketing","ur":"مارکیٹنگ"}',
  '{"ar":"الحملات وميزانياتها ومواعيدها وموادها","en":"Campaigns, their budgets, dates and materials","fr":"Campagnes, budgets, echeances et supports","ur":"مہمات، بجٹ، تاریخیں اور مواد"}',
  'M18 11v2h4v-2h-4zm-2 6.61c.96.71 2.21 1.65 3.2 2.39.4-.53.8-1.07 1.2-1.6-.99-.74-2.24-1.68-3.2-2.4-.4.54-.8 1.08-1.2 1.61zM20.4 5.6c-.4-.53-.8-1.07-1.2-1.6-.99.74-2.24 1.68-3.2 2.4.4.53.8 1.07 1.2 1.6.96-.72 2.21-1.65 3.2-2.4zM4 9a2 2 0 00-2 2v2a2 2 0 002 2h1v4h2v-4h1l5 3V6L8 9H4zm11.5 3c0-1.33-.58-2.53-1.5-3.35v6.69c.92-.81 1.5-2.01 1.5-3.34z',
  11, 'company', '{company,establishment,freelance}',
  '{"fieldClient":{"ar":"الجهة أو المنتج","en":"Brand or product","fr":"Marque ou produit","ur":"برانڈ یا مصنوعات"},"fieldCaseNumber":{"ar":"رقم الحملة","en":"Campaign number","fr":"Numero de campagne","ur":"مہم کا نمبر"}}',
  true, false),
 ('design',
  '{"ar":"تصاميم","en":"Design","fr":"Design","ur":"ڈیزائن"}',
  '{"ar":"طلبات التصميم ومواعيد تسليمها وملفاتها وفواتيرها","en":"Design requests, delivery dates, files and invoices","fr":"Demandes de design, livraisons, fichiers et factures","ur":"ڈیزائن کی درخواستیں، تاریخیں، فائلیں اور رسیدیں"}',
  'M12 2l-5.5 9h11L12 2zm5.5 11a4.5 4.5 0 100 9 4.5 4.5 0 000-9zM3 21.5h8v-8H3v8z',
  12, 'freelance', '{freelance,establishment,company,individual}',
  '{"fieldClient":{"ar":"العميل","en":"Client","fr":"Client","ur":"گاہک"},"fieldCaseNumber":{"ar":"رقم الطلب","en":"Request number","fr":"Numero de demande","ur":"درخواست نمبر"}}',
  true, false)
on conflict (key) do update set
  names = excluded.names, hints = excluded.hints, icon = excluded.icon, sort_order = excluded.sort_order,
  entity_default = excluded.entity_default, entity_choices = excluded.entity_choices, labels = excluded.labels,
  active = excluded.active, is_default = excluded.is_default;

update public.ui_packs set sort_order = 5 where key = 'clinic';
update public.ui_packs set sort_order = 6 where key = 'engineer';

delete from public.pack_services where pack_key in ('hr','finance','sales','procurement','marketing','design');
insert into public.pack_services (pack_key, service, sort_order, label) values
 ('hr','dashboard',1,null),
 ('hr','team',2,'{"ar":"الموظفون","en":"Employees","fr":"Employes","ur":"ملازمین"}'),
 ('hr','expenses',3,'{"ar":"الرواتب والمصاريف","en":"Payroll and expenses","fr":"Paie et depenses","ur":"تنخواہیں اور اخراجات"}'),
 ('hr','documents',4,'{"ar":"العقود والوثائق","en":"Contracts and documents","fr":"Contrats et documents","ur":"معاہدے اور دستاویزات"}'),
 ('hr','processes',5,'{"ar":"إجراءات التوظيف","en":"Hiring processes","fr":"Procedures de recrutement","ur":"بھرتی کے طریقہ کار"}'),
 ('hr','settings',6,null),

 ('finance','dashboard',1,null),
 ('finance','expenses',2,'{"ar":"المصاريف والإيرادات","en":"Expenses and revenue","fr":"Depenses et revenus","ur":"اخراجات اور آمدنی"}'),
 ('finance','documents',3,'{"ar":"الفواتير والمستندات","en":"Invoices and documents","fr":"Factures et documents","ur":"رسیدیں اور دستاویزات"}'),
 ('finance','risks',4,'{"ar":"المخاطر المالية","en":"Financial risks","fr":"Risques financiers","ur":"مالی خطرات"}'),
 ('finance','team',5,null),
 ('finance','settings',6,null),

 ('sales','dashboard',1,null),
 ('sales','cases',2,'{"ar":"العملاء والصفقات","en":"Clients and deals","fr":"Clients et affaires","ur":"گاہک اور سودے"}'),
 ('sales','expenses',3,'{"ar":"الفواتير والتحصيل","en":"Invoices and collection","fr":"Factures et encaissement","ur":"رسیدیں اور وصولی"}'),
 ('sales','documents',4,'{"ar":"العقود والعروض","en":"Contracts and quotations","fr":"Contrats et devis","ur":"معاہدے اور کوٹیشنز"}'),
 ('sales','team',5,'{"ar":"فريق المبيعات","en":"Sales team","fr":"Equipe commerciale","ur":"سیلز ٹیم"}'),
 ('sales','settings',6,null),

 ('procurement','dashboard',1,null),
 ('procurement','cases',2,'{"ar":"أوامر الشراء","en":"Purchase orders","fr":"Bons de commande","ur":"خریداری کے آرڈر"}'),
 ('procurement','expenses',3,'{"ar":"المدفوعات والمصاريف","en":"Payments and expenses","fr":"Paiements et depenses","ur":"ادائیگیاں اور اخراجات"}'),
 ('procurement','documents',4,'{"ar":"عقود الموردين","en":"Supplier contracts","fr":"Contrats fournisseurs","ur":"سپلائر معاہدے"}'),
 ('procurement','team',5,null),
 ('procurement','settings',6,null),

 ('marketing','dashboard',1,null),
 ('marketing','cases',2,'{"ar":"الحملات","en":"Campaigns","fr":"Campagnes","ur":"مہمات"}'),
 ('marketing','expenses',3,'{"ar":"ميزانية الحملات","en":"Campaign budget","fr":"Budget des campagnes","ur":"مہمات کا بجٹ"}'),
 ('marketing','documents',4,'{"ar":"المواد والمستندات","en":"Materials and documents","fr":"Supports et documents","ur":"مواد اور دستاویزات"}'),
 ('marketing','team',5,'{"ar":"فريق التسويق","en":"Marketing team","fr":"Equipe marketing","ur":"مارکیٹنگ ٹیم"}'),
 ('marketing','settings',6,null),

 ('design','dashboard',1,null),
 ('design','cases',2,'{"ar":"طلبات التصميم","en":"Design requests","fr":"Demandes de design","ur":"ڈیزائن کی درخواستیں"}'),
 ('design','expenses',3,'{"ar":"الفواتير والمصاريف","en":"Invoices and expenses","fr":"Factures et depenses","ur":"رسیدیں اور اخراجات"}'),
 ('design','documents',4,'{"ar":"الملفات والمخرجات","en":"Files and deliverables","fr":"Fichiers et livrables","ur":"فائلیں اور مصنوعات"}'),
 ('design','team',5,null),
 ('design','settings',6,null);
