-- 0155 — المهندس رعد 2026-09-17: «كل واجهة متخصصة، ما ينفع اي خلط ولخبطة».
-- احدى عشرة حزمة كانت بلا مؤشرات خاصة، فتقع كلها على المربعات العامة نفسها
-- («عناصر مفتوحة، مستحقة خلال 7 ايام، متاخرة، مكتملة») مهما اختلف قطاعها.
-- لكل واجهة الان اربعة مربعات بالفاظ عملها، بالاربع لغات. المقاييس والايقونات
-- من المتاح في الشيفرة وحده (count.open/due7/overdue/done، و list/calendar/
-- bell/check/folder/money) فلا مربع يعرض فراغا.
begin;

update public.ui_packs set tiles = '{"default": [{"icon": "list", "label": {"ar": "قضايا مفتوحة", "en": "Open cases", "fr": "Affaires ouvertes", "ur": "کھلے مقدمات"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "جلسات خلال 7 ايام", "en": "Hearings within 7 days", "fr": "Audiences sous 7 jours", "ur": "سات دن میں پیشیاں"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "متاخرة عن موعدها", "en": "Past their date", "fr": "En retard", "ur": "تاخیر شدہ"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "اغلقت", "en": "Closed", "fr": "Cloturees", "ur": "بند شدہ"}, "metric": "count.done"}]}'::jsonb where key = 'legal';

update public.ui_packs set tiles = '{"default": [{"icon": "list", "label": {"ar": "مراجعون قيد المتابعة", "en": "Patients in follow-up", "fr": "Patients en suivi", "ur": "زیر علاج مریض"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "مواعيد خلال 7 ايام", "en": "Appointments within 7 days", "fr": "Rendez-vous sous 7 jours", "ur": "سات دن میں اپائنٹمنٹ"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "مواعيد فاتت", "en": "Missed appointments", "fr": "Rendez-vous manques", "ur": "چھوٹی اپائنٹمنٹ"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "انتهت متابعتهم", "en": "Completed", "fr": "Termines", "ur": "مکمل"}, "metric": "count.done"}]}'::jsonb where key = 'clinic';

update public.ui_packs set tiles = '{"default": [{"icon": "list", "label": {"ar": "مشاريع جارية", "en": "Active projects", "fr": "Projets en cours", "ur": "جاری منصوبے"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "تسليمات خلال 7 ايام", "en": "Deliveries within 7 days", "fr": "Livraisons sous 7 jours", "ur": "سات دن میں ڈیلیوری"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "تاخر تسليمها", "en": "Overdue deliveries", "fr": "Livraisons en retard", "ur": "تاخیر شدہ ڈیلیوری"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "سلمت", "en": "Delivered", "fr": "Livres", "ur": "مکمل"}, "metric": "count.done"}]}'::jsonb where key = 'engineer';

update public.ui_packs set tiles = '{"default": [{"icon": "list", "label": {"ar": "برامج قائمة", "en": "Active programmes", "fr": "Programmes actifs", "ur": "جاری پروگرام"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "حصص خلال 7 ايام", "en": "Sessions within 7 days", "fr": "Seances sous 7 jours", "ur": "سات دن میں سیشن"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "حصص فاتت", "en": "Missed sessions", "fr": "Seances manquees", "ur": "چھوٹے سیشن"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "اكتملت", "en": "Completed", "fr": "Terminees", "ur": "مکمل"}, "metric": "count.done"}]}'::jsonb where key = 'trainer';

update public.ui_packs set tiles = '{"default": [{"icon": "list", "label": {"ar": "طلبات مفتوحة", "en": "Open requests", "fr": "Demandes ouvertes", "ur": "کھلی درخواستیں"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "تستحق خلال 7 ايام", "en": "Due within 7 days", "fr": "Echeance sous 7 jours", "ur": "سات دن میں واجب"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "تاخرت", "en": "Overdue", "fr": "En retard", "ur": "تاخیر شدہ"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "انجزت", "en": "Completed", "fr": "Traitees", "ur": "مکمل"}, "metric": "count.done"}]}'::jsonb where key = 'hr';

update public.ui_packs set tiles = '{"default": [{"icon": "money", "label": {"ar": "مستحقات قائمة", "en": "Open dues", "fr": "Creances ouvertes", "ur": "واجب الادا"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "تستحق خلال 7 ايام", "en": "Due within 7 days", "fr": "Echeance sous 7 jours", "ur": "سات دن میں واجب"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "تجاوزت موعدها", "en": "Past due", "fr": "Echues", "ur": "میعاد گزر گئی"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "سددت", "en": "Settled", "fr": "Reglees", "ur": "ادا شدہ"}, "metric": "count.done"}]}'::jsonb where key = 'finance';

update public.ui_packs set tiles = '{"default": [{"icon": "list", "label": {"ar": "صفقات مفتوحة", "en": "Open deals", "fr": "Affaires ouvertes", "ur": "کھلے سودے"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "متابعات خلال 7 ايام", "en": "Follow-ups within 7 days", "fr": "Relances sous 7 jours", "ur": "سات دن میں پیروی"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "فاتت متابعتها", "en": "Missed follow-ups", "fr": "Relances manquees", "ur": "چھوٹی پیروی"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "اغلقت", "en": "Closed", "fr": "Conclues", "ur": "بند شدہ"}, "metric": "count.done"}]}'::jsonb where key = 'sales';

update public.ui_packs set tiles = '{"default": [{"icon": "folder", "label": {"ar": "اوامر شراء قائمة", "en": "Open purchase orders", "fr": "Commandes ouvertes", "ur": "کھلے آرڈر"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "توريدات خلال 7 ايام", "en": "Deliveries within 7 days", "fr": "Livraisons sous 7 jours", "ur": "سات دن میں سپلائی"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "تاخر توريدها", "en": "Late deliveries", "fr": "Livraisons en retard", "ur": "تاخیر شدہ سپلائی"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "استلمت", "en": "Received", "fr": "Recues", "ur": "موصول"}, "metric": "count.done"}]}'::jsonb where key = 'procurement';

update public.ui_packs set tiles = '{"default": [{"icon": "list", "label": {"ar": "حملات قائمة", "en": "Active campaigns", "fr": "Campagnes actives", "ur": "جاری مہمات"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "تنطلق خلال 7 ايام", "en": "Launching within 7 days", "fr": "Lancement sous 7 jours", "ur": "سات دن میں آغاز"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "تاخر اطلاقها", "en": "Delayed launches", "fr": "Lancements retardes", "ur": "تاخیر شدہ آغاز"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "انتهت", "en": "Finished", "fr": "Terminees", "ur": "ختم"}, "metric": "count.done"}]}'::jsonb where key = 'marketing';

update public.ui_packs set tiles = '{"default": [{"icon": "folder", "label": {"ar": "اعمال قيد التنفيذ", "en": "Work in progress", "fr": "Travaux en cours", "ur": "زیر کام"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "تسليمات خلال 7 ايام", "en": "Deliveries within 7 days", "fr": "Livraisons sous 7 jours", "ur": "سات دن میں ڈیلیوری"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "تاخر تسليمها", "en": "Overdue", "fr": "En retard", "ur": "تاخیر شدہ"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "سلمت", "en": "Delivered", "fr": "Livres", "ur": "مکمل"}, "metric": "count.done"}]}'::jsonb where key = 'design';

update public.ui_packs set tiles = '{"default": [{"icon": "list", "label": {"ar": "اعمال مفتوحة", "en": "Open items", "fr": "Elements ouverts", "ur": "کھلے امور"}, "metric": "count.open"}, {"icon": "calendar", "label": {"ar": "تستحق خلال 7 ايام", "en": "Due within 7 days", "fr": "Echeance sous 7 jours", "ur": "سات دن میں واجب"}, "metric": "count.due7"}, {"icon": "bell", "label": {"ar": "تاخرت", "en": "Overdue", "fr": "En retard", "ur": "تاخیر شدہ"}, "metric": "count.overdue"}, {"icon": "check", "label": {"ar": "انجزت", "en": "Completed", "fr": "Terminees", "ur": "مکمل"}, "metric": "count.done"}]}'::jsonb where key = 'business';

commit;

select key, tiles->'default'->0->'label'->>'ar' as first_tile
from public.ui_packs where active order by sort_order, key;
